### ISSUE TITLE
Suggestion for AP Controls

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#1]
Mike,
This is just a a suggestion for Autopilot type controls which NahanniIV suggested to Vesper recently.
See this thread and the graphic for the the controls. It might be more familiar to people, because it is like Raymarine AP Controls....

http://www.cruisersforum.com/forums/f141/vesper-marine-ais-121248.html

![wilhelmsk](https://user-images.githubusercontent.com/2363959/33513796-c433f9bc-d7ae-11e7-90bd-d15a5a48c538.jpg)

**Comment by Rasbats** [comment]
v0.3 uses this idea.
