### ISSUE TITLE
wiki enhancements.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#102]
HI,

Unfortunately it isn't possible to make a PR against the wiki. Its' a shame, but a fact.

I attach some patches for you to consider. In general, I really like these docs. One good thing is that they are short and on-spot. This means that it's your turn to be the hard task master, since my proposed changes adds a lot of text, perhaps too much. 

[0001-Home-Add-some-general-info.patch.gz](https://github.com/Rasbats/shipdriver_pi/files/5705675/0001-Home-Add-some-general-info.patch.gz)
[0004-Add-new-chapter-Metadata-flow.patch.gz](https://github.com/Rasbats/shipdriver_pi/files/5705676/0004-Add-new-chapter-Metadata-flow.patch.gz)
[0003-Adaptation-add-ons-reference-plugin-wiki.patch.gz](https://github.com/Rasbats/shipdriver_pi/files/5705677/0003-Adaptation-add-ons-reference-plugin-wiki.patch.gz)
[0002-Some-notes-on-Cloudsmith.patch.gz](https://github.com/Rasbats/shipdriver_pi/files/5705678/0002-Some-notes-on-Cloudsmith.patch.gz)

**Comment by leamas** [comment]
Hm... forgot to say: Shouldn't here be some info (or links) how to set up the crucial environment variables in the builders?

**Comment by leamas** [comment]
More thoughts: The info in CI-md on how to setup a cloudsmith repo is very different from the wiki. I'm not saying that any of these descriptions is "right", but we should probably align them a little to not confuse users.

**Comment by Rasbats** [comment]
>0002-Some-notes-on-Cloudsmith.patch.gz

![0 circleci](https://user-images.githubusercontent.com/2537240/102459019-fbb39d80-403c-11eb-81c4-e626381ca2af.jpg)

Cloudsmith now needs the invite, unless you can see another way to create the repos. No free organisation (sic).

**Comment by Rasbats** [comment]
The 'managed' repo is now 'managed_plugins'. Scans better.

**Comment by leamas** [comment]
Hm... I just made a try with a new user opencpn.repos on cloudsmith. The situation for me was that I could create a organisation, it was just to push the button "Create organization". Then I could proceed to make a repo, iit's here: https://cloudsmith.io/~ocpntest/repos/ocpn-stable/packages/

It's not that I have anything against Rick's attempt to create a common place. However, it's actually a barrier to a new developer since anything manual takes some time (and even more time if you need to find the email addresses out there). The automatic flow is IMHO an advantage.

**Comment by Rasbats** [comment]
Tried to register a new Cloudsmith account a few days ago for testing the process. Cloudsmith came back some days later with a request for money for creating an organisation. You can register and accept invites but not make an organisation. This is why I think we are now limited to [https://cloudsmith.io/orgs/opencpn/](url)

**Comment by Rasbats** [comment]
![cloudsmith](https://user-images.githubusercontent.com/2537240/102473033-de87ca80-404e-11eb-8266-51b56af01068.jpg)

Maybe the free plan will continue without the extra features?

**Comment by leamas** [comment]
I actually think so. I now remeber I got similar messages after a week or so, as did the others which eventually started to use cs (I was the firsts to do so in the opencpn project).

If you read the text carefully it seems to refer to features of the paid plan which will end. They still have a very strong open-source commitment.

**Comment by Rasbats** [comment]
Ok. I will add your edit. Wiki is now [https://github.com/Rasbats/managed_plugins/wiki](url)

Did you see this:
>It all went well until I ran into the permission denied problem. Is there a script for Windows that will give the build scripts permission to execute.

I tried your git methods without success. Google had another fix which did not work. Unless you have another idea I will have to add Jon's Chmod, following his frontend2 script lines. Worked before with ShipDriver.

**Comment by leamas** [comment]
This is just a detail, but an annoying one. I'll eat my breakfast (late...) and try to spin up a Windows VM to investigate further. Give me some time...

**Comment by leamas** [comment]
BTW: I noticed the new overall more step-by-step approach. Like it.

**Comment by Rasbats** [comment]
Had to use the chmod in UKTides - .travis.yml and .circleci/config.yml.

[https://github.com/Rasbats/UKTides_pi](url)

**Comment by leamas** [comment]
This seems to work for me on a reasoanble updated windows 10: Note how the _git ls-files -s_ command displays the execute permissions in the first  octal digits: 644 is really rw for owner, just read for others. 755 means read, write and execute for owners, read + execute for all others

Octal digits... isn't unix great ;)

```


C:\> echo "foo" > foo.sh

C:\> git add foo.sh

C:\> git ls-files -s foo.sh
100644 0312d059ac5999891c861a755b9522991669f2e0 0       foo.sh

C:\ >git commit -am "Adding foo.sh"
[master 04bb9d0] Adding foo.sh
 1 file changed, 1 insertion(+)
 create mode 100644 foo.sh

C:\> git ls-files -s foo.sh
100644 0312d059ac5999891c861a755b9522991669f2e0 0       foo.sh

C:\> git update-index  --chmod=+x foo.sh

C:\> git ls-files -s foo.sh
100755 0312d059ac5999891c861a755b9522991669f2e0 0       foo.sh

C::\> git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   foo.sh


C:\ > git commit -m "Adding execute permissions to foo.sh"
[master c264e2e] Adding execute permissions to foo.sh
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 foo.sh

C:\> git push ...
```

**Comment by leamas** [comment]
Also note the commit message,at bottom. Here you see that the mode bits  actually are changed.

**Comment by Rasbats** [comment]
My eyes are glazing over! But what happens when the files are copied from ShipDriver to TideFinder. Will the execute permissions remain?

**Comment by leamas** [comment]
Since you are on windows and are using windows to copy file you will drop the permissions. Windows just doesn't knows they exist, and thus cannot copy them. 

The way to retain them is use git to copy them. This is some more acrobatic git steps, something like

    > cd TideFinder
    > git remote add shipdriver https://github.com/Rasbats/shipdriver_pi.git
    > git remote update shipdriver
    > git checkout shipdriver/master cmake

or so... The alternative is to add the permissions again after copying. Or make a script which does. But the again, the git method seems more robust.

**Comment by leamas** [comment]
BTW: It might be safer to make a _git rm -rf cmake_ first; otherwise you might keep old, renamed files in cmake.

**Comment by Rasbats** [comment]
It may be silly but what is the difference between me using chmod and the builder VM doing exactly the same thing. Using git for copying is too complicated (for me). The permissions only need adding for the new managed plugin. I will try that method first.

**Comment by leamas** [comment]
Just adding permissions on the new managed plugin files should be fine.  

The problem is about being consistent. It doesn't make much of a difference on Windows , but on all other platforms storing a script meant to be executed with 644 permissions is inconsistent and leads to developer confusion, occasional toolchain warnings etc.  

And since the script should be stored with proper 755 permissions anyway, the chmod commands are useless. They are a mere symptom on the underlying problem that scripts are stored with wrong permissions.

**Comment by Rasbats** [comment]
Ok. Got it.

**Comment by leamas** [comment]
I  have some time... let's put some flesh on the bones. If you look at the script files in ci, the first line is something like

    #!/usr/bin/env bash

This line is called a shebang, and is really some info to the shell how to run the file i. e.., which interpreter to use.  Implicitly, a shebang indicates that the file is an executable script.

However, in order to be executed, a file must have 755 permissions (more or less). This means that a file with a shebang but without execute permissions is a contradiction confusing users, developers and tools.

That is, on all platforms besides windows.

**Comment by leamas** [comment]
BTW: looking at the new wiki. It looks great. One basic remark is that this not only my workflow, you should also have credits. So, please add Mike or just 'I' in the managed_plugins top README.md.

Besides: the wiki now has links to  README-git.md.  This was OK when the wiki was in the same repos as shipdriver, but files now. How should we handle this? Copying the file as-is from shipdriver? Convert it to a page in the wiki, and just have a link in shipdriver docs? Or?

**Comment by Rasbats** [comment]
Just found an edit (plugin name) is needed in ci/circleci-build-flatpak.sh for the manifest. Can the script pick up this from anywhere else?

**Comment by leamas** [comment]
I looked at it . It could probably just use a wildcard.... stay tuned for a PR

**Comment by Rasbats** [comment]
PR done but I am fighting a problem with appveyor.
**ShipDriver**
`-- Computing checksum in ShipDriver-2.5-msvc-10.0.14393.xml
upload.bat
Using CLOUDSMITH_API_KEY: e481...
C:\project\opencpn\shipdriver_pi\build>cloudsmith push raw --no-wait-for-sync     --name ShipDriver-2.5-msvc-10.0.14393-metadata     --version 2.5.63+320.05e4d66     --summary "Plugin metadata for automatic installation"     opencpn/shipdriver-alpha ShipDriver-2.5-msvc-10.0.14393.xml 


**TideFinder**
  -- Computing checksum in TideFinder-1.2-msvc-10.0.14393.xml
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal [C:\project\opencpn\TideFinder_pi\build\tarball.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: cmake -P C:/project/opencpn/TideFinder_pi/build/build_tarball.cmake [C:\project\opencpn\TideFinder_pi\build\tarball.vcxproj]`

upload.bat does not seem to run. Any ideas?

**Comment by leamas** [comment]
Could you please link to the complete logs?

**Comment by Rasbats** [comment]
[https://ci.appveyor.com/project/Rasbats/tidefinder-pi/builds/36891569](url)
[https://ci.appveyor.com/project/Rasbats/shipdriver-pi](url)

**Comment by Rasbats** [comment]
Yes, I saw the fatal error but it builds locally with your batch file without showing the error. There is a windows bug I found which appears when making a debug verson (involving wxUniCharRef). Tried changing build.bat to make a release not relwithbuginfo version but the problem remained.

**Comment by Rasbats** [comment]
Trying to remove an unused extern reference in the source code and rebuild with appveyor.

**Comment by leamas** [comment]
It looks like the build is OK, but that it fails in the script build_tarball.cmake. This is a script which is created and run in Targets.cmake. We need  to take look at that script to see if it's anything which is obviously wrong.

Could you rebuild after applying this patch, and link to new logs?:

```
--- a/cmake/Targets.cmake
+++ b/cmake/Targets.cmake
@@ -100,12 +100,15 @@ function (tarball_target)
     message(STATUS \"Computing checksum in ${pkg_displayname}.xml\")
   "
   )
+  message(STATUS "TARBALL_SCRIPT: ${_tarball_script}")
   file(WRITE "${CMAKE_BINARY_DIR}/build_tarball.cmake" "${_tarball_script}")
   add_custom_target(tarball)
   add_custom_command(
     TARGET tarball # Compute checksum
     COMMAND cmake -P ${CMAKE_BINARY_DIR}/build_tarball.cmake
+    COMMENT "Building tarball..."
     VERBATIM
+
   )
   add_dependencies(tarball tarball-conf)

```

**Comment by leamas** [comment]
hm... The error is MSB3073. There is a hint on that [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f70c2425-14de-49cf-b228-d29548c9ef87/getting-error-msb3073?forum=msbuild). Is it that there are forward slashes in the invocation `cmake -P C:/project/opencpn/TideFinder_pi/build/build_tarball.cmake` ? Generally, although windows uses \\ it does accept / at least in API:s. But perhaps, occasionally, not on the command line?

If so, this should be fixed by amending to the patch like this:
```

--- a/cmake/Targets.cmake
+++ b/cmake/Targets.cmake
@@ -100,11 +100,14 @@ function (tarball_target)
     message(STATUS \"Computing checksum in ${pkg_displayname}.xml\")
   "
   )
+  message(STATUS "TARBALL_SCRIPT: ${_tarball_script}")
   file(WRITE "${CMAKE_BINARY_DIR}/build_tarball.cmake" "${_tarball_script}")
   add_custom_target(tarball)
+  file(TO_NATIVE_PATH "${CMAKE_BINARY_DIR}/build_tarball.cmake"  _path)
   add_custom_command(
     TARGET tarball # Compute checksum
-    COMMAND cmake -P ${CMAKE_BINARY_DIR}/build_tarball.cmake
+    COMMAND cmake -P ${_path}
+    COMMENT "Building tarball..."
     VERBATIM
   )

```

Could you give it a  try?

**Comment by Rasbats** [comment]
Building now. Off for situps and breakfast.

**Comment by Rasbats** [comment]
Had to wait. Failed again. Maybe the MakeDateLabel function needs looking at. Have another look later.

**Comment by leamas** [comment]
Ah, sorry. Now I see the error. And yes, build errors are fatal. Forget my previous posts on this.

cmake is so utterly incompetent when it comes to error handling. The simple requirement to stop the build on first error is just not possible...

**Comment by Rasbats** [comment]
Have restored Targets.cmake to the ShipDriver version. Now chasing the bug in my code. VS2017 is not being very helpful. The dll made locally is running fine.

Your work allowing a local build is really helpful in examining code.

**Comment by Rasbats** [comment]
Ok... finally found the error. The same code is in OpenCPN master and that does not seem to be causing a problem.
To paraphrase: wxString mtz;   
                       mtz[1] = 'D'; // this caused the error

**Comment by leamas** [comment]
Hm... when you create a wxString like that it's empty, has zero length and neither mtz[0] nor mtz[1] are allocated. So it makes sense that it fails. OTOH, it should then fail with a illegal pointer rather than a linkage error... sort of interesting. 

But in the end, the behaviour  of these two statements  are probably undefined, and if you have found it it main OpenCPN it should perhaps be filed as a bug. Undefined or not (not completely sure), it's obviously something causing problems , in particular with msvc.

**Comment by Rasbats** [comment]
tbc. Leaving open until all the above is reviewed.

**Comment by Rasbats** [comment]
Closing this one and moving the mtz issue to another.
