### ISSUE TITLE
Plugin .dll not added to tarball

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#107]
Version v2.5.63 the dll was in the tarball, with 2.5.64 it is not??? This problem is also a problem with TideFinder, which uses the ShipDriver template. UK Tides from 5 days ago is correct.

This seems to be a Windows problem. Checked tarballs for Ubuntu and the .dll is present.

**Comment by Rasbats** [comment]
Two files for comparison:
[working.uktides.appveyor.yml.txt](https://github.com/Rasbats/shipdriver_pi/files/5719373/working.uktides.appveyor.yml.txt)
[not.working.appveyor.yml.txt](https://github.com/Rasbats/shipdriver_pi/files/5719375/not.working.appveyor.yml.txt)

**Comment by Rasbats** [comment]
Been using TideFinder as a playground to avoid messing here.
Looks like a debug version for Windows is always made??? No release .dll to copy across.

**Comment by Rasbats** [comment]
>ci: appveyor: Drop git bash dependency, use a bat file instead.

Went back to this commit and apart from finding wxWidgets for a local build it worked correctly. Added the fix for finding wxWidgets and it still built correctly.

**Comment by Rasbats** [comment]
>cmake: Targets: rewrite complicated deps, part 2. 

The commit above is where things went bad for msvc. 

Will try reverting these changes in the commit:
**cmake: Handle -fvisibility compiler flag better (#104).**

**Comment by Rasbats** [comment]
Copied Targets.cmake from **Targets: rewrite complicated deps, part 1.** to
 **cmake: Handle -fvisibility compiler flag better (#104).**

This looks good at the moment. I will look at your commits after -fvisibility to see if anything else needs working on.

**Comment by Rasbats** [comment]
No... the typo fix caused the build to fail. Reverting this one again.

**Comment by Rasbats** [comment]
Alec... Is there anything now in Targets.cmake that will cause a problem?

**Comment by leamas** [comment]
is this still a problem? I cannot reproduce it.

**Comment by Rasbats** [comment]
I left this open because I did a revert: **Revert: cmake: Targets: rewrite complicated deps, part 1.** This then allowed the local build with Windows. wxWidgets were found.

After this your pull request: **cmake: Targets: rewrite complicated deps, part 1.** you made the pull request: **cmake: Targets: rewrite complicated deps, part 2.** In this request you edited 'Targets.cmake'. Everything seems to be ok but I wondered if the changes in the part 2. pull request for Targets.cmake were important,

**Comment by leamas** [comment]
OK, I see. Yes, we need to re-introduce that rewrite, the current state is just too messy. I'll  look into it. Please leave bug open (and thanks for both finding and work around my stupid mistakes...)

**Comment by Rasbats** [comment]
**Windows: fix the targets rewrite #111**
The builders like this but it does not build locally with VS2017. wxWidgets is not found even with the fix in PluginLibs.cmake. Something in Targets.cmake must be the issue.

**Comment by Rasbats** [comment]
```
if (WIN32 AND NOT MINGW)
  set(_mvdir rename)
 else ()
  set(_mvdir mv)
endif ()

```
This is missing from your update of Targets.cmake. Is this significant?

**Comment by leamas** [comment]
Significant in the sense that it's always nice to be able to remove 5-6 lines, yes. 

I could remove them after finding out it was possible to use _cmake -E rename_ instead. This works on all platforms from 3.2, which older than anything supported by us. As a bonus, it actually works on Windows (rename doesn't).
¨

**Comment by leamas** [comment]
> The builders like this but it does not build locally with VS2017. wxWidgets is not found even with the fix in PluginLibs.cmake. Something in Targets.cmake must be the issue.

It's hard to say what the problem might be without build logs. OTOH, since it works on appveyor something is different in your local environment when compared to appveyor's.

Are you sure that not findind wxWidgets is the first error encountered? The MS builders has this strange habit of continuing despite earlier errors, ending up in some unrelated error further down the road.

**Comment by Rasbats** [comment]
Sorry, my mistake. I was trying to build the debug version. Making the release version works fine. Thanks. If debug was not intended to be possible I will close this issue.

**Comment by leamas** [comment]
It's certainly intended to work. Still, this is some progress. 

To be honest, I have been fighting with what cmake calls generator expressions, you find them by searching for `$<CONFIG>`. They are related to this, and I cannot really test them (they are more or less Windows-specific) without using my Windows VM  which I havn't access to here. I'm on weekend on the polar forest...

We should dig deeper into this. A first step: Could you specify the exact step(s) you use on the command line to trigger the error?

**Comment by Rasbats** [comment]
Will look at this tomorrow. Meanwhile... I am dead jealous. Good memories of snow and ice!

**Comment by Rasbats** [comment]
Used CMake with just the github repo. VS2017 for the builds, not command line. 
Python not found so I entered the location. wxWidgets is in my PATH.
Debug failed.
Release worked and produced a good tarball.
Logs attached.

[debug.txt](https://github.com/Rasbats/shipdriver_pi/files/5758706/debug.txt)
[release.txt](https://github.com/Rasbats/shipdriver_pi/files/5758707/release.txt)

Finishing another project so not much time at this end.

**Comment by leamas** [comment]
Oops... it seems that your setup tries to build each and every target. What is supposed to work (Debug or RelWithDebInfo etc.) is _make tarball_.   However, your build fails when trying to run _make flatpak_ which obviously isn't expected to work on Windows.

It does so after building the dont-use-plain-make target i. e., after trying a plain _make_  which isn't supposed top work either. If it was sane, it should stop there, but it just tries next target.

Somehow, you need to setup your environment  to just build the tarball target.

**Comment by Rasbats** [comment]
This is the release tarball made locally:
[ShipDriver-2.5.63+2101010714.4033484_flatpak-18.08-win32.tar.gz](https://github.com/Rasbats/shipdriver_pi/files/5758912/ShipDriver-2.5.63%2B2101010714.4033484_flatpak-18.08-win32.tar.gz)

Apart from the name it looks like it has everything needed. The .exe produced at the same time would work like a legacy installer, I think.

**Comment by leamas** [comment]
No, this won't fly. The only supported targets are 'tarball' and 'pkg'. And your build obviomake flatpakusly tries to build both the default target corresponding to a  plan _make_ and the flatpak target corresponding to _make flatpak_, none of which meaningful on Windiows. 

I would be really surprised if there wasn't some kind of setting in VS to set the targets to build. Please look  into this. There might very well be other problems, but we need to get rid of these first.

**Comment by leamas** [comment]
A quick search gives the following for VS 2017:

> In a folder with multiple build targets, you can specify which CMake target to build: Choose the Build item on the CMake menu or the CMakeLists.txt context menu to specify the target. If you enter Ctrl+Shift+B in a CMake project, it builds the current active document.

**Comment by leamas** [comment]
hm... I have fired my windows VM. I don't have the complete VS installed, it's basically just a scratch build box. However, the VS command line tools are installed. Using these I can run the following:

```
> cmake  -T v141_xp  -G "Visual Studio 15 2017" --config RelWithDebInfo  ..
> cmake --build . --target tarball --config RelWithDebInfo
```
Which produces something which looks lika a sane tarball and metadata file. We already knew this. Trying to make a Debug build using

```
> cmake  -T v141_xp  -G "Visual Studio 15 2017" --config Debug  ..
> cmake --build . --target tarball --config Debug
```

also looks perfectly fine. So, it looks possible to build both Debug and RelWithDebInfo builds on WIndows for me, using the VS command line tools (and after installing the deps).

Thoughts?

**Comment by Rasbats** [comment]
I think that using the download bat file the config is built in. So the type of build is set for VS and that build works. All the linkages etc are set for that build and so everything is ok if VS builds for that type.

Nothing needs changing for the workflow. Time to close this one.
