### ISSUE TITLE
Adding a beta version to OpenCPN/plugins beta branch

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#108]
Following the managed_plugins wiki guide the metadata files were added to the local plugins beta branch. 

Pull request was then made. However the check for the PR failed. Asked Dave about this.

![After sending pull request](https://user-images.githubusercontent.com/2537240/102773535-515fb100-4381-11eb-9124-d29bd947b692.jpg)
![pul request failed check](https://user-images.githubusercontent.com/2537240/102773537-5290de00-4381-11eb-8e7b-48cca1395f7d.jpg)

**Comment by Rasbats** [comment]
Failure advice from github.

![failure advice from github](https://user-images.githubusercontent.com/2537240/102774086-35104400-4382-11eb-8973-a0f6300f0ed9.jpg)

**Comment by Rasbats** [comment]
Thanks for the reference Rick: 
[https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/](url)

Can this be factored in Alec? config.yml?

**Comment by Rasbats** [comment]
Disregard my config.yml request above.

After Dave did a fix another try...

![pull request failed check 2 mingw-x86_64 error](https://user-images.githubusercontent.com/2537240/102797529-b6c69880-43a7-11eb-9790-5eefc77e5a60.jpg)

Removed mingw from the metadata files and the checks passed. Alec... could you look at mingw when you have a minute?

**Comment by leamas** [comment]
As stated in rhe wrong place earlier: mingw triggers a bug in the plugin's project beta branch:https://github.com/OpenCPN/plugins/issues/313

**Comment by leamas** [comment]
As for the github actions in place for the plugins project I don't have any clue whatsoever. I'm not involved in this code, and at a glance it isn't poissibkle to review it.The problems with set-env should IMHO be filed at the plugins project with a heads-up to jon gough who is the author if I get it right.

**Comment by Rasbats** [comment]
Thanks. I will raise the issue at OpenCPN/plugins.
