### ISSUE TITLE
Plugins using JSON not loading Ubuntu 20.04

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#116]
Neither ShipDriver or UKTides will load with OpenCPN 5.2.4 on Ubuntu Focal. Problem seems to stem from libjson.

```
19:28:03.400 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/mike/.local/lib/opencpn/libShipDriver_pi.so
19:28:03.400 MESSAGE pluginmanager.cpp:2124 Plugin is compatible by elf library scan: true
19:28:03.400 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /home/mike/.local/lib/opencpn/libShipDriver_pi.so
19:28:03.401   ERROR dlunix.cpp:162 libjsoncpp.so.1: cannot open shared object file: No such file or directory
19:28:03.401 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /home/mike/.local/lib/opencpn/libShipDriver_pi.so 
19:28:03.401 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/mike/.local/lib/opencpn/libotcurrent_pi.so
19:28:03.401 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/mike/.local/lib/opencpn/libUKTides_pi.so
19:28:03.401 MESSAGE pluginmanager.cpp:2124 Plugin is compatible by elf library scan: true
19:28:03.401 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /home/mike/.local/lib/opencpn/libUKTides_pi.so
19:28:03.402   ERROR dlunix.cpp:162 libjsoncpp.so.1: cannot open shared object file: No such file or directory
19:28:03.402 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /home/mike/.local/lib/opencpn/libUKTides_pi.so 
```

**Comment by Rasbats** [comment]
TideFinder was recently made with the alternative workflow and this plugin works without a problem.

**Comment by leamas** [comment]
The problem is that is dynamically linked, using static libs is the simple work around. I'll look into it, later. To a meeting now...

**Comment by leamas** [comment]
Looking more into this. Seems like the build host has a system libjsoncpp available, and the build used this -- which basically is the right thing to do. There are two options:

  - Document the fact that this plugin requires the libjsoncpp1 library, which could and should be installed using `apt install libjsoncpp1`
  -  Force the build to bundle the library by adding the  `-DUSE_SYSTEM_JSONCPP:BOOL=OFF` to the cmake options (and/or remove the libjsoncpp build dep from cI/control)


Thoughts?

**Comment by Rasbats** [comment]
-DUSE_SYSTEM_JSONCPP:BOOL=OFF 
This seems like the best way to go. CMakeLists.txt is a useful home file for changes like this. I will give it a go.

**Comment by leamas** [comment]
Please don't do it in CMakeLists.txt, do it in ci/circleci-build-debain instead.  Other users have other needs, there is no reason to hardcode it.

If you do, you might as well drop the libjsoncpp-dev line from ci/control since that omne will not be used. In fact, you could make just this change, since the build will use the bundled sources if there is no system library available. 

However, adding the cmake option to the ci script makes things more visible without any harm.

**Comment by Rasbats** [comment]
But ... thinking of my workflow. At the moment we copy all the ./ci stuff to a new plugin. If we use the system json in a future plugin do I need to make a note about this feature of the script?

**Comment by leamas** [comment]
>  At the moment we copy all the ./ci stuff to a new plugin

In general, this will not work. The problem is the dependencies, which just will be different for different plugins (think of photolayer, all of a sudden we had to cope with tiff and geotiff).

OTOH, we could minimize the impact. Thinking in these lines, make no changes to circleci-build-debian,  just drop libwxjson the line from ci/control.

In which case the corresponding line in generic-build-raspbian should also be dropped for the same reason. Will add cycles to the raspbian builds...

**Comment by Rasbats** [comment]
>OTOH, we could minimize the impact. Thinking in these lines, make no changes to circleci-build-debian, just drop libwxjson the line from ci/control.

>In which case the corresponding line in generic-build-raspbian should also be dropped for the same reason. Will add cycles to the raspbian builds...

This approach looks good. The lines can be commented out, with a note. libtinyxml is going to be my next problem and the same approach could be used.

**Comment by leamas** [comment]
I made a PR #118, trying to sort out files which should be configured to a separate dir

**Comment by Rasbats** [comment]
Ok. Can I use the # symbol to comment out lines in 'build-deps/control'. That way I can leave a note for myself for the future.
Need to spend some time with other plugins and the wiki to get things in line.

**Comment by leamas** [comment]
Yes and no. You cannot have it between the lines with a  trailing comma, they are scanned as a single line. But you can put the comment before Build_depends or after the last line without a comma

**Comment by leamas** [comment]
So, practically, put a # before the  line and move it ahead of Build-Depends

**Comment by leamas** [comment]
OTOH: Why? I would just remove the line. It's still in git, should you need it. Better then to document some "common dependencies" or so in for example your wiki. And put  link to the wiki as a comment in control

**Comment by Rasbats** [comment]
>Better then to document some "common dependencies" or so in for example your wiki. And put link to the wiki as a comment in control

This sounds good. ShipDriver working with json for sail option is ok on Ubuntu Focal and Windows. Going to TideFinder to align the files with ShipDriver.

**Comment by Rasbats** [comment]
Working with ShipDriver. Closing this issue.
