### ISSUE TITLE
Placeholder for previous error in the code

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#123]
Ok... finally found the error. The same code is in OpenCPN master and that does not seem to be causing a problem.
To paraphrase: wxString mtz;
mtz[1] = 'D'; // this caused the error

@leamas
Contributor Author
leamas commented on 19 Dec 2020

Hm... when you create a wxString like that it's empty, has zero length and neither mtz[0] nor mtz[1] are allocated. So it makes sense that it fails. OTOH, it should then fail with a illegal pointer rather than a linkage error... sort of interesting.

But in the end, the behaviour of these two statements are probably undefined, and if you have found it it main OpenCPN it should perhaps be filed as a bug. Undefined or not (not completely sure), it's obviously something causing problems , in particular with msvc.

**Comment by leamas** [comment]
In OpenCPN, this seems like 
```
        if( lat > 20.0 ){
            wxString mtz;
            switch( ptcmgr->GetStationTimeOffset( pIDX ) ) {
            case -240:
                mtz = _T( "AST" );
                break;
            case -300:
                mtz = _T( "EST" );
                break;
            case -360:
                mtz = _T( "CST" );
                break;
            }

            if( mtz.Len() ) {
                if( m_graphday.IsDST() ) mtz[1] = 'D';

                m_stz = mtz;
            }
        }

```

Here, it's seemingly no problem.  When mtz[1] is referenced it's length is 3, and mtz[1] is allocated. If the length 0, the alternative, the  mtz.Len() test fails and nothing is referenced

**Comment by Rasbats** [comment]
No issue was raised for this with OpenCPN. The problem came up in TideFinder. Closing.
