### ISSUE TITLE
installation in /usr/lib64 should be used for Linux 64bit arch

### ISSUE THREAD

**Issue by dominig** [Rasbats/shipdriver_pi#131]
Installation is done in /usr/lib even for 64bits arch what is not the new standard used by OCPN main program anymore.
I can propose a patch which fix the issue.

diff --git a/cmake/PluginInstall.cmake b/cmake/PluginInstall.cmake
index d482bbd..b2f4250 100644
--- a/cmake/PluginInstall.cmake
+++ b/cmake/PluginInstall.cmake
@@ -35,10 +35,18 @@ elseif (WIN32)
   endif ()
 
 elseif (UNIX)
-  install(
-    TARGETS ${PACKAGE_NAME}
-    RUNTIME LIBRARY DESTINATION lib/opencpn
-  )
+  if (${ARCH} STREQUAL "x86_64") 
+    install(
+      TARGETS ${PACKAGE_NAME}
+      RUNTIME LIBRARY DESTINATION lib64/opencpn
+    )
+  else ()
+    install(
+      TARGETS ${PACKAGE_NAME}
+      RUNTIME LIBRARY DESTINATION lib/opencpn
+    )
+  endif()
+
   if (EXISTS ${PROJECT_SOURCE_DIR}/data)
     install(DIRECTORY data DESTINATION share/opencpn/plugins/${PACKAGE_NAME})
   endif ()

**Comment by Rasbats** [comment]
Now updated. Please can you check all is well. Thanks.

**Comment by Rasbats** [comment]
Build failed due to ldd.

sh -c "ldd  build/app/*/lib/opencpn/*.so"
ldd: build/app/*/lib/opencpn/*.so: No such file or directory

Removed this from config.yml for debian builds.

**Comment by dominig** [comment]
Then in the arch detection cmake, where distros are detected, it would be a good idea to set up a variable which would be used later to decide where to install.

**Comment by leamas** [comment]
No. That code is IMHO already too complex, and should be limited to the core use-cases -- and native plugins besides Debian/Ubuntu is not such a case.

The simple solution would be to add a cmake option like OCPN_LIBDIR which defaults to "lib" but could be set to other values as required. I see no reason for anything more complicated than that.

**Comment by Rasbats** [comment]
@dominig ... can we close this issue?
