### ISSUE TITLE
Fails to build locally on Windows

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#150]
Needed to add **set(BUILD_SHARED_LIBS TRUE)** to 'PluginLibs.cmake', to allow the build to find wxWidgets on Windows. This was needed for a local build.

The builder services did not have a problem with this.

```
set(wxWidgets_USE_LIBS base core net xml html adv stc)
set(BUILD_SHARED_LIBS TRUE)

find_package(wxWidgets REQUIRED base core net xml html adv stc)
if (MSYS)
  # This is just a hack. I think the bug is in FindwxWidgets.cmake
  string(
    REGEX REPLACE "/usr/local" "\\\\;C:/MinGW/msys/1.0/usr/local"
    wxWidgets_INCLUDE_DIRS ${wxWidgets_INCLUDE_DIRS}
  )
endif ()
include(${wxWidgets_USE_FILE})
```

**Comment by leamas** [comment]
This looks like a perfectly sane patch. Plugins are by definition shared libs, so I cannot see any problem with this definition. And, it's in the right place. In short: the right thing to do.

As I see it this bug can be closed.

**Comment by Rasbats** [comment]
Thanks.

**Comment by leamas** [comment]
Sorry, I was too quick, again. I think it would be much better if you moved this definition to PluginCompiler instead, that's where it belongs.

**Comment by Rasbats** [comment]
Ok... I will take care of that.
