### ISSUE TITLE
Plugin using template fails on RPi 3B+

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#151]
[https://github.com/Rasbats/TideFinder_pi/issues/6](https://github.com/Rasbats/TideFinder_pi/issues/6)

TideFinder does not use Json but is copied from ShipDriver. Should it have been removed? Is this the case for other plugins not using Json?

**Comment by Rasbats** [comment]
This one as well...
[https://github.com/Rasbats/otcurrent_pi/issues/16](https://github.com/Rasbats/otcurrent_pi/issues/16)

**Comment by Rasbats** [comment]
Started compiling tarballs on the Pi, installing CMake and wxWidgets. After a restart without doing anything else the plugin now runs ok.

**Comment by leamas** [comment]
> TideFinder does not use Json but is copied from ShipDriver. Should it have been removed? 

Yes

> Is this the case for other plugins not using Json?

Yes. In general, carrying libraries which are not used should be avoided, code should be kept as small as possible.  We have to live with the fact that plugins has different dependencies, that's just how it is.

OTOH, since these things lives in separate libraries they are easy to customize.

**Comment by leamas** [comment]
BTW: Please don't hesitate to send me a heads-up when you file bugs. I am not notified about new bugs here.

**Comment by Rasbats** [comment]
Leaving this as a reminder of work needed for TideFinder and otcurrent.
