### ISSUE TITLE
RFE: No hooks for beta release in version

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#157]
The semantic versioning scheme we use have place for a string like 'beta' or 'rc'. However, there are no hooks in the generic files in cmake/. Would be nice  to have...

**Comment by keesverruijt** [comment]
Yes! Second that for radar_pi. Especially since our workflow uses tags containing 'beta' to steer results to the beta binary repo, and now we can't name releases the same as our tag.

**Comment by leamas** [comment]
@keesverruijt : There is already a patch added to my PR :)

**Comment by leamas** [comment]
Fixed in #160. Closing
