### ISSUE TITLE
RFE: i18n gettext support.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#165]
The basic gettext support is the ability to create a .pot file which corresponds to actual sources.  This should be trivial, we already depends on the gettext tools and have a defined list of sources.

It's still unclear to me if the msgmerge step should be done in the plugin, merging actual translations. Or if msgmerge is done in crowdin, using the possibly more updated translations available there.

**Comment by Rasbats** [comment]
> if msgmerge is done in crowdin

Adds another layer of complication/change. The idea is great but I think this could wait until other stuff is well tested. How would it integrate with the gough workflow?

**Comment by leamas** [comment]
Anyway, msgmerge should *not* be done in the plugin, talked to Pavel. It's just a question about generating the pot-file. This has been part of many plugins, but became collateral damage when converting to  plugin installer. It should be trivial to fix.

**Comment by Rasbats** [comment]
Normally I would make the pot-file, send it to Hakan and he would put it on Crowdin. Translations are done and Hakan makes a PR to my repo, which incorporates the translations. So does Hakan do the msgmerge? Translations have always caused me problems;)

**Comment by leamas** [comment]
>  So does Hakan do the msgmerge?

Yes, using the existing translations on Crowdin.

> Translations have always caused me problems;)

The new docs are at https://leamas.github.io/ocpn-manuals/ocpn-dev-manual/5.3.1/i18n.html. Do they look sound?
