### ISSUE TITLE
RFE: Enhance arm64 builds using circleci and/or travis.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#171]
With some hands-on, it seems possible to use both circleci and travis to build arm64 plugins, see  https://github.com/OpenCPN/OpenCPN/issues/2178. We should move one of these, parhaps both, since using the official hardware is so much simpler than using my private builder.

**Comment by Rasbats** [comment]
Happy to help with this. But I can't help feeling that Android might have higher priority for users.

**Comment by leamas** [comment]
Agreed. 

Note that using the atm64 builders is should be possible to run android docker images without qemu hardware emulation, should simplify..

Also note that by pushing the arm64 flatpak builds wehave  a working alternative for all sorts of Linuxes on arm64. I wan't to make this available early, to avoid the pressure to create Debian/Ubunitu/Raspbian/what not plugins orn arm64.

**Comment by Rasbats** [comment]
"I wan't to make this available early, to avoid the pressure to create Debian/Ubunitu/Raspbian/what not plugins orn arm64"
Yes... I see the value of this.

**Comment by leamas** [comment]
Fixed by #172. Closing.
