### ISSUE TITLE
Flatpak builds not complete.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#175]
It has been decided that 5.6.0 will, w r t flatpak, support:

  - aarch64/runtime 20.08
  - x86_64/runtime 18.08
  - x86_64/runtime 20.08.

We need to configure shipdriver to build all of these.

**Comment by Rasbats** [comment]
A P would be appreciated when you have time available. I would like to have as many plugins ready as possible for 5.6.0 in whatever flavour. I assume it won't break any existing flatpak users work? Back from two weeks sailing so time is available for a week or two. I am taking off again in July. What a time of year for a new beta!

**Comment by leamas** [comment]
Done. I have been busy with https://github.com/OpenCPN/OpenCPN/pull/2303, that was a some work. Also, my boat, as usual, needs some care even if it's launched. I have no definite plans, but will definitaly move to our boat in a matter of days, not weeks.
