### ISSUE TITLE
Raspbian tarballs always sent to CLOUDSMITH opencpn/shipdriver-alpha

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#180]
Unable to create a stable (release) version of the ShipDriver raspbian tarballs.

@pkg_repo always ends up as "opencpn/shipdriver-alpha"

**Comment by Rasbats** [comment]
Log for latest 2.6.15 tagged release build for the Raspbians is attached:
[logs_Rasbats_shipdriver_pi_94_3_2.log](https://github.com/Rasbats/shipdriver_pi/files/6682570/logs_Rasbats_shipdriver_pi_94_3_2.log)

**Comment by leamas** [comment]
I'll see when I have some time...

**Comment by Rasbats** [comment]
Not sure if it helps but ...
Have been running the raspbian build locally using WSL 2 and drone exec, with a docker image. Locally it make the $[pkg_repo} correctly, recognising the tag, Why does drone.io CI with build 'execute_process' in 'Metadata.cmake' not produce the correct _git_tag?

**Comment by Rasbats** [comment]
Do we need to use ${DRONE_TAG} for raspbian builds?

**Comment by leamas** [comment]
Here is two patches. One is a point fix, just to make it build  handling the check for error_code put into Metadata.cmake which is broken.

```
From 27b6322d59c2e33da93f883894c7999d46abe961 Mon Sep 17 00:00:00 2001
From: Alec Leamas <leamas.alec@gmail.com>
Date: Fri, 2 Jul 2021 18:58:42 +0200
Subject: [PATCH 1/2] Fix error check

---
 cmake/Metadata.cmake | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/cmake/Metadata.cmake b/cmake/Metadata.cmake
index eb725f6..dfaae82 100644
--- a/cmake/Metadata.cmake
+++ b/cmake/Metadata.cmake
@@ -30,8 +30,8 @@ execute_process(
   OUTPUT_STRIP_TRAILING_WHITESPACE
 )
 
-if(error_code | !error_code)
-	message(WARNING "Error code is: ${error_code}")
+if (NOT "${error_code}" EQUAL 0)
+  message(WARNING "Error code is: ${error_code}")
 endif()
 
 if (NOT "$ENV{CIRCLE_BUILD_NUM}" STREQUAL "")
-- 
2.31.1

```

The next should print the selected upload directory in a legible way (below). Could you please try to apply it, create a new build and link to the log?

```
From 1c5709a190c8840b28cc7d5e53b8475adf5e5e10 Mon Sep 17 00:00:00 2001
From: Alec Leamas <leamas.alec@gmail.com>
Date: Fri, 2 Jul 2021 18:59:44 +0200
Subject: [PATCH 2/2] Make selected upload directory visible (#80)

---
 cmake/Metadata.cmake | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/cmake/Metadata.cmake b/cmake/Metadata.cmake
index dfaae82..dcfbbf9 100644
--- a/cmake/Metadata.cmake
+++ b/cmake/Metadata.cmake
@@ -76,7 +76,9 @@ else ()
     endif ()
   endif()
 endif ()
-message(STATUS "Selected upload repository: ${pkg_repo}")
+
+string(REGEX REPLACE "([a-zA-Z0-9])" "\\1 " pkg_repo_display  ${pkg_repo})
+message(STATUS "Selected upload repository: ${pkg_repo_display}")
 
 # pkg_semver: Complete version including pre-release tag and build info
 set(_pre_rel ${PKG_PRERELEASE})
-- 
2.31.1

```

**Comment by Rasbats** [comment]
Thanks Alec ...
Logs are here:
The build was v2.4.7.0-beta.
[https://cloud.drone.io/Rasbats/shipdriver_pi/190/2/2](https://cloud.drone.io/Rasbats/shipdriver_pi/190/2/2)
line 1811 for stretch and 2107 for buster.

**Comment by leamas** [comment]
It you add this patch (debug only!) it will show what's actually is going on in Metadata.make. Seems that we  need this info...
```
index 5a5162f..f66c9d7 100644
--- a/cmake/Targets.cmake
+++ b/cmake/Targets.cmake
@@ -75,6 +75,7 @@ function (tarball_target)
     TARGET tarball-conf
     COMMAND cmake -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/app/files
             -DBUILD_TYPE:STRING=tarball ${CMAKE_BINARY_DIR}
+            --trace-source=Metadata.cmake --trace-expand
   )
 
   add_custom_target(tarball-build)


```

**Comment by Rasbats** [comment]
Think I have a solution:
```
execute_process(
  COMMAND git log -1 --format=%s
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE _git_tag
  RESULT_VARIABLE error_code
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
```
The %s extracts just the version, without the hash. 
Now off to make a release version.

**Comment by Rasbats** [comment]
Tested and working on the RPi4. Should I remove any of the patch stuff before using the template elsewhere?

**Comment by leamas** [comment]
definitely remove tthe last patch. The first two should  be fine, although the display of the upload repo needs some cleanup. Will make  PR, please leave this bug open until done

**Comment by leamas** [comment]
hm... 82f2067e seems badly broken. On a local build. I get 

```
 git log -1 --format=%s
Clean up display upload repo (#180).
```
This means a severely corrupted name for the tarball etc. We need to revert this and find  a working solution.

**Comment by Rasbats** [comment]
I think  it would be better to patch the fix - `git log -1 --format=%s`
Have tried so many things in this area one revert is not going to fix it.

**Comment by leamas** [comment]
since the fix breaks local, untagged builds ee cannot use it as-is.

Can you link to a build which has the --trace-source applied?

**Comment by Rasbats** [comment]
v2.7.11.0-beta has the --trace-source applied. In this version I use `git tag --contains HEAD`. This causes the lack of a beta tarball in Cloudsmith. `git tag --contains HEAD` from the command line produces a version number but not when used in execute_process by drone.io.
Sorry about all the commits but this has been a real pain.
Cannot understand why, if `git log -1 --format=%h` works for _git_version then `git log -1 --format=%s` cannot be used for _git_tag.
The build log for v2..11.0-beta with trace is here:
[https://cloud.drone.io/Rasbats/shipdriver_pi/210](https://cloud.drone.io/Rasbats/shipdriver_pi/210)

**Comment by Rasbats** [comment]
v2.7.12-beta has the --trace-source applied and also the fix is being used in Metadata.cmake (`git log -1 --format=%s`).
Build log here:
[https://cloud.drone.io/Rasbats/shipdriver_pi/212](https://cloud.drone.io/Rasbats/shipdriver_pi/212)

**Comment by Rasbats** [comment]
`if(_lc_git_tag MATCHES beta )`
Are quotes needed around beta?

**Comment by leamas** [comment]
no

**Comment by leamas** [comment]
I made a new PR #183. This contains working printout of the upload repo used in upload.sh. Together with the new output from Metadata.cmake things should become somewhat more clear.  It also resets the way to get the tag name. I'm pretty sure this has been correct from the beginning, here is something else going on

Please apply the patch  and make a build. If the drone builds still fails, please re-add the --trace-source patch, build again and link to the build here.

**Comment by leamas** [comment]
Found it. The problem is that the drone builder does not fetch  the tags to the builder. Since the tags does not exist,  cmake obviously cannot find them. The following patch fixes it:

```
diff --git a/ci/drone-build-raspbian.sh b/ci/drone-build-raspbian.sh
index 09e81b6..bc857de 100755
--- a/ci/drone-build-raspbian.sh
+++ b/ci/drone-build-raspbian.sh
@@ -15,6 +15,8 @@ sudo apt-get install -q devscripts equivs
 sudo mk-build-deps -ir build-deps/control-raspbian
 sudo apt-get -q --allow-unauthenticated install -f
 
+git fetch --all --tags
+
 # Temporary fix until 3.19 is available as a pypi package
 # 3.19 is needed: https://gitlab.kitware.com/cmake/cmake/-/issues/20568
 url='https://dl.cloudsmith.io/public/alec-leamas/opencpn-plugins-stable/deb/debian'
```

After verifying that this patch works (it does for me), please review the code and remove various debug junk added while hunting this.

**Comment by Rasbats** [comment]
Looks good. Thanks for your patience with this. I will clean up tomorrow.

**Comment by Rasbats** [comment]
Cleaned out the stables. Removed a lot of Cloudsmith artefacts so I could get a better idea of exactly what builds are being made.
Had seen another issue before and it is still causing a problem with Drone CI.
Drone CI makes two builds, master and tag. It tries to push artefacts from both builds to Cloudsmith. There is an error message:

`Detail: A package with filename 'ShipDriver-2.8-raspbian-10.xml' and name 'ShipDriver-2.8-raspbian-10-metadata' already exists in the '******: ShipDriver-2.8-raspbian-10-metadata@2.8.1.0-+2107071947.v2.8.1.0-beta (vVwVbdfRt3Zm)' package. Republishing was not enabled for your package. `

One part of the build fails, sometimes buster, sometimes stretch.
Build logs here:

[https://cloud.drone.io/Rasbats/shipdriver_pi/221/2/2](https://cloud.drone.io/Rasbats/shipdriver_pi/221/2/2)

This results in the following in Cloudsmith:

![raspbian_bug](https://user-images.githubusercontent.com/2537240/124873748-c6fa3a00-dfbe-11eb-91ed-af928db772fc.jpg)
![raspbian_bug2](https://user-images.githubusercontent.com/2537240/124873754-c82b6700-dfbe-11eb-829e-640c854d277f.jpg)

Appveyor makes the two builds but does not produce artefacts from both.

**Comment by Rasbats** [comment]
Is a trigger needed?

[https://docs.drone.io/pipeline/triggers/](https://docs.drone.io/pipeline/triggers/)

**Comment by leamas** [comment]
looks like the right idea. Triggers seems to be more or less the same as filters, but with reversed logic.

**Comment by Rasbats** [comment]
Have set trigger for tag and pull-request events. This prevents the double beta builds. It will work for beta, prod and PR events but not for experimental, alpha, builds. PR events will create two conflicting artefacts. 
Some of your scripting logic is needed here I think.

**Comment by leamas** [comment]
Could this be closed?

**Comment by Rasbats** [comment]
Sailing! Needs further testing. Still possible duplicates.

**Comment by Rasbats** [comment]
Removed the trigger for Drone some time ago and there are now duplicates  for the Raspbian beta builds. I will reinstate the trigger.

**Comment by leamas** [comment]
Which builds, exactly, produces duplicates? 

The proper fix is to avoid the duplicates completely...

**Comment by Rasbats** [comment]
Any commits for Raspbian 9.13 and 10 (drone.io) that are tagged have duplicate builds unless I set the trigger in drone.yml to allow tagged builds only. If the trigger is not set for tag the master and tag builds will both upload artefacts to Cloudmith, producing duplicates. Appveyor builds both master and tag but only uploads the tagged build artefacts.
![duplicate raspbians](https://user-images.githubusercontent.com/2537240/126911840-daae77c2-d56a-4263-b86c-cf99a503ec0d.jpg)

[https://cloud.drone.io/Rasbats/shipdriver_pi](https://cloud.drone.io/Rasbats/shipdriver_pi)

**Comment by leamas** [comment]
hm... The core problem here is that I assumed that the different builders for buster and stretch would have different build numbers i. e., different values of DRONE_BUILD_NUMBER. However, it seems like the builders share a common number reflecting the parent job.

I will look into  this...

**Comment by leamas** [comment]
A nights sleep, and things becomes IMHO more clear.

First: The basic issue here that tarballs always goes  the alpha repo is actually solved. We should thus close this issue.

OTOH, we have a new issue about conflicting filenames. This is actually just the tip of the naming policy iceberg. I'll file a new issue about this, we need a fresh start.

**Comment by Rasbats** [comment]
Agree. I will close the alpha repo issue.

**Comment by Rasbats** [comment]
One of the beta Raspbians is still duplicated:
[https://cloudsmith.io/~opencpn/repos/shipdriver-beta/packages/?q=*raspbian*](https://cloudsmith.io/~opencpn/repos/shipdriver-beta/packages/?q=*raspbian*)

**Comment by Rasbats** [comment]
All hell has broken out on CircleCI with access to archives. Multiple build failures this morning.
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/523/workflows/376a5222-b32a-4d1b-a7ac-318664ebee0d/jobs/3727](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/523/workflows/376a5222-b32a-4d1b-a7ac-318664ebee0d/jobs/3727)

**Comment by Rasbats** [comment]
Re-run from failed fixed the CircleCI issue.
