### ISSUE TITLE
Broken metadata in plugins

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#181]
See attached
[metadata-errors.txt](https://github.com/Rasbats/shipdriver_pi/files/6740806/metadata-errors.txt)

**Comment by Rasbats** [comment]
[https://github.com/OpenCPN/plugins/tree/master/metadata](https://github.com/OpenCPN/plugins/tree/master/metadata)

No sign of these urls. Have you fetched the upstream of OpenCPN/plugins to make sure your fork is up-to-date?

**Comment by rgleason** [comment]
It is about 2 days old and done using check.bat and the validator.script.

**Comment by rgleason** [comment]
I see, perhaps it is fixed.  Sorry.
