### ISSUE TITLE
drones service: questions

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#186]
I assume drone builds some of the environments.  Is it required that a builder have an account in order to build and deploy?
It looks like the branch to use is Master.
It appears to build all the same OS as OpenCPN now, 3 flatpak, macos, windows, ubuntu, etc,  except the two Raspian builds are missing.  When will those be made available?

**Comment by Rasbats** [comment]
[https://github.com/Rasbats/managed_plugins/wiki/Drone](https://github.com/Rasbats/managed_plugins/wiki/Drone)

**Comment by rgleason** [comment]
Thanks, what about the 2 missing raspian builds?  How do we get those?

**Comment by rgleason** [comment]
Where is Drone?  there is no link and there are lots of "drone"

**Comment by rgleason** [comment]
Is it Drone Harnass?
https://www.drone.io/

**Comment by rgleason** [comment]
I think that is the right one, so I have logged in and added vdr_pi
Then added my secret for cloudsmith_api_key
What is "GIT_KEY_PASSWORD"  for ?
What is  "GIT_REPO"  for ? 

I have a Personal Access Token for Vdr_pi   (Vdr_pi > Settings > Dev Settings > Personal Access Token  
do I need that?

Also I have a  Rick_git_https access token but that is for me to log in to my accounts.

It seems to be building with the cloudsmith key only.
https://cloud.drone.io/rgleason/vdr_pi/2

**Comment by rgleason** [comment]
I guess I used my github account to allow clone.drone.io  access to 
Access public repositories
Read org and team membership, read org projects
Access user email addresses (read-only)
Using an OpenCPN organization access.

Now I have found 4 recent raspbian builds for  1.2 and 1.3 !   So that has enabled those builds!

Thanks.

**Comment by Rasbats** [comment]
@rgleason : Is VDR now building ok? Can this be closed?

**Comment by rgleason** [comment]
Yes
