### ISSUE TITLE
build-flatpak-x86-1808 failed

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#187]
Two weeks ago there was no problem with this build. Does "circleci-build-flatpak.sh" need amending?

[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/511/workflows/c808f6b4-7c6f-437b-a682-091e4b4e1d98/jobs/3619](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/511/workflows/c808f6b4-7c6f-437b-a682-091e4b4e1d98/jobs/3619)

**Comment by leamas** [comment]
still sailing,  on  phone. Looks like an intermittent  error, just rebuilding might work. in haste...

**Comment by Rasbats** [comment]
Tried rebuilding, but this did not cure the problem. Other things going on here as well. It is the sailing season in Europe!

**Comment by Rasbats** [comment]
Thanks for the fix. Closing.
