### ISSUE TITLE
ubuntu plugins does not load.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#19]
ubuntu plugins are deemed as incompatible. This basically because of https://github.com/OpenCPN/OpenCPN/issues/2003. An  -x86_64  suffix needs to be added to the `<target-os>` field.

I'm on it, stay tuned.

**Comment by Rasbats** [comment]
Running MacOSX Catalina. Unfortunately build with all commits does not import. Lacking the metadata.

**Comment by leamas** [comment]
hm.. Looking at the latest build at your repo, built from 89f601f . When I expand the tarball I can see the metadata.xml file where it is supposed to be. 

Just to make it the same for both of us: could you try the tarball in your own repo at https://cloudsmith.io/~mike-rossiter/repos/shipdriver-beta/packages ?

Exactly which tarball are you using (git commit?)

Does opencpn tell you it doesn't find the metadata?

**Comment by leamas** [comment]
hm... I have breathed some life into my Mojave VM, also having troubles.  The file plugin I download using safari is a .tar.gz file, a compressed tar archive. But the file on the disk is  a plain .tar file, it has somehow been decompressed, probably by safari. This will not work, opencpn expects a tar.gz file.

I can walk around this using curl like `curl https://dl.cloudsmith.io/public/mike-rossiter/shipdriver-beta/raw/names/ShipDriver-darwin-10.13.6-tarball/versions/2.4+72.89f601f/ShipDriver-2.4+72.89f601f_darwin-10.13.6-x86_64.tar.gz --output shipdriver.tar.gz ` which downloads a proper .tar.gz file. 

However, when I try to import it using opencpn I can see the file in the file selection widget, but it's kind of grey and I cannot select it.

To me, it looks like a bug in the Import File button on Mac. Have you ever had it working? If we conclude this, I can make a temporary plugin catalog which can be used for testing to get around the problem. I basicaklly never use mac, so I don't really know what to think.

Thoughts?

**Comment by leamas** [comment]
Made a try with a tarball from the plugin catalog, it's the same problem. So, this is not about the tarball, it's about Import Plugin on MacOS.

Is it the same for you on Catalina?

**Comment by leamas** [comment]
The MacOS plugins seems OK. I have been able to install successfully it using a modified ocpn-plugins.xml. To reproduce: exit opencpn, download attached file and copy it to ~/Library/Preferences//opencpn/ocpn-plugins.xml. 

Then restart opencpn, look in  the Plugins tab and  ShipDriver is listed and can be installed.

The ocpn-plugins.xml file contains a link to the clloudsmith tarball. You  can inspect and manually update it if need be. Note that pushing  the "Update Catalog" button will overwrite ocpn-plugins.xml and  ShipDriver will disappear.

github forces me to compress the catalog file; please uncompress before use.

[ocpn-plugins.xml.gz](https://github.com/Rasbats/shipdriver_pi/files/5135483/ocpn-plugins.xml.gz)


I'm still interested in if you can select plugins for import on Catalina (above), need input before filing a bug.

**Comment by Rasbats** [comment]
Went to have a look at ShipDriver on bionic. Fighting jigsaw icons at the moment but that is not unusual. Wish there was a simple uninstaller for the old plugins. Anyway, now going to Mac to test your xml.

**Comment by leamas** [comment]
> Fighting jigsaw icons at the moment but that is not unusual

Probably because the MANAGED_PLUGIN:ON isn't set in the build script, right? Anything not using GetPluginDatadir() will fail to find the icons, for sure.

Which leads to the question why this option exist. The plugin is built against the 1.16 (opencpn 5.0.0) API, and GetPluginDataDir existed already there. Or, if you want the option for some other reason, couldn't it be OFF by default?

**Comment by leamas** [comment]
> Wish there was a simple uninstaller for the old plugins.

On bionic, isn't those just debian packages? You can then handle them  first finding out the name of the package using something like  ` $ dpkg -l | grep -i shipdriver`.  And then remove it using `sudo dpkg -r <package-name>`

**Comment by Rasbats** [comment]
Ok... using your ocpn-plugins.xml the plugin installed fine with v2.4.72. Still the jigsaw icons but I will play a bit with the build script.

**Comment by leamas** [comment]
See above on the icons, While on the Mac, can you confirm that it isn't possible to select files when pushing Import Files button?

**Comment by Rasbats** [comment]
If you are looking at  'Import plugin' I need to use 'Quick Look' (ctrl+click). After this the tarball becomes available to load.

**Comment by leamas** [comment]
> [...]I need to use 'Quick Look' (ctrl+click). 

THANKS!  

Seems to work just fine. But the idea how user-friendly the mac is took a blow.... :)

**Comment by Rasbats** [comment]
With MANAGED_PLUGIN:ON in the script the icon shows in the toolbar for ShipDriver. Why didn't Jon include it in his frontend2? I will need to revisit all my plugins.

**Comment by Rasbats** [comment]
Naming of the tarball on the Mac. The latest is 'ShipDriver-2.4+77.v2.4.8_darwin-10.13.6-x86_64.tar'. I think the patch version needs to go into the build name before the +. Can you help with this? It affects the order of downloads in the list.  

I prefer Jon's naming of the tarballs where I can easily see version major/minor/patch in the Cloudsmith list.

**Comment by leamas** [comment]
Hm... the MANAGED_PLUGIN:ON looks a little weird to me, will submit a PR. TBH, if it works it's IMHO sheer luck...

Jon's problem is that he is trying to make a framework which works for all plugins. But as far as I know,  the MANAGED_PLUGIN option is specific for shipdriver... Here, we are just focusing on shipdriver which makes it so much simpler.

**Comment by Rasbats** [comment]
My mistake... I should have removed all the stuff about MANAGED_PLUGIN. It was used before OpenCPN 5.2 to allow testing with the beta. I will take out all the code that is now redundant. I will let you know when this has been done to let you resync.

**Comment by leamas** [comment]
> I think the patch version needs to go into the build name before the +.

The same thought have crossed my mind. Will look into it.

**Comment by leamas** [comment]
The ubuntu plugins does load. Closing
