### ISSUE TITLE
Build artifacts file name issues.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#193]
We have issues with the filenames for generated metadata and tarball files.

  - As of #180, multiple drone.io builds creates errors when uploading the same file twice.
  - The tagged build has filenames like ` ShipDriver-2.7.1.0-+610.v2.7.1.0_msvc-10.0.14393-win32.tar.gz`. This is not sane. The tagged build are supposed to have a "clean" name, something like ` ShipDriver-v2.7.1.0_msvc-10.0.14393-win32.tar.gz`. Tags are by definition unique, so a simple filename containing the tag and target platform should be enough.
  - The shipdriver repo contains too many tags. I presume this is about debugging #180, but needs to be taken care of anyway..

EDIT: Today's filename is also plain wrong according to the  specs att https://semver.org. The tag is definitely not build info as implied by the filename

**Comment by leamas** [comment]
There are multiple options to fix the "collisions" issue. So far we have been trying to use unique filenames, but this has the drawback of creating obscure names.

Another option  is to just allow overwrite when uploading,  latest build wins so to speak. We will then miss some traceability, we  will not not know where this build was created.  OTOH, we could add some comment to the metadata with this info....

**Comment by Rasbats** [comment]
Latest beta has stereo Raspbian tarballs/metadata files. Identical names for both tarballs/metadata files. As expected. Off to the garden to sort out tree growth.

**Comment by leamas** [comment]
> Latest beta has stereo Raspbian tarballs/metadata files. Identical names for both tarballs/metadata files

Indeed, but is it a problem? After all,  they are built using the same sources, right?

**Comment by Rasbats** [comment]
>Indeed, but is it a problem? 

Only one set of metadata xml files has been pushed to the auto directory of the plugins repo. So probably not an issue. Just strange seeing two duplicate sets of files in Cloudsmith.

**Comment by leamas** [comment]
OTOH,  we now build from all commits. It is sort of sane as well... That is not to say I'm sure what is the proper way to handle this. 

The important issues are really (?):
  - That an uploaded tarball which is published, in beta or elsewhere, does not change.
  - That the tagged build is left as-is after being published.

Do you think these two assumptions hold?

**Comment by Rasbats** [comment]
>OTOH, we now build from all commits.
Yes... for Raspbian and MSVC but not the others. 

>published, in beta or elsewhere, does not change.
Why should there be any changes? Why should the tagged build change?

I need to take the beta build of ShipDriver all the way to publication for use with PIM as a further test.

**Comment by leamas** [comment]
Please hold... I have one more thing in the oven...

**Comment by leamas** [comment]
with #195 I think we are pretty close. If possible, please try the complete release-publish cycle.

**Comment by Rasbats** [comment]
>Please hold... I have one more thing in the oven...

Already sent. Never mind. That one went all the way through the workflow successfully. 
I have repeated the exercise with #195. Just waiting for Dave to accept the PR.

Once accepted I need to test the product on as many OS as possible.

**Comment by Rasbats** [comment]
Beta PR accepted. Now some tests.

**Comment by Rasbats** [comment]
RPi Buster: Needed to install libjsoncpp-dev to get Beta ShipDriver running. The logfile pointed me in the right direction.

RPi Ubuntu Groovy (64bit). ShipDriver from the Beta catalog. Initially forgot I was using opencpn-flatpak. Got confused with all the OS available from Settings/System. It was possible to install the Ubuntu GTK3-x86-64 version but the jigsaw icon appeared and the plugin would not run. Missing the .so. With the AMD64 flatpak version of the plugin all went well.

Will the beta catalog button be available in the next release, without having to go through Settings?

MacOS: No problem.

Win: No problem.

Android: The last version (2.7) is working fine. How do I import/install a Beta version?

TBC

**Comment by leamas** [comment]
We need to look at those issues. Sailing now, will find time in the weekend.

BTW: So many thanks for your work!

**Comment by leamas** [comment]
> Will the beta catalog button be available in the next release, without having to go through Settings?

Ultimately, it's Dave's decision. Seemingly, he doesn't  want to make the beta available to "ordinary" users.

> RPi Ubuntu Groovy (64bit).  

The correct solution is to drop this build. We are currently focusing on flatpak for the fragmented aarch64/arm64 world.

> Android: The last version (2.7) is working fine. How do I import/install a Beta version?

No idea...

> RPi Buster: Needed to install libjsoncpp-dev t

Can you link to a build log?

**Comment by leamas** [comment]
hm...

> RPi Ubuntu Groovy (64bit).

Are we actually building this? where, then? "confusedf"

**Comment by leamas** [comment]
> Android: The last version (2.7) is working fine. How do I import/install a Beta version?

At a second thought: can and must be done using Import. That is, download the plugin, transfer it to the Android device (USB stick?) and use the Import button

**Comment by Rasbats** [comment]
>At a second thought: can and must be done using Import. That is, download the plugin, transfer it to the Android device (USB stick?) and use the Import button

Not available on my Android OpenCPN

>RPi Ubuntu Groovy (64bit).

Flatpak

>Buster. Can you link to a build log?

[https://cloud.drone.io/Rasbats/shipdriver_pi/262/2/2](https://cloud.drone.io/Rasbats/shipdriver_pi/262/2/2)

Can it be added to the dependencies?

**Comment by leamas** [comment]
>>  RPi Ubuntu Groovy (64bit).

> Flatpak

That is , we are building flatpak-aarch64 on i Ubuntu Groovy (64bit) ?!

> Can it be added to the dependencies?

Won't help, we need it in the runtime.

libjsoncpp is a dependency of wxjson. Does Shipdriver actually use this? Removing the wxJSON library would solve the problem as long as it builds.

Still, wxJSON is like part of the plugin infrastructure, and many plugin actually uses it. Perhaps we could persuade Dave to include it in OpenCPN's dependencies.

The alternatie would be to let wxJSON bundle libjsoncpp. We have done similar things earlier, so it's doable. Takes some time, though.

Thoughts?

**Comment by Rasbats** [comment]
> Drop unused libs/wxJSON (Rasbats#193). 

Prefer to leave as is. If other plugins migrate to the ShipDriver workflow it could be needed. Only a small number of people are using ShipDriver on the RPi. Will deal with the problem of libjsoncpp as it comes up. It might be useful for Dave to make it a dependency of OpenCPN in view of RPi use.

**Comment by leamas** [comment]
>  Android: The last version (2.7) is working fine. How do I import/install a Beta version?
 >>At a second thought: can and must be done using Import. That is, download the plugin, transfer it to the Android device (USB stick?) and use the Import button

>Not available on my Android OpenCPN

@bdbcat: IIRC, you have described the procedure for testing android beta plugins somewhere? Or?

**Comment by leamas** [comment]
> RPi Buster: Needed to install libjsoncpp-dev to get Beta ShipDriver running. The logfile pointed me in the right direction.

This should be fixed by #198

**Comment by leamas** [comment]
> RPi Ubuntu Groovy (64bit). ShipDriver from the Beta catalog. Initially forgot I was using opencpn-flatpak. Got confused with all the OS available from Settings/System. It was possible to install the Ubuntu GTK3-x86-64 version but the jigsaw icon appeared and the plugin would not run. Missing the .so. With the AMD64 flatpak version of the plugin all went well.


So this is the flatpak-aarch64 plugin generated on Ubunti 21.04, right?  Which runs OK on opencpn-flatpak (?)

Is here actually an issue, or was it just some testing mess? "scratches remain strains of hair on my head"

**Comment by leamas** [comment]
> RPi Ubuntu Groovy (64bit). ShipDriver from the Beta catalog. Initially forgot I was using opencpn-flatpak. Got confused with all the OS available from Settings/System. It was possible to install the Ubuntu GTK3-x86-64 version but the jigsaw icon appeared and the plugin would not run. Missing the .so. With the AMD64 flatpak version of the plugin all went well.

So this is about flatpak-aarch64 generated on Ubuntu 21.04, right?

**Comment by Rasbats** [comment]
>So this is the flatpak-aarch64 plugin generated on Ubunti 21.04, right? Which runs OK on opencpn-flatpak (?)

The only issue was that the Ubuntu GTK3-x86-64 version did not raise an incompatible version and stop the installation.

**Comment by leamas** [comment]
I suppose we could leave this for now. There is a possibility that this happened since you for good reasons had been using the"advanced"  plugins Settings dialog. If it's indeed a problem, it's certainly on the main OpenCPN side rather than the plugin.

That leaves us with the beta testing question, where we need input from @bdbcat.

**Comment by bdbcat** [comment]
To test a Beta plugin on Android:
1.  On Android, edit config file manually: 
[Plugins]
CatalogExpert=1

2.  On your PC, install "adb".  Many tutorials available on google.
3.  On the PC, download the plugin Beta tarball of interest. For example, ends up in ~/Downloads/foo_pi.so
4. Connect the Android device to the PC by USB cable.
5. Push the plugin to the device, using adb:
  $ adb push ~/Downloads/foo_pi.so /storage/emulated/0
6.  Start OCPN on the Android device.
7.   Import the plugin, selecting the foo_pi.so from the /storage/emulated/0 directory.

Test away!
Dave

**Comment by bdbcat** [comment]
Additional:
You may, of course, directly download the foo_pi.tar.gz tarball directly to the device, if it has been published to Cloudsmith, so skipping the "adb" steps.
I do not plan to enable CatalogExpert by default in Android releases.  With some (very appreciated) exceptions, Android users are not much interested in testing our app.  They (reasonably) expect published apps and plugins to be ready for daily use.

**Comment by Rasbats** [comment]
Thanks Dave ... this will really help the testing.

**Comment by leamas** [comment]
This issue has morphed into discussing all sorts of stuff. However, it seems like the original issue is fixed.

Time to close?

**Comment by Rasbats** [comment]
Agree.
