### ISSUE TITLE
No gtk3 builds.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#20]
The linux world is dropping the gtk2 support, moving to gtk3. The latest example is ubuntu, which from focal (20.04) does not support gtk2 any longer.' Same goes for Debian Bullseye/11.

The build chain needs to updated with a gtk3 option.

**Comment by Rasbats** [comment]
Can we update with the gtk3 option to resolve this?

**Comment by leamas** [comment]
I have submitted #24  with the gtk3 builds. It resolves this issue.

**Comment by Rasbats** [comment]
Thanks. Working on another plugin with bugs. About to merge #24.

**Comment by Rasbats** [comment]
This may be of interest. Beyond my skill set. 
[https://github.com/Rasbats/DR_pi/issues/9](url)

**Comment by leamas** [comment]
NOw, the gtk 3 builds are actually live & kicking. Closing.
