### ISSUE TITLE
WIP: Automated update script

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#201]
Moved here to make comment when testing/updating.

**Comment by Rasbats** [comment]
This is still just the first shot. That said, it's an automated script which (hopefully) can be run in any plugin using shipdriver templates.

@leamas The basic strategy is to merge changes for the shipdriver repo rather than just overwriting existing files. As a consequence, the logic is basically to first merge everything, and then reset those changes which belongs to the local plugin.

Testing: copy the script to a plugin repo. This is as of now not really specified, but it is certainly possible. In the repo, make sure that the index is clean and run it as ./update-templates from bash.

Open issues:

    bootstrapping: How to use latest version in a plugin which does not have this script in it's repo.
    Windows usage (just some docs would make things so much easier).
    Some kind of 'exception-list' which list files which should not be updated.
    EDIT: Make it possible to update from a given treeish (commit or tag) in shipdriver repo.

+ a probably large number of bugs...

That said, it should be possible to merge already now, other users will not use for now, I guess.

**Comment by leamas** [comment]
I have problems which merge algorithm to use. 
  - Currently, script uses `git merge -X theirs`. This basically means "use the shipdriver stuff", unconditionally. It simple, but the conflicts are not visible in any way. This means that if plugins have fixes we want to upstream we will miss them.
  - I have experimented dropping  the `-X theirs`. This leaves all changes as conflicts in the files. The normal workflow is to review the changes, and use the shipdriver stuff using `git checkout shipdriver/master <file>`. Of course, one can also merge things manually if there is a need to keep the local changes.

Will do some more experiments. And reading up on git merge strategies, this is deep stuff.

**Comment by leamas** [comment]
I have updated script, and notably UPDATE-TEMPLATES.md. I have also run some initial tests which seems to work fine on aisRX.

Script is designed to give user a lot of control of how the update is done, with  possibility to make diffs etc. This comes with a usability cost, but it might be worth it. To just blindly copy files is probably not the best strategy even if it simpler to use (?)

To proceed this issue we need some independent testing. Please read UPDATE_TEMPLATES.md before doing that :)

**Comment by Rasbats** [comment]
Tested bootstrapping on Windows with both Git Bash and Powershell:
```
Mike@vostro-64 MINGW64 ~/Documents/GitHub/JavaScript_pi (master)
$ set repo=https://raw.githubusercontent.com/Rasbats/shipdriver_pi/master

Mike@vostro-64 MINGW64 ~/Documents/GitHub/JavaScript_pi (master)
$ curl %repo%/update-templates --output update-templates
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: %repo%
```

**Comment by leamas** [comment]
Hm...  something is messed up here: %repo%  is CMD syntax, definitely not bash and probably not powershell. Have you tried running it in plain cmd.exe?

**Comment by leamas** [comment]
The other way around is that you use the Linux instructions using git bash...

**Comment by Rasbats** [comment]
>in plain cmd.exe?

That works. Continuing.

**Comment by leamas** [comment]
No news is good news. Or?

**Comment by Rasbats** [comment]
Paused while we have the issue with the MacOS build.
Log is here:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/556/workflows/b8e5b95d-03ab-43e9-84f4-bc4f015252f6/jobs/4017](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/556/workflows/b8e5b95d-03ab-43e9-84f4-bc4f015252f6/jobs/4017)

**Comment by Rasbats** [comment]
```
Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ set repo=https://raw.githubusercontent.com/Rasbats/shipdriver_pi/master

Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ curl %repo%/update-templates --output update-templates
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: %repo%
```
The problem is still here, using Windows. I can manually copy across and use _update-templates_. Continuing.

**Comment by Rasbats** [comment]
Did the manual copy update-templates.
```
Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ bash update-templates -t
+ source_treeish=shipdriver/master
++ git status --porcelain
+ clean='M  update-templates'
+ '[' -n 'M  update-templates' ']'
+ echo 'Please commit or stash pending changes. Aborting.'
Please commit or stash pending changes. Aborting.
+ exit 1

Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ git rebase master
error: cannot rebase: Your index contains uncommitted changes.
error: Please commit or stash them.

Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ git commit -m 'Empty'
[master 83d4518] Empty
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 update-templates

Mike@vostro-64 MINGW64 ~/Documents/GitHub/otcurrent_pi (master)
$ git push
```

Various moves later using Linux instructions with Git Bash and the script ran. Now looking at a build using the changes but CMakeLists.txt is going to need work, I think.

**Comment by Rasbats** [comment]
Trying some extra includes.

**Comment by Rasbats** [comment]
Moving to a new issue for this and closing #201.

**Comment by Rasbats** [comment]
This:
```
Mike@vostro-64 MINGW64 ~/Documents/GitHub/oplaydo2_pi (main)
$ bash update-templates -t
+ source_treeish=shipdriver/master
++ git status --porcelain
+ clean=
+ '[' -n '' ']'
+ '[' -z '' ']'
+ git ls-remote --exit-code shipdriver
+ git remote remove shipdriver
+ echo 'Removing existing shipdriver remote.'
Removing existing shipdriver remote.
+ git remote add shipdriver https://github.com/Rasbats/shipdriver_pi.git
+ git remote update shipdriver
Fetching shipdriver
From https://github.com/Rasbats/shipdriver_pi
 * [new branch]      2.1.b4.leamas -> shipdriver/2.1.b4.leamas
 * [new branch]      4.8.6         -> shipdriver/4.8.6
 * [new branch]      b4-drone.io   -> shipdriver/b4-drone.io
 * [new branch]      master        -> shipdriver/master
 * [new branch]      patch-1       -> shipdriver/patch-1
 * [new branch]      patches       -> shipdriver/patches
 * [new branch]      pr/13         -> shipdriver/pr/13
+ git fetch --tags shipdriver
++ git rev-parse --short shipdriver/master
+ hash=189eafe
+ new_branch=update.189eafe
+ git rev-parse update.189eafe
+ git branch -D update.189eafe
Deleted branch update.189eafe (was 189eafe).
+ git branch update.189eafe shipdriver/master
Branch 'update.189eafe' set up to track remote branch 'master' from 'shipdriver'.
+ '[' -z '' ']'
+ git diff --quiet HEAD shipdriver/master -- update-templates
+ git checkout shipdriver/master update-templates
error: unable to create file update-templates: Permission denied
Updated 1 path from db0e36c
+ cat
update-templates script is updated to latest version. Please commit
changes and re-run script.
+ exit 0

Mike@vostro-64 MINGW64 ~/Documents/GitHub/oplaydo2_pi (main)
$ bash update-templates
bash: update-templates: No such file or directory

Mike@vostro-64 MINGW64 ~/Documents/GitHub/oplaydo2_pi (main)
```
Problem seems to be that the old _update-templates_ is present and it does not allow the new one to overwrite it. Perhaps because it is in use.
