### ISSUE TITLE
Bad urls in current catalog.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#204]
Current catalog contains some broken urls to shipdriver.

Check log file:  [urlcheck.log](https://github.com/Rasbats/shipdriver_pi/files/6938950/urlcheck.log)

**Comment by Rasbats** [comment]
The last PR for ShipDriver was for the beta catalog.

[https://github.com/OpenCPN/plugins/pull/417/commits/14570f29debaa07576beb1b43e7dc0d9fcd1a2e7](https://github.com/OpenCPN/plugins/pull/417/commits/14570f29debaa07576beb1b43e7dc0d9fcd1a2e7)

2.7 is the last production release. Both 2.7 and 2.8.5.1-beta work fine.

Where does OpenCPN/plugins store the beta xml metadata?

**Comment by leamas** [comment]
In the Beta branch

**Comment by Rasbats** [comment]
me = idiot

Then why do the checks produce errors?

**Comment by leamas** [comment]
We are all idiots :)

The check is done against the master branch, which is what users see right now.

**Comment by leamas** [comment]
I'm assuming this to be closed, you should have had nag mails from Dave otherwise.
