### ISSUE TITLE
Flatpak: need to check for outdated TLS certficates

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#210]
Main OpenCPN ran into problems due to outdated TLS certificafes: https://github.com/OpenCPN/OpenCPN/issues/2419.

We need to check that we are are not running into the same problems in the ci scripts.

**Comment by Rasbats** [comment]
Made a temporary fix in _circleci-build-flatpak.sh_ for arm64.
sudo apt install --reinstall ca-certificates
