### ISSUE TITLE
[tracker] drone.io: Cannot run armhf Debian 11 images.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#217]
Drone .io cannot handle modern armhf images like Bullseye.

Upstream bug: https://discourse.drone.io/t/drone-cloud-build-failures-with-recent-armhf-containers/8434

We need to work around for now, keeping this bug open until things are sorted out.

**Comment by leamas** [comment]
hm... the drone.io service has run into bitcoin miners piracy problems, and is for now [blocking new users](https://discourse.drone.io/t/user-registration-is-disabled/9931/37?page=2).

Together with  that it doesn't really support Debian 11/Bullseye it is perhaps better to just drop this service and move the Debian 10/Streth build to CircleCI

**Comment by Rasbats** [comment]
>move the Debian 10/Streth(sic) build to CircleCI

Ok but ...

>it doesn't really support Debian 11/Bullseye

You got this working so can this drone.io build be left in place for Debian 11 users installing any existing ShipDriver based plugins. Only new developers using ShipDriver templates will be affected.
