### ISSUE TITLE
finding wxwidgets building Logbookkonni locally

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#226]
Get this output error when I build locally with bld.bat

```
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
    wxWidgets_INCLUDE_DIRS base core net xml html adv stc aui)
```

And the Environment Variables have   	
	wxWidgets_LIBRARIES
So it should be picked up.

Any ideas what I am missing?

Using branch  update-sd   https://github.com/rgleason/LogbookKonni_pi/tree/update-sd

**Comment by rgleason** [comment]
You have made several incorrect assumptions.

bld.bat does not build legacy, it uses bash and builds tarballs.

When and if you take away the ability to build locally, I will revert Logbookkonni back to use testplugin.

**Comment by leamas** [comment]
BTW: Both the cmake/ and ci/ directories are fully generic, so when updating you can (i. e., should) just copy the new files from shipdriver to your plugin without much thought.

**Comment by rgleason** [comment]
Thanks
Windows virtualized my documents/ github directory to be under onedrive causing the wxwidgets error.  No notice or question asked!

**Comment by rgleason** [comment]
Ps. Running win_deps.bat.failed to download 7z, I need to update the template for logbook next, but i picked a newer choc 7z install and I think it worked.

**Comment by rgleason** [comment]
I pulled shipdriver master again and found logbook is identical for cmake, ci, and supporting files and dir.

When I run win_deps.bat    pip does not install.  Wxwidgets does install.


C:\github\logbookkonni_pi\buildwin>python --version   1>nul 2>&1  || choco install -y python

```
C:\github\logbookkonni_pi\buildwin>python --version
Python 3.6.3

C:\github\logbookkonni_pi\buildwin>python -m ensurepip
C:\Program Files (x86)\Poedit\python.exe: No module named ensurepip

C:\github\logbookkonni_pi\buildwin>python -m pip install --upgrade pip
C:\Program Files (x86)\Poedit\python.exe: No module named pip

C:\github\logbookkonni_pi\buildwin>python -m pip install -q setuptools wheel
C:\Program Files (x86)\Poedit\python.exe: No module named pip

C:\github\logbookkonni_pi\buildwin>python -m pip install -q cloudsmith-cli
C:\Program Files (x86)\Poedit\python.exe: No module named pip

C:\github\logbookkonni_pi\buildwin>python -m pip install -q cryptography
C:\Program Files (x86)\Poedit\python.exe: No module named pip

```

Any suggestions?

**Comment by rgleason** [comment]
Are you using a different branch?

**Comment by rgleason** [comment]
This was all working before on a different computer, but it is useful to go through this again.   Must it be python 3.6?    I've downloaded 3.10.0 and installed pip

Please see this win-deps.bat output

[win_deps-output.txt](https://github.com/Rasbats/shipdriver_pi/files/7377005/win_deps-output.txt)

I am not sure why I am not seeing anything in build.
