### ISSUE TITLE
Script to copy xml from Cloudsmith to local plugins/metadata

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#229]
Also I am trying to use the script ./downloads_xml_bash.sh logbookkonni 1.4.18.6 oprnvpn alpha
but that does not work. I also tried using logbook 1.4 and that does not work either.
How do I get logbook metadate copied to my local plugins metadata?

**Comment by leamas** [comment]
It should be the same, just follow the manual which even points out where you can find it in the GUI...

**Comment by rgleason** [comment]
Ok thanks.  I guess I can use that ssh key without a problem.
