### ISSUE TITLE
Macos build issue -logbookkonni_pi

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#232]
Just tried to push to master, trial run  https://github.com/rgleason/LogbookKonni_pi
3 Flatpak built OK
2 android failed.  https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/108/workflows/c25a5695-0f49-4679-8890-a4a9155f1e15/jobs/1207

```
CMake Error at cmake/AndroidLibs.cmake:100 (add_subdirectory):
  add_subdirectory given source "/home/circleci/project/libs/AndroidHeaders"
  which is not an existing directory.

```

This used to build for android, can this be fixed easily? otherwise I will cancel this build.

**Also more importantly MacOS is failing** 

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/108/workflows/c25a5695-0f49-4679-8890-a4a9155f1e15/jobs/1209

Any ideas?
Sorry about the trouble with the update.

**Comment by leamas** [comment]
> add_subdirectory given source "/home/circleci/project/libs/AndroidHeaders"  which is not an existing directory.

Directory exists at shipdriver upstream, you need to copy it

**Comment by leamas** [comment]
> Also more importantly MacOS is failing

Seems that some of the changes present in upstream cmake is not present in your repo, perhaps cmake/PluginPackage.cmake, dunno. The shipdriver macos build works fine, so the problem is in your repo.

**Comment by rgleason** [comment]
Most recent.  I always use the most recent.

**Comment by rgleason** [comment]
I just decided to make sure my repos is identical so
git push -f origin master:master   and now this is at 

```
To github.com:rgleason/shipdriver_pi.git
   6442aaf..ec12d72  master -> master

```
and my earlier credentials and Passcode still seem to work.

**Comment by rgleason** [comment]
So now I am stuck.  We don't find 
git checkout 44c6de1
in shipdriver.

**Comment by rgleason** [comment]
DO NOT USE BASH!
You much use CMD Prompt for VS 2017!!!

git remote update upstream
git branch -va 
* master                         ec12d72 new-credentials: Strip space on user url input.
git clean -fxd

```
c:\Github\shipdriver_pi>git clean -fxd
Removing build-deps/rgleason
Removing build-deps/rgleason.pub
```
git push -f origin master:master   (I know this is not good protocol but my repos is the end of the line)
Everything up to date

python ./ci/new-credentials
Enter ssh URL for ocpn-plugins.xml clone: git@github.com:rgleason/plugins.git
Then enter a PASScode twice.


```
c:\Github\shipdriver_pi>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   buildwin/win_deps.bat

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        build-deps/rgleason.enc
        build-deps/rgleason.pub

no changes added to commit (use "git add" and/or "git commit -a")

```

```
git add build-deps/
git add buildwin
git commit -am "add git deployment key"
git push origin master:master

```
Register the new public key as a deployment key with write permissions (Allow write access) on your github OpenCPN/plugins fork repo (in Settings just above and to the left of the CODE button | Deploy keys):

Add Deploy Key
Title:  Deploy-plugins-JUNO
Key: (began with sha-rsa  may characters and ended with  Frederick@Juno  (which I included)

The key was accepted.

Thankyou Alec for your help.  
Now what?  I execute a script to copy certain dir/files from shipdriver to logbookkonni.
