### ISSUE TITLE
SD Manual: Bad link  Joining the Opencpn Organization

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#261]
[Joining the OpenCPN Organization](https://opencpn-manuals.github.io/main/AlternativeWorkflow/Cloudsmith.html#_joining_the_cloudsmith_opencpn_organisation)

Has a bad link that fails. [ See  ](https://github.com/Rasbats/shipdriver_pi/issues/232#issuecomment-950836618)

 I think it is 

`After you login you will automatically find the invite within the organization invites section of your user settings: https://cloudsmith.io/user/settings/orgs/invites/`

**If you are not logged in!**

**Comment by rgleason** [comment]
No, actually it is a link in the SD documentation. That is the point.   See Joining the Opencpn Documentation above.

**Comment by leamas** [comment]
The Sd templates documentation lives in https://github.com/Rasbats/managed_plugins.
