### ISSUE TITLE
flatpak not accepting a github branch to build from

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#272]
Using circleci for building a branch "v0.5" in JavaScript_pi flatpak builds fail.
[https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi/73/workflows/f5b74a11-2061-4b9a-9671-21b50f4ccd4c/jobs/744](https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi/73/workflows/f5b74a11-2061-4b9a-9671-21b50f4ccd4c/jobs/744)

circleci did have some issues with finding this branch earlier but other OS are now building correctly (Android not needed).

Previously we built successfully with the "installer" branch.

Latest ShipDriver template files are in place.

**Comment by Rasbats** [comment]
Plugin code is here:
[https://github.com/Rasbats/JavaScript_pi](https://github.com/Rasbats/JavaScript_pi)

**Comment by leamas** [comment]
This is about the flatpak manifest vs the repo. If you look at the very end in the manifest there is:

```
 sources:
          - type: git
            url: ..
            branch: master
```

That is, it tries to clone the master branch from your current repo. However, when I look at the repo the defauilt branch is v0.5, and the outdated master branch is just not available in your circleci clone.'

I guess you should patch the manifest to use the branch you are using in your main repo. Or, perhaps fetch the master branch to your repo before building. But, the  master branch looks old (?)

**Comment by leamas** [comment]
@Rasbats : Did you sort this out?

**Comment by Rasbats** [comment]
Yes ... sorted for v0.5. Closing.
