### ISSUE TITLE
CircleCI builds not picking up the beta repos on Cloudsmith. 

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#281]
CircleCI builds of sd3.0.0-beta1 end up in shipdriver-alpha.

**Comment by Rasbats** [comment]
Also drone/raspbian the same.

**Comment by Rasbats** [comment]
Not sure how long this has been a problem. Last beta build was some 3 months ago.

**Comment by leamas** [comment]
It's the same code, in cmake/Metadata.  

Great that you file bugs like this. We are now in some kind of beta freeze, and the usual convention then is to not accept any changes which does not close a bug. Shall we  make a try to stick to this until 3.0 is out?

**Comment by leamas** [comment]
Can you share a build link, preferably circleci?

**Comment by Rasbats** [comment]
Ok ... found it is "-beta1" that causes confusion. Link follows.

**Comment by Rasbats** [comment]
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/616/workflows/66961789-19ca-42c3-b08e-524065a8945c](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/616/workflows/66961789-19ca-42c3-b08e-524065a8945c)

**Comment by leamas** [comment]
Thanks.

The problem seems to be that for some reason circleci does not fetch the tags, even if told so. Facts in case:

  - The cd3.0.0-beta1 is not available in the build.
  - `git fetch --tags origin` does *not* fetch it (this is weird)
  -  This does, but is really clumsy:
         $ git remote add upstream https://github.com/Rasbats/shipdriver_pi.git
         $ git fetch --tags upstream

**Comment by leamas** [comment]
Off for dinner. Back in a while.

**Comment by leamas** [comment]
New pieces. I think we both stumbled over the primary roadblock here: The tag must point to the commit being built. For now, I understand that this not has been the case.

Using my own clone (which I can anythin I want with...) I have basically re-defined the sd3.0.0-beta1 to point to my upstream/master i. e., 2a5c0b82f76.  With this setup, I got the logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1078/workflows/eb355fde-7a1a-4e5c-b067-786a0c0ad02e). It looks bad, all fails. But if you look into the cmake output in the beginning of the build you can see that they have all selected the beta repo. The exception is the raspbian-bullseye build which is green but uses the wrong  directory.

All in all: these things are hard to test. Now off to fetch my wife.

**Comment by Rasbats** [comment]
So long since I made a beta/prod I forgot about tagging with the same name as the commit.
Builds are now correct.
Closing this one.

**Comment by leamas** [comment]
... but you forgot to actually close ;)
