### ISSUE TITLE
ShipDriver_pi.fbp: Unused file?

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#284]
Seems that  this file is a wxFormBuilder definition, and as I understand this tool is not really used any more. Am I right? If so, can we just remove this file?

**Comment by Rasbats** [comment]
The tool is really useful for designing the dialogs. F8 in wxFormBuilder moves the gui.cpp and gui.h to the src folder of the plugin. The preferences dialog is also designed alongside the main plugin dialogs.

The file needs to stay.

**Comment by leamas** [comment]
OK, just want to check...
