### ISSUE TITLE
Plugin.cmake - CMakeLists.txt

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#288]
_CMakeLists.txt contains_:
```
add_subdirectory("libs/jsoncpp")
target_link_libraries(${PACKAGE_NAME} ocpn::jsoncpp)

```
Should this be included with the other libraries like TinyXML in Plugin.cmake?
It caused an error when migrating DR_pi FE2 to SD. Resolved by removing:
```
add_subdirectory("libs/jsoncpp")
target_link_libraries(${PACKAGE_NAME} ocpn::jsoncpp)

```
from CMakeLists.txt in DR_pi.

**Comment by leamas** [comment]
hm... If there is a shortlist of libraries which should be included everywhere jsoncpp migth be in that since it's about the communication with main OpenCPN.

> . Resolved by removing [...]

I cannot understand this in any other way than that the version of libs/jsoncpp was different that in other places. And this is indeed a problem. There is a possible route to handle this but it's a big change, perhaps too big in the beta cycle.  I'll file a new issue later,

**Comment by Rasbats** [comment]
I will reinstate the libs/jsoncpp and post the error I get.

**Comment by Rasbats** [comment]
```
EXEC : error : patch failed: libs/jsoncpp/src/lib_json/json_reader.cpp:753 [C:\Users\Mike\Documents\GitHub\DR_pi\build\tarball-conf.vcxproj]
EXEC : error : libs/jsoncpp/src/lib_json/json_reader.cpp: patch does not apply [C:\Users\Mike\Documents\GitHub\DR_pi\build\tarball-conf.vcxproj]
  -- Using bundled jsoncpp.
  -- Using bundled tinyxml
  -- Configuring done
```
No tarball could be made.

**Comment by leamas** [comment]
I know that one... it's my bad, a recent one. Just drop jsoncpp for now, I'll take a look later when there is time.

Please keep bug open...

**Comment by leamas** [comment]
Another solution might be to revert 93b985b

**Comment by leamas** [comment]
This is actually solved by #298, but this is just a sidenote in the overall issue. Should we conclude that #298 should be rejected, there are simple fixes available anyway.

**Comment by leamas** [comment]
I think we can close this now, right?

**Comment by rgleason** [comment]
Using libs as a submodule would keep pi dev paws off that code, then the necessary changes must be done in the PI code.

This is the right way to do it, but it will make more work for me if I migrate to SD with sean's plugins because his libs are not always the same I have found.
