### ISSUE TITLE
RFE: Propose changing references for flatpak build .yaml

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#294]
_org.opencpn.OpenCPN.Plugin.shipdriver.yaml_
To avoid confusion would it be better named as:
_org.opencpn.OpenCPN.Plugin.plugin.yaml_

_${PROJECT_SOURCE_DIR}/flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml_
In _CMakeLists.txt_ would become:
_${PROJECT_SOURCE_DIR}/flatpak/org.opencpn.OpenCPN.Plugin.plugin.yaml_

**Comment by leamas** [comment]
No, this not possible.  The first  of name part is the extension point in OpenCPN, the last part is used to create a plugin directory when the plugin is loaded. This is hardwired  in the Flatpak design, and nothing we could possibly change.

Otherwise, a good thought...
