### ISSUE TITLE
Library maintenance

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#296]
Each and every plugin derived from shipdriver has a libs/ directory with common utilities. These are general, not modified for each plugin.

Having a separate copy of each lib introduces a maintenance problem. When a library needs to  be updated, all plugins using must be updated. And when there is a bug it will most likely be fixed in a single plugin, leaving the others exposed for the same  bug. Etc.

The solution to this would be to use a git submodule. That is basically that we create a new project which contains all plugins of general interest,  and imports this project in each plugin. The advantage would be that we can maintain the plugins in a single place rather than a separate copy in each plugin.  For the plugins. this means that the libs directory is replaced with a reference to the common library project.

Adding a git submodule adds some complexity. The most obvious part is that it changes the way to clone the plugin. Other aspects includes how to update the libraries, this must be do using `git submodule` tools. 

I have made some preliminary tests. All in all, I think the addad complexity might be  worth it. It should also be acceptable early in the beta cycle, this does not add new functionality, it's more of re-factoring the code. Will make a PR later which can be evaluated

**Comment by Rasbats** [comment]
Not sure about this. How does it affect cloning and building locally? I like the independence of each plugin.

**Comment by leamas** [comment]
Let's discuss when there is a PR, I'm preparing it. Basically, you can do same the things as today, including changing libraries. But it's slightly more complicated.

**Comment by leamas** [comment]
Filed #298. let's talk there.
