### ISSUE TITLE
CircleCI: New terms & conditions

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#308]
Seems that we have problems with how we use our main CI service. See https://github.com/OpenCPN/OpenCPN/discussions/2467

**Comment by leamas** [comment]
The build matrix seems  to be something like:

  - Circleci: Can build everything, unclear account limitations
  - Travis ci: Can "probably" build everything, account restrictions requires manual intervention
  - Github Actions: No arm support, can build all amd64 stuff including Windows and MacOS.
  - Drone.io: Arm-only, cannot build debian-11.
  - Local circleci builds can typically build everything besides arm64 and MacOS. Flatpak requires refactored build scripts.
  - Appveyor: Windows only, single point of failure.

**Comment by Rasbats** [comment]
Had a problem with a plugin that I was moving from unmanaged to managed.
At first there was a problem with tokens.
Checked out the environment variables and then used "Import fom other repo" or something similar.
Selected the ShipDriver repo. The environment variables were accepted and the plugin could be build on circleci.
It may have been a typo that caused the initial issue but it could solve your problem.
circleci has not given me any other issues until today.

**Comment by leamas** [comment]
No, my problem is about my account. They have changed it from open-source to free, and applied restrictions.

See  https://github.com/OpenCPN/OpenCPN/discussions/2467 (just the beginning, the rest is basically Rick's blog).

Is your account also 'free' rather than 'open-source' these days?

**Comment by Rasbats** [comment]
Also Free.

**Comment by leamas** [comment]
so... we have a problem, all of us.

I have kept my ticket at CircleCI open, basically asking the question if there still are open-source individual accounts. No reply so far.

**Comment by leamas** [comment]
Problem solved, if it ever was a problem. Closing
