### ISSUE TITLE
Missing copyright & license

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#31]
There is no overall copyright and license statement, not any license file. 

In a open-source context this is really problematic, and would effectively make it impossible to include the plugin in a Linux dist.  Using the new manager this is not a problem, and all plugins are actually not open-source.  That said, creating some order here would make things more sane.

I suggest that you add something like  this to README.md, close to the icons statement:

---

This software is Copyright (c) Mike Rossiter 2017-2020. It is distributed under the terms of the Gnu Public License version 2 or, at your option, any later version. See the file COPYING for details.

The software contains open-source licensed files under different licenses including  Expat and Libpng. See the source files for details.

----

I cannot reasonably do this in a PR, it's your code. I propose GPLv2 since this is the main license used by OpenCPN;  there are too many other options (Expat/MIT comes to mind).

**Comment by Rasbats** [comment]
Thanks. Will do this. Fighting user icons at the moment.

**Comment by leamas** [comment]
user icons?

**Comment by Rasbats** [comment]
Not for ShipDriver luckily. For UKTides each port with tide predictions is shown with a waypoint that uses a tidal guage type icon. A number of pSharedDataLocations that had to be eliminated.

For ShipDriver: before submitting for publication intend that the plugin can transmit NMEA 'WPT' and 'RTE' sentences for an active route. Why ... OpenCPN cannot do this at the moment. It could be useful for testing other stuff.

**Comment by leamas** [comment]
Well, you have you statement in place. But it refers to the file COPYING, you need to add that as well. It is available in many places, one of which OpenCPN where it's called COPYING.gplv2.

**Comment by Rasbats** [comment]
Thanks again. I will close this one.
