### ISSUE TITLE
vdr_pi update

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#317]
I am trying to update vdr_pi  SD Template.
I have copied over the [relevant files and directories](https://opencpn-manuals.github.io/main/AlternativeWorkflow/Plugin-Adaptation.html), however there are some open questions.

1.  CMakeLists.txt   SD does not seem to have any  Set(SRCS  or Set(HDRS  etc.  Where do I put those?
2.  What do I do about validation and ssh now?  Has it changed from the recent process for Logbook? It appears the files have changed.
3.  I have the orginal vdr-plugin.xml.in   it is very different than the one in shipdriver. What should be done?
4. org.opencpn.OpenCPN.Plugin.TideFinder.yaml  will rename the 3 instances.
5. I am reviewing this. https://opencpn-manuals.github.io/main/AlternativeWorkflow/Plugin-Adaptation.html#_org_opencpn_opencpn_plugin_tidefinder_yaml

I think I will try the [automatic push to catalog. ](https://opencpn-manuals.github.io/main/AlternativeWorkflow/Catalog-Github-Integration.html)  at the end.

**Comment by rgleason** [comment]
1 .I found the  Plugin.cmake file where all the plugin detail goes. Will move the relevant stuff there.  Needs a note in the instructions. 
2. vdr-plugin-xml.in  and plugin-xml.in  are basically the same.  I was wrong about that.

**Comment by rgleason** [comment]
in Plugin.cmake
Have got the Options set
Do I need this naymore?


set(OCPN_TARGET_TUPLE
    ""
    CACHE STRING "Target spec: \"platform;version;arch\""
)

```
string(TOLOWER "${OCPN_TARGET_TUPLE}" _lc_target)
if ("${_lc_target}" MATCHES "android*")
  set(QT_ANDROID ON)
  # Until we have a proper toolchain file:
  set(CMAKE_CROSSCOMPILING ON)
```

**Comment by rgleason** [comment]
I am trying to build now, with my bld.bat file  
```
cd build
cmake -T v141_xp -G "Visual Studio 15 2017" ..
cmake --build . --target tarball --config RelWithDebInfo >output.txt
```
Which has two errors that I have not found an answer...my files are similar to Shipdriver's

```
vdr_pi.cpp(174): error C2561: 'vdr_pi::GetPlugInVersionMajor': function must return a value
vdr_pi.cpp(172): note: see declaration of 'vdr_pi::GetPlugInVersionMajor'
vdr_pi.cpp(179): error C2561: 'vdr_pi::GetPlugInVersionMinor': function must return a value 
vdr_pi.cpp(177): note: see declaration of 'vdr_pi::GetPlugInVersionMinor'
```

Here are vdr_pi.cpp  lines 172 - 179  similar to ShipDriver

```
int vdr_pi::GetPlugInVersionMajor()
{
     return PLUGIN_VERSION_MAJOR;
}

int vdr_pi::GetPlugInVersionMinor()
{
      return PLUGIN_VERSION_MINOR;
}
```

What should I check?

**Comment by rgleason** [comment]
Then there is the concern about running the scripts, as my widgets is located and built at  "c:/users/fcgle/source/widgets"

**Comment by leamas** [comment]
we are in the beta cyclr right now. Perhaps  better if you wait a little before 3.0 is out.

**Comment by rgleason** [comment]
I really like the separation of cmakelists.txt and plugin.cmake!

**Comment by leamas** [comment]
This is no issue, just a support request. Please close.

**Comment by rgleason** [comment]
we are in the beta cyclr right now. Perhaps better if you wait a little before 3.0 is out.

**Comment by rgleason** [comment]
PS  I went back to the old version and made the changes.
