### ISSUE TITLE
RFC: Add device context to allow drawing for Android builds

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#318]
Finally we have a 'Hello World' plugin which draws on the Android OpenCPN viewport: 
[https://github.com/Rasbats/oplaydo2_pi](https://github.com/Rasbats/oplaydo2_pi)

Jon's ODDC for ocpn_draw_pi works for that plugin but I could not make the DC work for a new plugin. 

Using recent ShipDriver code and Sean's piDC class from Climatology_pi and his overlay factory code lines can be drawn with oplaydo2_pi. The only addition needed for the SD template was the addition of _pidc.cpp_ and _pidc.h_ from Climatology_pi to _libs/plugingl_, with a small edit of _CMakeLists.text_ in _plugingl_. The Android work from @leamas  and the DC from @seandepagnier made the drawing possible.

This will allow updating of other plugins for Android that need to draw on the viewport. Is there any reason not to add piDC to ShipDriver? This would avoid a manual copy when using _update-templates_.

The files added already have a copyright notice at their head.

**Comment by leamas** [comment]
I see no reason why we should not update the libraries. Please make a PR against https://github.com/leamas/opencpn-libs/ so we record this in the proper place. And  update the shipdriver's libs to reflect these changes.

Yes, it's a pain to maintain the libraries when we have separate copies out in each plugin :)

**Comment by leamas** [comment]
The PR at https://github.com/leamas/opencpn-libs/pull/2 is merged. Are there any more open issues here, or should it be closed?

**Comment by Rasbats** [comment]
>Are there any more open issues here

Yes. Spent the last several days trying to write text on the Android viewport. TBC.

**Comment by Rasbats** [comment]
_oplaydo2_pi_ uses the ShipDriver template but the device context files are in the src files. _pidc.cpp/h_ removed from ShipDriver.
