### ISSUE TITLE
RFE: Patches branch needs a new home

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#32]
Hi,

As you probably have understood, my plan is to make this plugin sort of a demo one. Most things are sorted out, hopefully all are happy. 

However, the way to this state has been complicated with multiple bugs and fixes. What I want to show to others is a reasonably clean history with a set of useful commits. To that end I have created a branch which leads up to same state as 61cf77c (before the reformatting), but with a clean history. I would be thankful if you just could let this branch live in this repo. The way to accomplish this would be

    $ git remote add leamas https://github.com/leamas/shipdriver_pi.git
    $ git fetch leamas patches:patches

Thanks in advance...

--a

**Comment by Rasbats** [comment]
Sorry... should have waited perhaps before adding the remote. Do you have it ok?

**Comment by leamas** [comment]
Yes, it is ok. Thanks!

Forgot to mention that it's not that useful until you publish it:` git push origin patches`.

--a

**Comment by leamas** [comment]
Patches branch has got a new home... closing
