### ISSUE TITLE
Local builds - MacOS - json library problem

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#330]
From Tony Voss:
Being able to repeatedly run ‘make tarball’ without re-running circleci-build-macos.sh or whatever is essential.  I use it repeatedly:  edit code; make tarball; import plugin & reinstall.  So yes please make this work.  I guess jsoncpp need not be recompiled each time as with any code that has not been touched?

Tony does not want to delete build-osx and run the script each time he changes code. 
I have forgotten the reasons for json being a default library. Is this necessary?

**Comment by leamas** [comment]
hm... we don't test macos that much. Resources are scarce....

Repeated builds works fine on at least Linux/flatpak.  Agree that is should on MacOS as well.  That is, after the first run of _circleci-build-macos.sh_ it should be possible to just run `make`, do some editing, and run `make` again. This way, the libraries etc should still be in place without any need to rebuild them

Could we get  Tony in the loop here? What happens if he tries this?

**Comment by leamas** [comment]
> I have forgotten the reasons for json being a default library. Is this necessary?

Not really. If it builds without it, so fine. One of the final patches before 3.0.0 was to  handle a missing libjsoncpp library without a build failure.

**Comment by leamas** [comment]
I have actually made some testing. In short, if this is an issue it's about documentation.

 After running _circleci-build-macos.sh_ it works just fine to run run `make` in the build-osx directory, do some editing and then run `make` again. When doing so, just the files which needs to rebuilt are actually compiled. In particular, various libraries are already compiled and will not be rebuilt unless touched.

**Comment by Rasbats** [comment]
But `make tarball` ? To allow an import and test.

**Comment by leamas** [comment]
`make`actually does the same as `make tarball`,

**Comment by leamas** [comment]
hm... doing `make tarball` I can reproduce an error like "The binary directory .../build-osx/libs/jsoncpp is already used to build a source directory". This is probably the actual  issue. I will look into it.

**Comment by leamas** [comment]
This libjsoncpp is a mess, my bad. For now, this patch fixes it:

```
+++ b/Plugin.cmake
@@ -89,6 +89,4 @@ macro(add_plugin_libraries)
   add_subdirectory("libs/plugingl")
   target_link_libraries(${PACKAGE_NAME} ocpn::plugingl)
 
-  add_subdirectory("libs/jsoncpp")
-  target_link_libraries(${PACKAGE_NAME} ocpn::jsoncpp)
```

The logic in main CMakeLists.txt includes libjsoncpp if it exists. When plugin.cmake incudes it again, we get the error. 

Now, 3.0.0 is out, and we should not change this during the 3.0 cycle. Problem is easily avoided in Plugin.cmake, see above. But in a longer perspective (4.0?) we should probably re-consider the (lack of) design here.

**Comment by leamas** [comment]
A second thought: A possible patch while still in the 3.0 branch could be

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7809385..aff783f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -78,15 +78,15 @@ if (NOT ${BUILD_TYPE} STREQUAL "flatpak")
 
   include_directories(BEFORE ${CMAKE_BINARY_DIR}/include)
 
-  if (EXISTS "libs/jsoncpp")
-    add_subdirectory("libs/jsoncpp")
-    target_link_libraries(${PACKAGE_NAME} ocpn::jsoncpp)
-  endif ()
-
   if (COMMAND add_plugin_libraries)
     add_plugin_libraries()
   endif ()
 
+  if (EXISTS "libs/jsoncpp" AND NOT TARGET ocpn::jsoncpp)
+    add_subdirectory("libs/jsoncpp")
+    target_link_libraries(${PACKAGE_NAME} ocpn::jsoncpp)
+  endif ()
+

```
That is, CMakeLists loads the libjsoncpp directory iff it exists and is not loaded by Plugin.cmake. Just logging an idea, nothing more.

**Comment by leamas** [comment]
See also #331
