### ISSUE TITLE
#define PLUGIN_VERSION_TWEAK 

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#341]
The value in the 'Tweak' is not carried through to _build/config.h_ 

e.g. v0.5.0.1 - the '1' will not be available to the plugin.
PLUGIN_VERSION_TWEAK = ""

**Comment by leamas** [comment]
hm... When I make a preliminary test and sets PKG_VERSION to 3.0.0.1 the correct value '1' is available in config.h?

Is this about the default value used when, as in the normal case, only a three digit version is used? In which case PLUGIN_VERSION_TWEAK indeed is the empty string "". Did you, right or wrong, expect it to be '0' in this case?

**Comment by Rasbats** [comment]
This came from Tony Voss looking to use Patch and Tweak for JavaScript_pi.
Not sure if he tested with '1' but yes ... I would have expected '0' if 4 digits had been set.

**Comment by Rasbats** [comment]
In _CMakeLists.txt_ I see `set(VERSION_PATCH ${PROJECT_VERSION_PATCH})`
but there is no `set(VERSION_PATCH ${PROJECT_VERSION_TWEAK})`

**Comment by leamas** [comment]
> This came from Tony Voss 

Any chance you could get Tony to file bugs directly here?

> Not sure if he tested with '1' but yes ... I would have expected '0' if 4 digits had been set.

You mean three digits set? With four digits set, the expectation must be that PROJECT_VERSION_TWEAK is the fourth digit, which it indeed is.

> In CMakeLists.txt I see set(VERSION_PATCH ${PROJECT_VERSION_PATCH})
but there is no set(VERSION_PATCH ${PROJECT_VERSION_TWEAK})

Yes, this is sort of inconsistent and should probably be fixed. But it does not affect config.h which is generated from the cmake variable PROJECT_VERSION_TWEAK.

**Comment by Rasbats** [comment]
I will let Tony file a new bug for this if it is needed.

**Comment by leamas** [comment]
> Yes, this is sort of inconsistent and should probably be fixed.

At a second though I'd prefer not to fix it. The VERSION_MAJOR and VERSION_MINOR legacy. I have kept them to  not cause too much trouble in existing plugins.  However, using the official, and documented PROJECT_VERSION_MAJOR and PROJECT_VERSION_MINOR is actually better, chances are higher that users finds out what they are about.

For that reason I think it's a bad idea to introduce the obviously not used VERSION_TWEAK. It's simple better to use the existing PROJECT_VERSION_TWEAK.
