### ISSUE TITLE
Torture Testing and Tweaks

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#347]
Please let me know when you have finished servicing SD and have her aall polished up for the next period of use.
I need to update VDR_pi so that it is available in MacOS.  Thank you.

**Comment by leamas** [comment]
This will never be finished, this is not how software development works.

Current stable release is sd3.0.0. Please use that or the  v3.0 release branch,  currently on same commit. If there are problems, file bugs and we will try to handle them
