### ISSUE TITLE
update-templates: please cherry-pick updates to release branch

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#350]
We have a some patches in main which are plain bug fixes and thus preferably should go into the release branch.

One example is fixes to update-templates. There is no reason whatsoever to not update this script, it is not hampered by compatibility  issues. That is, a working 3.0.0 installation will not break due to changes in this script. 

To cherry-pick, first list the last commits in master:
```
$ git checkout master
$ git log --oneline -17
63c863f (HEAD -> master, origin/master, origin/HEAD) Actually use the tag as effective version (#349)
549282c Metadata: git tag --contains -> git tag --points-at.
9de058f ci: flatpak: Drop 18.08 transition build (#346).
1e1747d ci: flatpak: aarch64: Use stable branch after 5.6.0 release.
4cc6d19 flatpak: manifest: Set runtime version to correct 'stable'
ae6ffa0 Flatpak: Copy build from sandbox before use (#348).
df30f11 flatpak: keep build dirs.
ed6f406 ci: Flatpak: Build aarch64 from stable branch after  5.6.0 release.
57d5b88 (upstream/master) update-templates: Don't forget to pdate buildwin (#133).
65546d2 Build: Fix repeated plain 'make' errors (#331).
8bddc3d update-templates: Remove unused files (#336).
7eab21c Changolog: update.
c6620bc Remove special handling of libjsoncpp in CMakeLists.
75e49cd appveyor: Use the regular win_deps.bat script for builds.
539165f PluginLibs: Remove old MSYS hacks.
fb5cfd6 PluginLibs: Restructure using sane sections.
298c16b (upstream/v3.0) CMakeLists: Only link libjsoncpp if not done by Plugin.gl (#330).
```

Here we can see ll commits in master added since after v3.0 was branched.  The commits which patches _update-templates_ is `8bddc3d`  and `57d5b88`. To cherry-pick these into the v3.0 release branch:

    $ git checkout v3.0
    $ git cherry-pick 8bddc3d
    $ git cherry-pick 57d5b88

... and push the updated v3.0 branch

**Comment by leamas** [comment]
We should IMHO also pick 549282c and 63c863f into v3.0. Together, these fixes the issues described in #349 without breaking any eggs.

**Comment by leamas** [comment]
@rasbats: Ping? IMHO, we need to prepare for a 3.0.1 release. I can do as a PR, but it would certainly be better if you would be able to control this yourself.

Thoughts?

**Comment by Rasbats** [comment]
@leamas : Could you fix this please.

**Comment by leamas** [comment]
OK, I'm on it.

**Comment by leamas** [comment]
We have release branch in place. Closing.
