### ISSUE TITLE
RFE: Checkbox option to use as an Autopilot Testing device?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#353]
Please see Douwe's note
https://www.cruisersforum.com/forums/f134/reliable-methods-for-desktop-testing-of-autopilot-plugins-258742.html#post3537499

It would be very helpful for some types of autopilot Plugins.

**Comment by rgleason** [comment]
Also I haven't tried Shipdriver lately and intend to do so, but it would also be helpful to include setting of True/apparent Wind direction and speed (maybe just true is all that is necessary) and Current direction and speed, to allow testing of autopilot modes in those conditions.

**Comment by Rasbats** [comment]
After a week of attempts at making a simulator to test autopilot-Plugin I have given up. I can generate SEATALK sentences but passing these between plugins has not proved possible.

>but it would also be helpful to include setting of True/apparent Wind direction and speed 

Use a grib file?

>Current direction and speed, to allow testing of autopilot modes in those conditions.

No time here. Perhaps Douwe should make a version available.

**Comment by rgleason** [comment]
Mike thank you for trying for week, sorry about that. Douwe has an earlier version of shipdriver that he adapted which I will try to find on his repos. Have you seen it?

**Comment by rgleason** [comment]
I may try to do a compare and update it.

**Comment by rgleason** [comment]
I've found these changes by Douwe for autopilot  looking at the network view  starting July 29  Douwe branch
https://github.com/douwefokkema/shipdriver_pi/network  

1. Added input of HSC sentence to enable control by autopilot. HSC sentence has priority over APB sentence   July 29
https://github.com/douwefokkema/shipdriver_pi/commit/4f91ba878bedc4d4b149b25ec46db6de4a68552f

2. Always on Auto!    Oct 18, 2019
https://github.com/douwefokkema/shipdriver_pi/commit/f3c98a9f6aaed39695cd46b8fb78d39201f4b803

3. Disable APB   Oct 18, 2019
https://github.com/douwefokkema/shipdriver_pi/commit/47b3b33fcbb6c45e6fb3eb58e490183fdee162d9

4. Again always auto mode   Oct 18,2019
https://github.com/douwefokkema/shipdriver_pi/commit/16193c3aff93eab00e4566f4f12828d99b7e78da

5. Test  May 5 2020   some interface changes and other things.
https://github.com/douwefokkema/shipdriver_pi/commit/5971fbc95cc2267dd23251a92ae13c453a45042f

6. UI for currents working  May 5, 2020
https://github.com/douwefokkema/shipdriver_pi/commit/ac38068d63cf83365ae1080410d2591873d42ac2

7.  Currents functioning  May 5, 2020
https://github.com/douwefokkema/shipdriver_pi/commit/e0c42df8fd49a42b5a16c7a35aba997265ef090c

It appears to me that I need to revert my clone of Douwe's shipdriver   back to "7.  Currents functioning  May 5, 2020" above to get it working as a testing bed for autopilots?   Is that correct?
https://github.com/douwefokkema/shipdriver_pi/commits/e0c42df8fd49a42b5a16c7a35aba997265ef090c

I've been trying to get a fork of Douwe's shipdriver building. I am almost there, but am missing some of the Shipdriver template files from that time, like cloudsmith-upload.sh  .  I will try to retrieve them next.

**Comment by rgleason** [comment]
Closing
