### ISSUE TITLE
SVG handling: cleanup required.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#354]
The current SVG handling is not ideal.
  - Each and every plugin defines it's own WHATEVER_USE_SVG symbol. Makes things less generic for no use besides keeping at least a single item in `late_init()` as an example.
  - ocpn_plugin.h defines `ocpnUSE_SVG`, we need to synchronize there
  - Using `ocpnUSE_SVG` means  that the wxsvg headers must be available. However, the current wxsvg library in opencpn-libs is an unusable mess copied from OpenCPN.
  - IMHO,  shipdriver should have a SVG plugin icon as an example.

**Comment by rgleason** [comment]
This work would be a big help. I am wonder about the use of <PluginName>_USE_SVG   and  ocpnUSE_SVG  and have been using the more generic  PLUGIN_USE_SVG similar to testplugin.

**Comment by leamas** [comment]
Fixed in #355. Closing
