### ISSUE TITLE
update-templates not importing libs from SD

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#360]
Working on an update of sar_pi. No libs directory imported from SD.

**Comment by leamas** [comment]
You are starting at dda3f09, right?

**Comment by Rasbats** [comment]
Yes and before that commit 88d3e471b2937e5d1b63d3f039b1973922346a2f

**Comment by leamas** [comment]
OK, seems to be a rebasing problem. PR under way...

**Comment by Rasbats** [comment]
But I don't see libs in the script.

**Comment by leamas** [comment]
Here are multiple issues:
  - First, here are some line endings stuff. Fix by:
  
        $ git add --renormalize src/NavFunc.h src/SAR_pi.h src/icons/icons.sh src/SARgui_impl.h
        $ git commit -m "src: Re-normalize line endings."

- Second: The question about whether to copy libs or not is basically in transition. Once we are using opencpn-libs everything in libs is per definition private and should not be copied. 

Seems that we should add libs again to keep things sane until opencpn-libs is actually used. Will make a PR.
