### ISSUE TITLE
Is a ci  darwin-wx315 version needed?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#371]
Just wondering.

**Comment by leamas** [comment]
This is not a Q&A forum. Sorry.

**Comment by rgleason** [comment]
You need a darwin wx315 version

**Comment by rgleason** [comment]
Won't be so polite in the future.

**Comment by Rasbats** [comment]
[https://github.com/OpenCPN/plugins/tree/master/metadata](https://github.com/OpenCPN/plugins/tree/master/metadata)

In the catalog. Is there a problem with this version?

**Comment by rgleason** [comment]
Thanks.  Not that I know of.  This was started 11 days ago. and is closed.

**Comment by rgleason** [comment]
Testplugin has a darwin-wx315 version now.

**Comment by rgleason** [comment]
Found it for shipdriver
