### ISSUE TITLE
RFE: Bootstrapping is confusing

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#373]
Had a play with otidalroute_pi. The repo is back to unmanaged but contains an edited version of update-templates.

Two changes:
*  `git remote add -t v3.0 shipdriver https://github.com/Rasbats/shipdriver_pi.git`
* `if ! git diff --quiet FETCH_HEAD $source_treeish -- update-templates; then`

The first creates a remote using the v3.0 branch of shipdriver.

The second uses FETCH_HEAD iso HEAD. FETCH_HEAD.

If the v3.0 branch of ShipDriver had this edited version of update-templates would copying the files from ShipDriver/v3.0 to the plugin allow us to drop the Bootstrapping?

**Comment by Rasbats** [comment]
But I did not add the shipdriver remote so it failed to list the tags.

**Comment by Rasbats** [comment]
But this could be added to `function list_sd_tags() `.

**Comment by leamas** [comment]
> Had a play with otidalroute_pi. The repo is back to unmanaged but contains an edited version of update-templates.

These games are hard to play. The script updates itself so whatever changes are done they will be  lost. I think I will be able to make a PR tomorrow, but until then I suggest that you work-around by creating n the remote.

**Comment by leamas** [comment]
> But this could be added to function list_sd_tags()

Yes, or perhaps in the command. My first attempt yesterday went wrong.

**Comment by leamas** [comment]
> If the v3.0 branch of ShipDriver had this edited version of update-templates would copying the files from ShipDriver/v3.0 to the plugin allow us to drop the Bootstrapping?

No. The bootstrap procedure does not include a local copy of shipdriver. For you, this is more or less implied, but for other users it's not. Which means bootstrapping must get it's stuff from the canonical source which is the remote github shipdriver clone.

Otherwise, would need to add instructions to first make a clone of shipdriver to the instructions. This is more to read and do compared to current state. 

Personally, I think that the really confusing fact that it just doesn't work. We need to fix that, almost there but we [need a new tag](https://github.com/Rasbats/shipdriver_pi/pull/374#issuecomment-1003719696)

**Comment by Rasbats** [comment]
>but we need a new tag

sd3.0.1-beta2 created.

**Comment by Rasbats** [comment]
sd3.0.1-beta3 created.

Not sure what happened but _libs/api-17_ was not working correctly for compiling JavaScript_pi, which uses API 117. Replacing _libs/api-17_ resolved the problem.

After a number of false starts things seem to have been sorted out, using an old _libs/api-17_. Javascript_pi compiles using 
`./update-templates sd3.0.1-beta3`.

**Comment by leamas** [comment]
> Not sure what happened but libs/api-17 was not working correctly for compiling JavaScript_pi, which uses API 117. Replacing libs/api-17 resolved the problem.

You did this in master branch. We need to keep two things running simultaneously:
   - The master branch is moving in direction to using a git submodule for libraries.
   - The v3.0 branch is keeping the old (broken) structure where every plugin has it's own copy.
   
Now, and this is partly my bad, we are totally lost. The sd3.0.1-beta3 tag points to the master branch, which obviously makes no sense. We have branched the beta in the v3.0 branch, and the that is the branch which should be updated and eventually released as v3.0.0.  I'll be back later, pretending I have a life for some time first. But, we  really need to sort this out....

**Comment by Rasbats** [comment]
>The v3.0 branch is keeping the old (broken) structure where every plugin has it's own copy.

Still unhappy about using another github user's repo for the libs. Why can't I fork your _opencpn-libs_ and use the libs from there? This repo could probably also be used as a sub-module???

**Comment by leamas** [comment]
> Still unhappy about using another github user's repo for the libs. Why can't I fork your opencpn-libs and use the libs from there? This repo could probably also be used as a sub-module???

The important thing is about maintenance. My long-term plan is to make opencpn-libs available in a wider context than just shipdriver. For that reason I'd prefer to have it somewhere else. Not necessarily at my own user, but somewhere else. The best would be if I could persuade Dave to create opencpn/opencpn-libs and let me have permissions on it...

But, what is the problem for you here, really? Is it that you perceive that you cannot change the libraries in the submodule? If so, this is a misconception, I could expand on it if you want.

**Comment by leamas** [comment]
BTW: Since we are discussing the libraries which really belongs in #338 I presume that the bootstrapping stuff is still ok after moving things to the correct branch?

**Comment by Rasbats** [comment]
Nope ... libs/api-17 is broken. Will try and fix for v3.0 branch.

**Comment by leamas** [comment]
$ git checkout v3.0
    $ git checkout master libs/api-17
    $ git commit -m "Update libs/api-17 from master."

**Comment by Rasbats** [comment]
Still fails. Do I need a different tag than sd3.0.1-beta4, which was before libs/api-17 was changed?

**Comment by leamas** [comment]
Fails in what way?

**Comment by leamas** [comment]
>  Do I need a different tag than sd3.0.1-beta4, which was before libs/api-17 was changed

If you run update-templates with a tag, you get the tag. But, you could test by manually updating libs-api17 first.

**Comment by Rasbats** [comment]
Manual update works. New tag?

**Comment by leamas** [comment]
Yes

**Comment by Rasbats** [comment]
Done. Looks good for both JavaScript_pi and ShipDriver.

One concern is that the script allows a non-working beta to be used. Should it use the latest tag, even if it has to be entered on the CL?

**Comment by leamas** [comment]
> One concern is that the script allows a non-working beta to be used. Should it use the latest tag, even if it has to be entered on the CL?

That betas are broken, well, that's part of the concept. After all, we build betas in order to test them, and that they fail is not (should not be) unexpected.

I suggest that we make a recommendation in the docs to use the latest stable (i. e., non-beta) tag. That should IMHO be sufficient for now. Will make a PR.

**Comment by leamas** [comment]
> Will make a PR.

Done: #377

**Comment by leamas** [comment]
@rasbats: Still confusing?
