### ISSUE TITLE
3.0 checklist

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#376]
@ rasbats: is there anyhing which stops us from releasing 3.0.1? There are builder issues for drone.io and perhaps CircleCI MacOS builds, but these are IMHO better handled in next release.

Anything else?

**Comment by leamas** [comment]
And the libs/api-17 thing.

**Comment by leamas** [comment]
Assuming libs are  OK  after latest patches (?)

The non-working examples should be handled by #377 

@Rasbats : anything more?

**Comment by leamas** [comment]
I have possible problems building after using update-templates. Needs time to investigate.

**Comment by leamas** [comment]
and #378

**Comment by leamas** [comment]
After #379 things works also for more complex plugins like oesenc and o-charts. They now build OK after an update, previously the update broke the builds.

As far as I can see, things are ready for 3.0.1 after merging #379.

@Rasbats: anything more?

**Comment by Rasbats** [comment]
>As far as I can see, things are ready for 3.0.1

Agree.

**Comment by leamas** [comment]
well, then let's tag v3.0 as sd3.0.1. And see that other users,  including Rick, get the message.

Question: How do we announce our releases? Perhaps just a new thread in OpenCPN discussions?

**Comment by leamas** [comment]
Oops.. don't forget the Changelog before tagging

**Comment by Rasbats** [comment]
>tag v3.0 as sd3.0.1.

All done. 

>Perhaps just a new thread in OpenCPN discussions?

That would reach the majority of interested parties. Your call.

**Comment by leamas** [comment]
All done, closing
