### ISSUE TITLE
VDR & Logbook Updates - what branch?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#382]
I have been struggling to get the SD master branch template working.
It creates all kinds of errors not finding essential cmake files.  I have not found the reason for this.
What branch should I be using?
This one?
https://github.com/Rasbats/shipdriver_pi/tree/v3.0

**Comment by rgleason** [comment]
For example,  re VFKaps, just pushed to plugins.
You could indicate what  S[D template version here in Plugin.cmake](https://github.com/Rasbats/vfkaps_pi/blob/master/Plugin.cmake)  it might help in several ways....

#
#
# -------  Plugin setup --------
#  SD Template v????

**Comment by rgleason** [comment]
PS Currently there is no logbook pushed to plugins due to older security issues. I need to build it and push

**Comment by Rasbats** [comment]
v3.0 branch is the current one to use. However the tag sd3.0.1 is not producing Raspbian Bullseye or Flatpak build:  - build-flatpak-x86-1808

Have raised an issue here:  #383

**Comment by rgleason** [comment]
Thanks, maybe that one will build for me. I will add the others when fixed.  I think Raspian Bullseye may start using Debian from other issues.
