### ISSUE TITLE
sd3.0.1 failing for raspbian-bullseye and flatpak-arm64

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#383]
Builds with commit #e1bca7e worked fine.

Updated to the sd3.0.1 template and there are failures. In the Raspbian config.yml script I see a missing build   - build-flatpak-x86-2008. Forgot the discussion about this build.

Cannot see the reason for the raspbian build failing. 

[https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/11/workflows/d9813b2f-c705-4e92-89ba-9b8e8e1527a6/jobs/113](https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/11/workflows/d9813b2f-c705-4e92-89ba-9b8e8e1527a6/jobs/113)

[https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/11/workflows/d9813b2f-c705-4e92-89ba-9b8e8e1527a6/jobs/105](https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/11/workflows/d9813b2f-c705-4e92-89ba-9b8e8e1527a6/jobs/105)

**Comment by leamas** [comment]
Made a PR  which should close this. However, we cannot verify it right now, see #386.

**Comment by leamas** [comment]
The bigger issue here is how this could slip through out testing.  We need to make a  checklist before making a release. It should include:
- Does update-templates do it's job?
- Does everything  build as expected?
- Some  basic smoke tests of the plugin, at least omn one platform: Does it load, is basic functionality in place.

@Rasbats:  Thoughts?

**Comment by Rasbats** [comment]
Cloudsmith doing routine maintenance this pm.

First: build-flatpak-x86-2008 : Has this been discontinued?

>Thoughts?

[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi?filter=all)

Right or wrong (probably wrong) I imagined a build of ShipDriver v3.0 would reveal errors like this.

[https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi?filter=all)

Testing with JavaScript_pi revealed the errors with libs, which got fixed. Before this, using a manual fix, resulted in good builds. Perhaps the commits that addressed the issue (libs) caused the problem. Not revealed until I used sd3.0.1.

Problem was revealed when using sd3.0.1 with other plugins. Bugs found. Ergo - extensive testing was carried out. sd3.0.2 starts here I think. 

Once a tag is tested should non-working tags be removed to avoid errors? In fact, because of the libs issue, should all previous tags be removed once we start sd3.0.2-beta1?

**Comment by leamas** [comment]
> First: build-flatpak-x86-2008 : Has this been discontinued?

No, but  build-flatpak-x86-1808 is. The logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1273/workflows/b5efc00f-7546-44e8-bede-3106e06ac970) shows it (they all fail since cloudsmith is down...)

**Comment by leamas** [comment]
> Once a tag is tested should non-working tags be removed to avoid errors?

No. Established best practise is to treat tags as immutable. We need better testing before we tag,  see [comment in #383](https://github.com/Rasbats/shipdriver_pi/issues/383#issuecomment-1008018296).

According to our findings here,  we should expand the testing of update-templates by applying it to other plugins. Also I found last-minute changes before tagging sd3.0.1 this way.

**Comment by leamas** [comment]
| Once a tag is tested should non-working tags be removed to avoid errors?

Another question is if we should list it in update-templates. here, we could certainly blacklist unusable tags to make life simpler for end users.

**Comment by Rasbats** [comment]
>we could certainly blacklist unusable tags

Agree with blacklisting.

**Comment by leamas** [comment]
OK, but let's postpone it to next major release. For now, we  should avoid new  code in the  v3.0 branch and hence in v3.0.2. The online  help clearly says the recommended usage is "last stable tag", it should  cover it  for now.

**Comment by Rasbats** [comment]
>hence in v3.0.2

sd3.0.2?

**Comment by leamas** [comment]
yup...

**Comment by Rasbats** [comment]
[https://ci.appveyor.com/project/Rasbats/shipdriver-pi](https://ci.appveyor.com/project/Rasbats/shipdriver-pi)

Untagged build compiles. Put a small edit in and rebuilt with tag. Windows fails to build. 
@leamas : Your work on Raspbian and Flatpak has fixed the builds for those OS. Testing with other plugins.

**Comment by Rasbats** [comment]
The edit was just CR/NL (Windows). Is this a reason for failing?

**Comment by Rasbats** [comment]
Do we still need poedit?

**Comment by leamas** [comment]
> Do we still need poedit?

No idea,  you are the Windows guru. Can you run the build script in appveyor without poedit?

That said, this looks like a server problem which very well can be sporadic. What happens if you wait for some time and rebuild?

**Comment by Rasbats** [comment]
>this looks like a server problem

Correct ... it builds this morning.

**Comment by Rasbats** [comment]
Another poedit fail with EarthExplorer when testing Checksums.

[https://ci.appveyor.com/project/Rasbats/earthexplorer-pi/builds/42144532](https://ci.appveyor.com/project/Rasbats/earthexplorer-pi/builds/42144532)

**Comment by leamas** [comment]
> Could not connect to the feed specified at 'https://community.chocolatey.org/api/v2/'. 

This is a server problem, we can just hope they will fix it. 

The status page is at https://status.chocolatey.org/ and does not report any problem. What happens if you rebuild right away?
