### ISSUE TITLE
sd3.01  Upate-templates.md  - Add remote shipdriver

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#390]
In update-templates.md

Please add the following under    **Options:**

**-l** lists available tags which can be used as _treeish_    
(Necessary to do this first, as it adds a remote  "Shipdriver")

First step:  `./update-templates -l`

**Comment by leamas** [comment]
Please close. There is no such need.

**Comment by rgleason** [comment]
Why not?  You want everyone starting to use this to be in the dark?

**Comment by leamas** [comment]
Because the statement  _Necessary to do this first, as it adds a remote "Shipdriver"_  is plain wrong.  It just reflects your experiences after using -T, which is a test tool only.

**Comment by rgleason** [comment]
As I said **_I didn't use -T_**  I just asked if it was the proper tool to use.  It was a question!

**Comment by rgleason** [comment]
Do what you want. You'll have this question again ...and again.

**Comment by leamas** [comment]
> Please add the following under Options: [..]

A question?

**Comment by rgleason** [comment]
My question was in another issue, when I first approached using update-templates, after reading everything available.

**Comment by rgleason** [comment]
I removed remote shipdriver and then executed  ./update-tempates -I 
and it did indeed add a shipdriver remote again.
Why not tell your followers this?

```
fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ git branch -va
  master                  6826d72 Trigger build
* v3.0                    fd46a27 rm gitmodules
  remotes/origin/master   6826d72 Trigger build
  remotes/origin/v3.0     fd46a27 rm gitmodules
  remotes/upstream/master 53ac07c Merge pull request #42 from rgleason/master

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ git remote -v
origin  git@github.com:rgleason/LogbookKonni_pi.git (fetch)
origin  git@github.com:rgleason/LogbookKonni_pi.git (push)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (fetch)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (push)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (fetch)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (push)

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ git remote remove shipdriver

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ git remote -v
origin  git@github.com:rgleason/LogbookKonni_pi.git (fetch)
origin  git@github.com:rgleason/LogbookKonni_pi.git (push)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (fetch)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (push)

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ ./update-templates -l
Adding new shipdriver remote
sd3.0.0
sd3.0.0-beta1
sd3.0.0-beta2
sd3.0.0-rc1
sd3.0.1
sd3.0.1-beta1
sd3.0.1-beta4
sd3.0.1-beta5
sd3.0.2-beta1

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ git remote -v
origin  git@github.com:rgleason/LogbookKonni_pi.git (fetch)
origin  git@github.com:rgleason/LogbookKonni_pi.git (push)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (fetch)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (push)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (fetch)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (push)

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$

```

**Comment by rgleason** [comment]
Please add the following under Options:

-l lists available tags which can be used as treeish
(Necessary to do this first, as it adds a remote "Shipdriver")

First step: ./update-templates -l

**Comment by leamas** [comment]
> (Necessary to do this first, as it adds a remote "Shipdriver")

It is not necessary (third time I repeat this?). The remote will be created in any case when doing the actual update.

**Comment by rgleason** [comment]
Oh really.  Did not experience that.  So if I execute "./update-templates" it also adds a remote shipdriver.  .. Sorry.  Well this is closed.

**Comment by leamas** [comment]
>  Did not experience that

probably because you were using -T
