### ISSUE TITLE
 EarthExplorer managed version v1.0.0 - Raspbian 9.13 armhf metadata checksum failed

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#391]
[https://github.com/OpenCPN/plugins/runs/4752872859?check_suite_focus=true](https://github.com/OpenCPN/plugins/runs/4752872859?check_suite_focus=true)

Have now removed the _plugins/metadata_ file for this OS.

**Comment by leamas** [comment]
OK. Can you attach it the metadata file here? 

Is there a build link?

**Comment by Rasbats** [comment]
[metadata.xml.txt](https://github.com/Rasbats/shipdriver_pi/files/7838401/metadata.xml.txt)

[https://cloud.drone.io/Rasbats/EarthExplorer_pi/16/1/2](https://cloud.drone.io/Rasbats/EarthExplorer_pi/16/1/2)

**Comment by leamas** [comment]
hm... That metadata file is the one bundled in the tarball, right?  What I need is the metadata file uploaded to cloudsmith which contains a checksum.

That said, I cannot reproduce this. I have cloned your repo and made a single commit in README.md;

```
db164cf (HEAD -> build, origin/build) Useless README commit.
4156886 (tag: v1.0.0, upstream/master, upstream/HEAD, origin/master) cmake: Update TemplateVersion to e49825d
```

I then pushed this. The results are available in [Cloudsmith](https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/) and in my [auto branch](https://github.com/leamas/plugins/commits/auto)

The checksum in all of them is the same:  30a10ae4a87.... 

I suggest that you do the same: add a useless commit to for example README  and push. This will generate a build which eventually will
  - upload the tarball to unstable/Alpha
  - Likewise, upload the metadata file
  - push the metadata to auto branch at plugins.

To check, download the tarball and xml metadata file. Then, compute the correct checksum using `cmake -E sha256sum path-to-tarball.tar.gz`. Compare this to the  checksum in the metadata results. 

Then in your plugins clone, check the auto branch using

    $ git remote update origin
    $ git fetch origin auto:auto-tmp
    $ git checkout auto-tmp
    $ git log --oneline -14

You should see something like 
```
269f70d3 (HEAD -> auto, origin/auto) db164cf: raspbian-armhf: Useless README commit.
e8d278e8 db164cf: raspbian-armhf: Useless README commit.
3df0ed14 4156886: raspbian-armhf: cmake: Update TemplateVersion to e49825d
4ce4f55a 4156886: raspbian-armhf: cmake: Update TemplateVersion to e49825d
2bb1725f 64c069a: raspbian-armhf: sd3.0.2-beta1
ac7369b7 64c069a: darwin-wx315: sd3.0.2-beta1
e2bf8092 64c069a: msvc: sd3.0.2-beta1
bcde1e4e 64c069a: raspbian-armhf: sd3.0.2-beta1
821970df 64c069a: flatpak-x86_64: sd3.0.2-beta1

```
Try to identify the commit which adds the raspbian-armhf commit, in my case it's the latest  269f70d3; might be different for you. Take a look at it using `git show 269f70d3`. This prints the complete metadata file, and you can compare the checksum with the value from above.

**Comment by Rasbats** [comment]
[EarthExplorer-v1.0.0-raspbian-9.13.xml.txt](https://github.com/Rasbats/shipdriver_pi/files/7838913/EarthExplorer-v1.0.0-raspbian-9.13.xml.txt)

**Comment by leamas** [comment]
hm... That is the same checksum as reported as wrong when checking. Which means that git-push is in sync, no problems there. But that some how the checksum is wrong.  Please do the first steps from me previous post i. e., make a commit, rebuild download metadata + tarball and check the checksum. If they are OK this is some transient error, otherwise not.

**Comment by Rasbats** [comment]
Checksums found to be the same. Probably a transient. 

[EarthExplorer-1.0-raspbian-9.13.xml.txt](https://github.com/Rasbats/shipdriver_pi/files/7839449/EarthExplorer-1.0-raspbian-9.13.xml.txt)
[EarthExplorer-1.0.0+17.1d49409_raspbian-9.13-armhf.tar.gz](https://github.com/Rasbats/shipdriver_pi/files/7839450/EarthExplorer-1.0.0%2B17.1d49409_raspbian-9.13-armhf.tar.gz)

Closing. Not making another build unless someone yells.

**Comment by leamas** [comment]
OK. Back to #392...
