### ISSUE TITLE
sd3.0.2 test checklist

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#392]
✓ All shipdriver builds OK
✓ update-templates works on o-charts and Logbook
✓ shipdriver plugin basic functionality
✓ Last minute doc changes to update-templates  #394
✓ update-templates works on Tidefinder. 
✓ #391 (alec)

@Rasbats: thoughts?

**Comment by Rasbats** [comment]
✓  shipdriver plugin basic funtionality

>? update-templates works on Tidefinder + ? (mike)

BBL

**Comment by leamas** [comment]
This feels more comfortable than 3.0.1. Are we ready to release?

**Comment by leamas** [comment]
@Rasbats: ^

**Comment by Rasbats** [comment]
>Are we ready to release?

Yes ... I will tag with sd3.0.2 this morning.

**Comment by leamas** [comment]
OK. I have announced the release.

Let's try to reuse and update this checklist when doing next release.

Now, let's hope 3.0.2 is not less than a week away so we can start working with master branch and 3.1.0.

@Rasbats: so much better being two. Thanks!

Closing
