### ISSUE TITLE
sdv3.0.2beta1  update-templates  process hangs on, not totally completeing.

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#395]
I found yesterday, when update-templates sdv3.0.2beta1   (I think that was what I used)
that after it completed, I then stayed in the CLI and git add and git commit the changes.
Then when I tried to push to my remote repos, it would not recognize my security keys.

Puzzled, I then closed the bash cli and there was some process that had not completed.
I reopened the bash cli and was then prompted to enter my key pw, this step was being skipped over.

I don't know what caused this.

**Comment by leamas** [comment]
This kind of report are sort of useless unless there is a way to reproduce it. Clearly, here is not enough information to even try.

sd3.0.2 is released so there is no point using the beta.

**Comment by rgleason** [comment]
Well, perhaps it will help if it happens again.
