### ISSUE TITLE
vdr_pi update  push to plugins/auto worked but 3 metadata failed.

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#396]
When I pushed to "prod"   everything built and deployed to CS  vdr-prod.
I had properly setup plugins/auto to receive the metadata files, but 3 were missed.
(2) raspbian and (1) msvc were missed, though they exist, and I don't know why

https://github.com/OpenCPN/plugins/pull/577

I then updated my local plugins/auto and pushed the 3 missing and then removed the older version and made a commit and pushed that to plugins/auto.

What if anything do I need to check to be able to have all metadata get to plugins/auto?
Any ideas why those 3 metadata would not deploy to git plugins/auto when the others are?

Thanks.

**Comment by leamas** [comment]
>Any ideas why those 3 metadata would not deploy to git plugins/auto when the others are?

First check is to look in the build logs and check the git-push step.   Fo example, if appveyor/msvc is missing, how does the git-push log entry look like in appveyor?

**Comment by rgleason** [comment]
Appveyor, I had entered the key name wrong. Fixed.

The raspbian seem to have been pushed.  Perhaps it was a glitch?
https://app.circleci.com/pipelines/github/rgleason/vdr_pi/210/workflows/5a25524e-aea2-4be7-b7a9-782943b56e2d/jobs/1720
```
Writing objects: 100% (4/4), 855 bytes | 855.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:rgleason/plugins.git
   32fde4c..ecafbaf  auto -> auto
Pushed metadata to branch auto at the rgleason/plugins.git repository

CircleCI received exit code 0

```

**Comment by leamas** [comment]
Now, this is git, so nothing is lost. You can hunt down the commits done by git-push in the auto branch. The basic idea is to checkout the auto branch, locate the commit(s) which adds the actual  metadata and then display it. This way, you can find out exactly what was pushed (and when) to auto. 

The details are in the last part of https://github.com/Rasbats/shipdriver_pi/issues/391#issuecomment-1008842393, it applies in the same way here.

**Comment by rgleason** [comment]
Found them in cloudsmith and commited to auto branch
https://github.com/OpenCPN/plugins/commit/bbdff632f7c5884bd5a5cffbb4413abb694be5d0

Then tried to get the cloudsmith sha several times with different names. Failure.
fcgle@Hesper MINGW64 ~/source/plugins (auto)
$ cmake -E sha256sum https://cloudsmith.io/~opencpn/rpos/vdr-prod/packages/detail/raw/VDR-v1.3.16_raspbian-10.tar.gz
https://cloudsmith.io/~opencpn/rpos/vdr-prod/packages/detail/raw/VDR-v1.3.16_raspbian-10.tar.gz: No such file or directory

Then found the sha in 
https://cloudsmith.io/~opencpn/repos/vdr-prod/packages/detail/raw/VDR-v1.3.16-raspbian-10-tarball/v1.3.16/#metadata

Checksum (SHA-256)   
ffaa997e80d3e11a9af551dbecd74dda3ca2923f0012c2127d51f57fb2c19611

The metadata file has
 <tarball-checksum> ffaa997e80d3e11a9af551dbecd74dda3ca2923f0012c2127d51f57fb2c19611 </tarball-checksum>

Which are the same. So that does not really answer why the metadata files failed to get to auto branch.

**Comment by rgleason** [comment]
Should I just do the scripted update and try again after updating and getting the plugins/auto branch ready?

**Comment by leamas** [comment]
First: you could checkout out the auto branch like any other branch to check it. You can see the actual state  of the metadata/ directory, and using `git log --oneline -18` or so you can check the history.

The general bug hunt procedure:
- First check the build logs: does the git-push step complete?  Last part of the git-push message is something like 
```
To github.com:leamas/plugins.git
   6beead5..8c0a9a9  auto -> auto
``` 
which means that auto branch is updated to 8c0a9a9 . Remember that commit
- Then , in the OpenCPN/plugins clone check that commit:
      
      $ git fetch origin
      $ git show 8c0a9a9
This will display the actual changes to the metadata file. Are they sound?
- Check the metadata file using some editor, it lives in the metadata directory. If it's fine, you are sort of done.
- If it's still not what you expect: check the log for the metadata file. Assuming this is about o-charts-plugin-raspbian-armhf-10.xml we do

      $ git log --oneline  metadata/o-charts-plugin-raspbian-armhf-10.xml

This shows the changes done to this file, and should you get a hint to what happened to it after 8c0a9a9

Making manual updates to the auto branch is way too complicated. If you want to do manual changes, it much easier to commit into the master (or beta) branch directly in the plugins clone, of course after first having merged the other changes in auto.  But no-one else has had such a need, something is broken in your setup. 

> Should I just do the scripted update and try again after updating and getting the plugins/auto branch ready?

Yes. Make a new push triggered by source code changes, check the results and apply bug-hunting described above in case of problems.

**Comment by rgleason** [comment]
Alec, thanks, will follow this procedure if I find there are still troubles in the next update.
I've already removed auto and created it again.

**Comment by rgleason** [comment]
```
fcgle@Hesper MINGW64 ~/source/plugins (auto)
$ git pull origin auto
Enter passphrase for key '/c/Users/fcgle/.ssh/id_ed25519':
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 96 (delta 69), reused 38 (delta 24), pack-reused 12
Unpacking objects: 100% (96/96), 26.37 KiB | 57.00 KiB/s, done.
From github.com:rgleason/plugins
 * branch            auto       -> FETCH_HEAD
   7e1e5d9..487e2d6  auto       -> origin/auto
Updating 7e1e5d9..487e2d6
...
...

```

```
fcgle@Hesper MINGW64 ~/source/plugins (auto)
$ git log --oneline -25
487e2d6 (HEAD -> auto, origin/auto) 44e4edd: flatpak-x86_64: 1.3.19.0
780b783 44e4edd: darwin-wx315: 1.3.19.0
7debd6a 44e4edd: flatpak-aarch64: 1.3.19.0
38ef33d 44e4edd: msvc: 1.3.19.0
5190e6d 44e4edd: raspbian-armhf: 1.3.19.0
adebddf 44e4edd: android-armhf: 1.3.19.0
7602c3a 44e4edd: android-arm64: 1.3.19.0
3e0c05b 44e4edd: msvc: 1.3.19.0
da8c6ec 44e4edd: ubuntu-gtk3-x86_64: 1.3.19.0
850c4b9 44e4edd: debian-x86_64: 1.3.19.0
18a5264 44e4edd: ubuntu-gtk3-x86_64: 1.3.19.0
0a883e3 44e4edd: ubuntu-x86_64: 1.3.19.0
d8d0cb1 8630485: msvc: 1.3.18-beta
f899a99 8630485: darwin-wx315: 1.3.18-beta
dfb2e3e 8630485: raspbian-armhf: 1.3.18-beta
a3f84e0 8630485: android-armhf: 1.3.18-beta
b40d58b 8630485: android-arm64: 1.3.18-beta
75fa176 8630485: msvc: 1.3.18-beta
fa833e8 8630485: debian-x86_64: 1.3.18-beta
bf9507a 8630485: flatpak-aarch64: 1.3.18-beta
ca21a3f 8630485: flatpak-x86_64: 1.3.18-beta
9dcbcff 8630485: ubuntu-gtk3-x86_64: 1.3.18-beta
b76abf4 8630485: ubuntu-gtk3-x86_64: 1.3.18-beta
4421515 8630485: ubuntu-x86_64: 1.3.18-beta
7e1e5d9 (upstream/master) Merge branch 'master' of github.com:OpenCPN/plugins

```

So these are the metadata that got added.

1. 487e2d6 (HEAD -> auto, origin/auto) 44e4edd: flatpak-x86_64: 1.3.19.0
2. 780b783 44e4edd: darwin-wx315: 1.3.19.0
3. 7debd6a 44e4edd: flatpak-aarch64: 1.3.19.0
4. 38ef33d 44e4edd: msvc: 1.3.19.0
5. 5190e6d 44e4edd: raspbian-armhf: 1.3.19.0
6. adebddf 44e4edd: android-armhf: 1.3.19.0
7. 7602c3a 44e4edd: android-arm64: 1.3.19.0
8. 3e0c05b 44e4edd: msvc: 1.3.19.0
9. da8c6ec 44e4edd: ubuntu-gtk3-x86_64: 1.3.19.0
10. 850c4b9 44e4edd: debian-x86_64: 1.3.19.0
11. 18a5264 44e4edd: ubuntu-gtk3-x86_64: 1.3.19.0
12. 0a883e3 44e4edd: ubuntu-x86_64: 1.3.19.0

So as stated earlier,  auto never saw  raspbian-9.13 and raspbian-10 that did not get pushed to rgleason/plugins/auto for some reason.  commit to note:  It is missing raspbian-9.13 and raspbian-10 that did not get pushed to rgleason/plugins/auto for some reason.


I don't know where/how to find this.

```
The general bug hunt procedure:

    First check the build logs: does the git-push step complete? Last part of the git-push message is something like

To github.com:leamas/plugins.git
   6beead5..8c0a9a9  auto -> auto

```

Alec I don't really follow your suggestions here https://github.com/Rasbats/shipdriver_pi/issues/396#issuecomment-1025151929   I am not understanding what to do.

**Comment by rgleason** [comment]
The two missing metadata files are the ones from Drone
https://cloud.drone.io/rgleason/vdr_pi/73

This shows there is some problem with not finding  GIT_REPI.
It appears that the key I put in is not found. I will have to check this out further.

```
Checking raw package upload parameters ... OK
Checking VDR-v1.3.19_raspbian-9.13-armhf.tar.gz file upload parameters ... OK
Requesting file upload for VDR-v1.3.19_raspbian-9.13-armhf.tar.gz ... OK
Creating a new raw package ... OK
Created: opencpn/vdr-prod/vdr-v1319_raspbian-913-armhftargz-vlj (94uzD1341MjQ)
+ python3 ci/git-push
No $GIT_REPO found, cannot push to git repo.
```

Similar for the other missing one

```
Checking raw package upload parameters ... OK
Checking VDR-v1.3.19_raspbian-10-armhf.tar.gz file upload parameters ... OK
Requesting file upload for VDR-v1.3.19_raspbian-10-armhf.tar.gz ... OK
Uploading VDR-v1.3.19_raspbian-10-armhf.tar.gz:
Creating a new raw package ... OK
Created: opencpn/vdr-prod/vdr-v1319_raspbian-10-armhftargz-Ndm (scZEa9VjzaC5)
+ python3 ci/git-push
No $GIT_REPO found, cannot push to git repo.
```

**Comment by rgleason** [comment]
I think I've fixed those two issues, it was the GIT_REPO  key was mislabeled.

**Comment by leamas** [comment]
OK. In hindsight, the best of all sights, it seems that this should not have been that hard to find from the very beginning:

  - Some metadata file is misssing.
  - Check the build log for the plugin building the metadata, first bullet in my guide [above](https://github.com/Rasbats/shipdriver_pi/issues/396#issuecomment-1025151929).
  - From the log it's clear that git-push does not complete, it does not push anything.
  - Log contains an in my eyes clear error message that pinpoints why.

Still, hindsight is hindsight. And you seem to have it running,

**Comment by rgleason** [comment]
Thanks Alec. Yes I think the key is looking at the build logs. Your descrptiom is good.
