### ISSUE TITLE
Undefined Symbol on Ubuntu

### ISSUE THREAD

**Issue by CharlesParent** [Rasbats/shipdriver_pi#40]
Hello !
Just tried to install shidriver from opencpn repository:
`sudo apt-get install opencpn-plugin-shipdriver`

When opening OpenCPN the plugin is not visible and logs indicates:

`15:57:49.728 MESSAGE pluginmanager.cpp:1145 Checking plugin candidate: /usr/lib/opencpn/libShipDriver_pi.so
15:57:49.729 MESSAGE pluginmanager.cpp:2098 Plugin is compatible: true
15:57:49.729 MESSAGE pluginmanager.cpp:2161 PlugInManager: Loading PlugIn: /usr/lib/opencpn/libShipDriver_pi.so
15:57:49.729   ERROR dlunix.cpp:162 /usr/lib/opencpn/libShipDriver_pi.so: undefined symbol: _ZN11wxJSONValueaSEi
15:57:49.729 MESSAGE pluginmanager.cpp:2220    PlugInManager: Cannot load library: /usr/lib/opencpn/libShipDriver_pi.so 
`

Would somebody have an idea ?

**Comment by CharlesParent** [comment]
Tried to build shipdriver_pi from v2.4 tag, this time shipdriver is installed correctly

**Comment by Rasbats** [comment]
The official release of ShipDriver is v2.4. Working on the managed version at the moment. This uses a new method for producing the tarballs that is causing problems. There will be a number of changes to the master code that will not work as we test this method.

**Comment by CharlesParent** [comment]
Thank you for the information @Rasbats ! Do not hesitate if you need support for testing
