### ISSUE TITLE
Unable to create tarball on Windows

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#41]
Windows can use zlib but does not have gzip as part of the OS. For this reason ShipDriver does not compile standalone using Visual Studio 2017.

**Comment by leamas** [comment]
Seems there is undocumented build dependencies. Have you compared your setup with the setup in the appveyor script?

A log from last build on appveyour: https://ci.appveyor.com/project/leamas/shipdriver-pi/builds/35508488

Looking at the log and the build script it looks like nothing is installed before invoking cmake. However,  the virtual host obviously  has installed git (presumably the standard "Git for Windows" NSIS package).

Also, the cmake/Targets.cmake locates the tar program, finding it the git bundle. I *think* this is what you refers to as "gzip", it is used to repack the tarball.

Seems to boil down to what's exactly installed on the appveyor host which you hav't in place locally. Or?

BTW: Built packages are available at: https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable

**Comment by leamas** [comment]
I have added a debug statement to cmake. New  build logs at https://ci.appveyor.com/project/leamas/shipdriver-pi/builds/35509155

Specifically, we have `Using tar program: C:/Program Files/Git/usr/bin/tar.exe`. Which means that cmake is indeed using the tar program in the git bundle. Is the problem that that this does not exist in your local environment?
`

**Comment by Rasbats** [comment]
Thanks. Now fixed.
