### ISSUE TITLE
CMake 3.2 not found. All builds fail.

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#414]
Using update-templates sd3.0.3-beta1 and an update for otcurrent_pi builds fail.
[https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi?filter=all)

**Comment by Rasbats** [comment]
Package name was missing from Plugin.cmake. Trying a new build.

**Comment by leamas** [comment]
This seems to about the update from cmake 3.22.1 to 3.22.2. The new version is broken somehow. 

Please try the following patch:

```
diff --git a/ci/circleci-build-debian.sh b/ci/circleci-build-debian.sh
index 59ebb37..78c0d19 100755
--- a/ci/circleci-build-debian.sh
+++ b/ci/circleci-build-debian.sh
@@ -43,7 +43,7 @@ sudo apt install -q \
     build-essential libssl-dev libffi-dev
 
 python3 -m pip install --user --upgrade -q setuptools wheel pip
-python3 -m pip install --user -q cloudsmith-cli cryptography cmake
+python3 -m pip install --user -q cloudsmith-cli cryptography cmake==3.22.1
```

If it works, the corresponding fix needs to be applied to all failing ci/ scripts.

**Comment by leamas** [comment]
Upstream issue: https://gitlab.kitware.com/cmake/cmake/-/issues/23172

**Comment by Rasbats** [comment]
Adding the package name fixed the problem here. Something for the future but closing now.

**Comment by Rasbats** [comment]
Cmake 3.22.2 seemed to be used successfully.
[https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi/217/workflows/694cbc71-4062-4c2a-bb16-e08b11811578/jobs/2347](https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi/217/workflows/694cbc71-4062-4c2a-bb16-e08b11811578/jobs/2347)

**Comment by leamas** [comment]
Upstream issue closed. Admittedly, I was a bit quick to file it.

**Comment by leamas** [comment]
> Something for the future 

Not really. Just a mistake, we can't really create guards for such things.
