### ISSUE TITLE
Ubuntu builds struggling with CircleCI

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#415]
First otcurrent_pi had problems, now sar_pi is struggling.
Seems that downloading the updates causes the issue.
Both with sd3.0.3-beta1, but this may not be related.

[https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/otcurrent_pi?filter=all)
[https://app.circleci.com/pipelines/github/Rasbats/sar_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/sar_pi?filter=all)

**Comment by leamas** [comment]
This has seemingly nothing to do with our code, it's a `apt update` which has problems retrieving the metadata files. For now, let's assume it's a temporary problem.

**Comment by leamas** [comment]
@rasbats: still a problem? shipdriver builds fine for me

**Comment by leamas** [comment]
@Rasbats: ping?

**Comment by Rasbats** [comment]
The builds worked after leaving it for a day. Now closing.
