### ISSUE TITLE
Which tagged template to use now?  for Logbook?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#417]
sd3.0.3-beta1  or  sd3.0.2 ?

**Comment by leamas** [comment]
you can try sd3.0.3-beta1 

We can't have it like this. Issues is not a support channel. Keep open until I'm back

**Comment by rgleason** [comment]
Do you want me to use email?

**Comment by leamas** [comment]
Definitely not. 

Let's breath some life into Zulip. After all, it's a tool which has some actual potential in this usecase.

**Comment by rgleason** [comment]
Ok Zulip.  Close?

**Comment by leamas** [comment]
yes
