### ISSUE TITLE
Using sd3.0.3 template in aisRX_pi - flatpak issue

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#425]
In the .yaml file in ShipDriver sd3.0.3, line 38, branch master is used. But the aisRX repo is using main (the new default branch name).

This created an error:

[https://app.circleci.com/pipelines/github/Rasbats/aisRX_pi/12/workflows/9123ff72-a494-40cc-bd21-99f6bf2ae11c/jobs/128](https://app.circleci.com/pipelines/github/Rasbats/aisRX_pi/12/workflows/9123ff72-a494-40cc-bd21-99f6bf2ae11c/jobs/128)

Changed branch master to main and the flatpak build completed correctly.

**Comment by leamas** [comment]
hm, right.  But besides rectifying the branch tag in the Flatpak yaml manifest there is not much to do, this is not a template thing. The manifest is local and not updated by update-templates etc. And whether a plugin uses the branch `main'  or `master' is a local plugin issue.

Ergo: We should not take any specific action with the templates here, just confirm that a plugin which uses for example `main' needs to adjust this also in the Flatpak manifest.

Which boils down to that I think this issue should be closed without any particular actions. 

Thoughts?

**Comment by Rasbats** [comment]
The error messages in CircleCI enable the user to detect the problem. Closing.
