### ISSUE TITLE
Template circleci-build-flatpak-wx31.sh failed to build

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#426]
I today updated templates from Shipdriver. Now i selected the last beta, sd3.1.0-beta1, maybe not wise?
Anyhow now tested..
This [one linked here ](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/44/workflows/b5dce741-5ff3-412a-9383-9197b7ca0f64/jobs/460)failed.
The error here as well:

```
#!/bin/bash -eo pipefail
ci/circleci-build-flatpak-wx31.sh
ls: cannot access 'org.opencpn.OpenCPN.wx31.Plugin.*.yaml': No such file or directory
Exited with code exit status 2
CircleCI received exit code 2

```
The other was OK. Thanks for the handy templates!
Håkan

**Comment by leamas** [comment]
> Now i selected the last beta, sd3.1.0-beta1, maybe not wise?

No, not wise. This is the first beta for upcoming 3.1, far from tested. Please use the latest stable release 3.0.3.

Overall, please talk to us before using beta releases. There are occasions when this is the correct choice, but to be honest only Mike an I knows when. The recommended usage is always latest stable release i. e. , latest non-beta release.

**Comment by Hakansv** [comment]
leamas, Mike..
OK used sd3.0.3 instead. Works fine.
Thanks

**Comment by Hakansv** [comment]
I'll test the new version 3.1.0 when time. Other prios for the moment, sorry.

Thanks for the link to a more suitable forum for PM questions/issues. Very good. Will attempt soon.

Håkan

**Comment by leamas** [comment]
> Thanks for the link to a more suitable forum for PM questions/issues. Very good. Will attempt soon.

As I said earlier, I need your email address to be able to invite you to the forum first. See above

>  Other prios for the moment, sorry.

No needs for apologies...
