### ISSUE TITLE
PM templates does not include tarballs for OpenPlotter versions

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#428]
For info:
I'm using shipdriver templates for ais-vd_pi.
No tarballs are built for Ubuntu 18.04 nor Ubuntu 20.04
All those using Openplotter won't get the plugin. See shots from PM and Openplotter default installer.
Since o-charts are working on these system I can for sure copy some scripts from there to solve it but it may be Shipdriver's templates need an update?
Thanks
Håkan

![bild](https://user-images.githubusercontent.com/7202854/157045974-2c4cb357-be63-4348-a1cc-fe4730bf78de.png)

![bild](https://user-images.githubusercontent.com/7202854/157045998-99d96bf7-7e53-48b0-a67f-02b75c8fbdc9.png)

**Comment by leamas** [comment]
Assuming you are on shipdriver stable release sd3.0.3.

3.0.3 does not build ubuntu plugins for armhf, it builds Debian. The bullseye/armhf plugins are (should be?) accepted on focal as long as there are no compatibility settings. These are built by circleci and should not be a problem (?)

As for buster/armhf which is used on bionic, these are built on drone.io. I'm aware of the problems  using this builder, and it is to be dropped in upcoming 3.1.0 (which also contains many other changes). However, 3.1.0 is still not ready for prime time.

Can you live with the bionic  problem for a week or two so we can test 3.1.0 first? 

For focal: check your circle ci build logs, look for raspbian-bullseye. Likewise, check your cloudsmith repo for raspbian-11, this is the plugin used on focal.

**Comment by Hakansv** [comment]
Something is for sure wrong by me but I try the best.
Now I saw that despite a tagged version it was build to the alpha catalog?
I may tag by another method next time?

**Comment by leamas** [comment]
> Now I saw that despite a tagged version it was build to the alpha catalog?

Can you link to the build logs?

**Comment by Hakansv** [comment]
I upload a new Shipdriver template and it seems all are built.
So I may have to tweak my Tag method for next prod. release.
Thanks
