### ISSUE TITLE
arm.medium builds fail on CircleCI

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#435]
Getting this for the free circleci account. Something new?
This job has been blocked because resource-class:arm.medium is not available on your plan

The circleci logs are here:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi?filter=all](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi?filter=all)

**Comment by leamas** [comment]
This has been resolved on the CircleCI side. Rebuilding master a. k. a. sd3.1.0  works fine for me again.

The CircleCI (free!) support is actually amazing.

I think this bug should be closed.

**Comment by Rasbats** [comment]
Working here. Closing.
