### ISSUE TITLE
update-templates: drone builds are not disabled.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#443]
update-templates does not remove _.drone.yml_ despite that the drone builder is not used.  This leads to build errors for some users which have an account on drone.io

The work-around is to remove the file manually.

Although there is a PR, let's leave this bug open until next release for visibility.

**Comment by rgleason** [comment]
Now I recall that that was the issue with Logbook!!!   I ended up disabling the drone setup for logbook.  Very sorry I did not recall that problem.

**Comment by leamas** [comment]
Fixed in f2cc77bb65 and bb1604d

**Comment by rgleason** [comment]
That one made me loose almost 1/2 day.

**Comment by leamas** [comment]
Removing drone completely is a breaking change and thus needs to wait to next major release, at least 3.2.0.

However, we could probably avoid re-installing drone in update-templates also in 3.1.4, assuming that no new users will add drone configurations. That is, cherry-pick bb1604d4  into 3.1.4.

**Comment by leamas** [comment]
Fully fixed in master, partly fixed in released 3.1.4
