### ISSUE TITLE
Drop windows 7 and move to VS2019

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#450]
As concluded in https://github.com/OpenCPN/OpenCPN/issues/2633: It's time to drop the Windows 7 support and use VS2019 to build.

**Comment by Rasbats** [comment]
Happy with this. Intend moving to VS2019 as the default tool for plugins I work with.

**Comment by leamas** [comment]
We have moved to VS2022, and we will keep compatibility for Win 7 for now. Closing.
