### ISSUE TITLE
3.1.4-beta1 testing

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#455]
I have tested 3.1.4-beta1 with "my" plugins radar_pi and o-charts_pi. Looks good so far.

@Rasbats : Ping? Are you there? Could you possibly also test a plugin or two with the beta?

**Comment by Rasbats** [comment]
>Ping? Are you there? Could you possibly also test a plugin or two with the beta?

Yes to both. Home until the middle of July. Keeping Zulip open for conversation.

**Comment by leamas** [comment]
Grat to hear from you! 

Let's  stick to zulip. Closing this.
