### ISSUE TITLE
Time to update VDR and Logbook?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#456]
I know Alec sent out a note sometime ago, but I was pretty busy and I am a little sketchy on process here so bear with me.
What version do I use for the automatic?

After the update, I've found it is just easier to do my usual thing to get it into opencpn/plugins, otherwise things go awry.

**Comment by leamas** [comment]
This is not an issue. Closing.

**Comment by rgleason** [comment]
I believe we do not have a full set of plugin  metadata and tarball for all the versions, that is why I wrote that so long ago.  Perhaps it should be updated now before the next version.
