### ISSUE TITLE
flatpak arm64 fails to build

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#457]
Ran a small test to see if ShipDriver (master) still building correctly. flatpak arm64 failed:

[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/785/workflows/fb926481-1c3f-4203-8705-57d57bf4a562/jobs/6498](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/785/workflows/fb926481-1c3f-4203-8705-57d57bf4a562/jobs/6498)

**Comment by leamas** [comment]
+ flatpak install --user -y --noninteractive flathub org.freedesktop.Sdk//20.08
    error: Nothing matches org.freedesktop.Sdk in remote flathub

hm... are you sure this is not some transient error? The error message above seems weird. I can list the contents of flathub using `flatpak  --user remote-ls flathub` and sees that that org.freedesktop.Sdk//20.08 is definitely there. On  a sidenote, anything else would be a surprise.

Perhaps just try a rebuild?

**Comment by Rasbats** [comment]
Tried one rerun without success. I will try again.

**Comment by Rasbats** [comment]
Failed again.

**Comment by Rasbats** [comment]
And failed again. Is `flathub org.freedesktop.Sdk//20.08` (//) valid?

**Comment by Rasbats** [comment]
Rerun failed this morning.

**Comment by leamas** [comment]
NO need to try again. I'll see when I can find some time, stay tuned.
