### ISSUE TITLE
flatpak-arm64 not building

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#459]
Freedesktop SDK 20.08 is EOL. Still used in OpenCPN builds but why is it not working for the SD3.1.4 template and SD builds?
[https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi](https://app.circleci.com/pipelines/github/Rasbats/JavaScript_pi)

**Comment by leamas** [comment]
This is part of #458. I'm just about to start working on it but, believe it or not, time constraints.
