### ISSUE TITLE
sd3.2.0-beta4 using old msvc setup

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#477]
For a test I used update-templates sd3.2.0-beta4.
I noticed it changed PluginSetup.cmake to go back to previous msvc. Is that intentional?
After update:
```
 elseif (MSVC)
-  set(plugin_target "msvc-wx32")
+  set(plugin_target "msvc")
   if (CMAKE_SYSTEM_VERSION)
```

**Comment by Rasbats** [comment]
Thanks. Same here for ShipDriver. But the tarball made is _msvc-wx32_. I think _appveyor.bat_ sorts this out.
Which plugin are you building? Does it work?
Fighting MacOS plugin woes at the moment.

**Comment by Hakansv** [comment]
The one I have is ais-vd_pi
I haven't yet tried a build to github / ci only local. And if I'm correct the local build use PluginSetup.bat?

**Comment by Rasbats** [comment]
First step will be to update _opencpn-libs_. See the README in that folder.

**Comment by Rasbats** [comment]
Step 2: win_deps.bat wx32 to populate the cache.
Step 3: I am using a batch file:
[leamas.shipdriver_pi.bat.pdf](https://github.com/Rasbats/shipdriver_pi/files/10219387/leamas.shipdriver_pi.bat.pdf)
Remove the .pdf!
Replace _shipdriver_  in the _.bat_ with your own plugin name.

**Comment by Rasbats** [comment]
I have added another tag for update-templates : _sd3.2.0-beta5_. I will test this with some other plugins tomorrow. Waiting for a decision for the MacOS builds.

The difference between _beta4_ and _beta5_ only affects the MacOS.

**Comment by Rasbats** [comment]
Now using sd3.2.0-beta6 for testing with other plugins. Hope this can be the last before we make a release sd3.2.0.

**Comment by Rasbats** [comment]
@leamas : _PluginSetup.cmake_ has:
 ` set(plugin_target "msvc")`
Not: 
 ` set(plugin_target "msvc-wx32")`
 Is this correct? It does not seem to affect the final tarball.

**Comment by Rasbats** [comment]
Same for the MacOS target:

```
elseif (APPLE)
  set(plugin_target "darwin-wx315")
  set(plugin_target_version "10.13.6")
```

**Comment by leamas** [comment]
These are basically obsolete, the basic message is to use OCPN_TARGET_TUPLE to get it right. This is what we do in the CI builds.

That said, darwin-wx315 is plain wrong and should be fixed. And changing msvc to msvc-wx32  should not hurt, please feel free do to these changes.

**Comment by leamas** [comment]
I found another corner case in PluginSetup.cmake. No time for a fix now, but should be fixed before release. It is about using _ubuntu-gtk3_ in OCPN_TARGET_TUPLE_ which will become _ubuntu-gtk3-gtk3_

**Comment by Hakansv** [comment]
> These are basically obsolete, 

Well it's used for local (Win) builds:
set(plugin_target "msvc-wx32" gives:
ais-vd-1.8.0+2212161154.00e031e_msvc-wx32-10.0.19044-win32.tar.gz
set(plugin_target "msvc" obviously gives:
ais-vd-1.8.0+2212161154.00e031e_msvc-10.0.19044-win32.tar.gz
So we keep "PluginSetup.cmake" updated as well?

**Comment by leamas** [comment]
Yes, unless you use -DOCPN_TARGET_TUPLE which always is the preferred way -- it gives you exact control. That said, we should update PluginSetup.cmake for the default case, I'm sure @Rasbats  will take care of this.

**Comment by Hakansv** [comment]
I'm the novice here and have so far used this method to build.
cmake --build . --target tarball --config RelWithDebInfo
Please advice how to use -DOCPN_TARGET_TUPLE if of any advantage.

**Comment by leamas** [comment]
See the [manual](https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/od-compile-cmake.html#_explicit_target_specificationocpn_target_tuple) This is about opencpn, but sd works the same way.

**Comment by Rasbats** [comment]
Corrections for target names made. Tag sd3.2.0-beta6 has been re-made.

**Comment by leamas** [comment]
Time to close?

**Comment by Hakansv** [comment]
Could be. Haven't yet tested but actions seems good.
