### ISSUE TITLE
Using update-templates sd3.2.0-beta5

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#478]
build-conf.rc (New file) not added to repo root files.
Added by hand.

**Comment by Rasbats** [comment]
Needed to add patch for matrix.h (wxWidgets) in _build-deps_ directory.

**Comment by leamas** [comment]
build-conf.rc: This is a typo in update-templates, see below. Can you fix it?
```
index 1b6f62e8..249cfcd5 100755
--- a/update-templates
+++ b/update-templates
@@ -192,7 +192,7 @@ grep -q wxwidgets build-deps/macos-deps || \
 
 # Check for files/dirs which are private, but should be copied on first run.
 for f in  \
-    config.h.in build-deps build-conf.sh libs build-deps/macos-cache-stamp
+    config.h.in build-deps build-conf.rc libs build-deps/macos-cache-stamp
 do
     if test -e $f; then continue; fi
     git checkout $source_treeish $f

```

**Comment by Rasbats** [comment]
>Can you fix it?

Will fix this morning.

**Comment by leamas** [comment]
I pushed the change, need it for further work. make a git pull or git rebase.

**Comment by leamas** [comment]
update-templetas adds wxwidgets to build-deps/macos-deps. This is wrong, remove it for now.

**Comment by Rasbats** [comment]
>update-templetas adds wxwidgets to build-deps/macos-deps. This is wrong, remove it for now.

Done. Please let me know when you are ready for another beta tag. This is needed to test other plugins.

**Comment by Rasbats** [comment]
Tag beta6 now added. Closing this issue.
