### ISSUE TITLE
Flatpak error using sd3.2.1

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#486]
I received build errors for the [ais-vd builds.](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/59/workflows/e48dbb83-8ad3-4e3d-9568-23b84b2ad5d9)
Since Flatpaks didn't found the server I've rerun it a couple of times wo change.
I run it again a day or two later and still the same error
Is there anything I can do or does sd3.2.1 need an update.?

For the Flatpaks:
Error: Failed to install org.opencpn.OpenCPN: While pulling app/org.opencpn.OpenCPN/x86_64/beta from remote flathub-beta: Server returned status 404: Not Foundk

**Comment by Rasbats** [comment]
Updating Photolayer a couple of my flatpak builds failed on first pass. After a re-run they built, but they did take a very long time.

**Comment by leamas** [comment]
This is actually not trivial. Posted a [message](https://lists.freedesktop.org/archives/flatpak/2023-January/002284.html) on the flatpak list, let's see what happens.

**Comment by Rasbats** [comment]
Reran the Flatpak builds using SSH. These failed. But the next runs with the merge for Android keys have passed ok. All OS built.

**Comment by leamas** [comment]
See the [reply] (https://lists.freedesktop.org/archives/flatpak/2023-January/002286.html) in the mailing list.  It is about a temporary problem  which now is fixed.  Closing this, please reopen if need be.
