### ISSUE TITLE
Missing key for Android armhf using sd3.2.1

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#487]
I received build errors for the [ais-vd builds.](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/59/workflows/e48dbb83-8ad3-4e3d-9568-23b84b2ad5d9)

The missing key for one Android may need some tweaks?
For Android armhf:

W: GPG error: https://packages.cloud.google.com/apt cloud-sdk-buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://packages.cloud.google.com/apt cloud-sdk-buster InRelease' is not signed.

**Comment by Rasbats** [comment]
Same issue with this mornings build of ShipDriver.
