### ISSUE TITLE
Shipdriver Message

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#488]
Hit "start"
Message:  "Right click and chose the vessel start" is mode restrictive. You cannot do it. You have to close the message. Then when you hit start it asks same question again. Vicious cycle.
What are we actually supposed to do?
Thanks.

**Comment by Rasbats** [comment]
Agree ... the context message should not appear in the list until the SD dialog is displayed.

**Comment by leamas** [comment]
Fix in latest release 3.2.2 and also in master. Time to close?

**Comment by Rasbats** [comment]
Not yet in the master catalog. No time to do this at present.

**Comment by Rasbats** [comment]
Now in the master catalog. Closing.
