### ISSUE TITLE
SD3.2.2 failed for all bookworm

### ISSUE THREAD

**Issue by Hakansv** [Rasbats/shipdriver_pi#490]
I tried sd3.2.2 but most failed.
The result is [here](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi?branch=master)

I run update-templates sd3.2.2

In the end this comment was shown:  (what's 'update --init'?)
Submodule path 'opencpn-libs' not initialized
Maybe you want to use 'update --init'?
Create or update cmake/TemplateVersion
[master cdf8e2d] cmake: Update TemplateVersion to ff0ae9c
 1 file changed, 5 insertions(+)
 create mode 100644 cmake/TemplateVersion

**Comment by leamas** [comment]
The error messages are quite clear: `warning: Could not find remote branch auto to clone`, bad things happening after that.

You have set up your repo to use the automatic upload of metadata, but there is not auto branch. You need t create that as described in the [manual](https://opencpn-manuals.github.io/main/AlternativeWorkflow/InstallConfigure/GithubPreps.html)

**Comment by Hakansv** [comment]
OK, I deleted that after tried the "updatePluginGithub.bat" which ended up in close to 40 merge conflicts so I thought next time I'll start clean if I'd try that batch file again. ?? (Just a try)

**Comment by leamas** [comment]
never heard of that bat file. But just removing the auto branch and then creating it again from scratch is perfectly fine as long as you don't have pending changes in the branch. I only use it occasionally myself, and then usually follow this scheme 
  1. remove auto
  2.re-create auto
  3. make a build
  4. clean up metadata
  5. merge auto
  6. make a PR

**Comment by Hakansv** [comment]
Sorry about the bat file reference. It was my own executing the (somewhere) suggested  method to transfer metadata from auto to master. Don't mind. 
When auto branch was present all previous builds worked.
The three new? bookworm failed though. I presume you have tested these so it would be me again? [Link:](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi?branch=master)

**Comment by leamas** [comment]
this is about build-deps/control, and indirectly a bug in update-templates. Reopening  + new title

**Comment by leamas** [comment]
You should be able to  work around this for now  by editing _build-deps/control_ and change the wxwidgets deps so they look like this (copied from shipdriver):
```
 base-files (>=11) | libwxgtk3.0-dev,
 base-files (>=11) | libwxgtk3.0-0v5 | libwxgtk3.0-0,
 base-files (>=10) | libwxgtk-webview3.0-dev,
 base-files (<< 10) | libwxgtk3.2-dev | libwxgtk3.0-gtk3-dev,
 base-files (<< 10) | libwxgtk-webview3.2-dev | libwxgtk-webview3.0-gtk3-dev,
```

The other lines in *build-deps/control* should be left as-is, just replace the lines containing *libwxgtk*

As a first step, can you do this so we can verify my theories? Next step would be to add a fix to update-templates so it's done automatically, but this is another story.,

What makes this somewhat tricky is that *control* by definition is a local file which can and should be modified by each plugin according to it's needs. Thus we cannot just copy the one from shipdriver even if would work in most cases.

**Comment by Rasbats** [comment]
See Zulip note:
Small problem ... using the tag sd3.2.2-beta1 the Bookworm artifacts are sent to CS shipdriver-alpha.
Log is here:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/871/workflows/1455f3d7-2b1d-4153-a26d-b5bacf1a28d9/jobs/7471](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/871/workflows/1455f3d7-2b1d-4153-a26d-b5bacf1a28d9/jobs/7471)

**Comment by Hakansv** [comment]
@leamas 
Now the control looks like below and then sd3.2.2 works for all system.
So far only tested wo tag so alpha. What they are called in CS I don't know. "...-12-..."?
Thanks
```
Source: opencpn
Build-Depends: debhelper (>= 9),
 base-files (>>8) | mesa-common-dev,
 base-files (>>8) | libgl1-mesa-dev,
 libgtk2.0-dev,
 libjsoncpp-dev,
 libtinyxml-dev,
 libunarr-dev | base-files (<< 11), 
 base-files (>=11) | libwxgtk3.0-dev,
 base-files (>=11) | libwxgtk3.0-0v5 | libwxgtk3.0-0,
 base-files (>=10) | libwxgtk-webview3.0-dev,
 base-files (<< 10) | libwxgtk3.2-dev | libwxgtk3.0-gtk3-dev,
 base-files (<< 10) | libwxgtk-webview3.2-dev | libwxgtk-webview3.0-gtk3-dev,
 libcurl4-openssl-dev,
 python3-pip,
 python3-setuptools,
 python3-wheel
```

**Comment by leamas** [comment]
Many thanks!

First step will be to make a note of this in the 3.2.2 release message. I will look into fixing update-templates later.

Yes, Bookworm is the same as Debian-12.

**Comment by Hakansv** [comment]
OK, thanks. So this i ready

**Comment by leamas** [comment]
This really needs to be open until we have a fix for the root cause in update-templates.

See also: https://github.com/OpenCPN/OpenCPN/discussions/2932

**Comment by Hakansv** [comment]
Radar_pi is now updated to SD 3.2.2 but still fails on [Bookworm](https://app.circleci.com/pipelines/github/opencpn-radar-pi/radar_pi/333/workflows/f6ca833c-7877-4bfd-a49e-acde22c8d0d7/jobs/2219)
I saw a sd3.2.3-beta. Is that to address that issue and we should await further work?

**Comment by Hakansv** [comment]
When Kees used sd3.2.3-beta1 all Bookworm was nicely built. 
Are we happy and time to close this issue?

**Comment by Rasbats** [comment]
My Bookworks are building fine with sd3.2.3-beta1. I reckon time to close.
