### ISSUE TITLE
Legacy wx3.0 builds

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#500]
There is a need to restore the ability to compile for wxWidgets v3(Not Darwin)/3.1.5 (Darwin) and add them to the master catalog. In particular the target darwin-wx315 is not recognised for adding metadata to the master catalog.

This will be needed if we want to rebuild versions for OpenCPN 5.6.2 and earlier. Cloudsmith may have deleted them if the lifecycle has been exceeded. 

Can sd3.1.x templates handle this or does OpenCPN/plugins need a fix? 

[https://github.com/OpenCPN/plugins/issues/815](https://github.com/OpenCPN/plugins/issues/815)

**Comment by leamas** [comment]
>  In particular the target darwin-wx315 is not recognised for adding metadata to the master catalog.

This is really a issues about opencpn/plugins, see https://github.com/OpenCPN/plugins/issues/818.

However, the validating just gives  warning messages. If you create a PR with such messages it's just to inform Dave about the situation and he will merge it anyway.  So, I don't really see if this is a problem.

> Can sd3.1.x templates handle this or does OpenCPN/plugins need a fix?

Dunno, we will need to make a run.  But we very likely need to at least update repository signing keys.

**Comment by leamas** [comment]
I made a PR for Tony: https://github.com/antipole2/JavaScript_pi/pull/52.  This is more or less what needs to be done with 3.1 to keep it building, I guess.

**Comment by Rasbats** [comment]
Understood. Closing.
