### ISSUE TITLE
Windows Cross-compilation from Linux

### ISSUE THREAD

**Issue by CharlesParent** [Rasbats/shipdriver_pi#52]
Hello,

I was wondering if it was possible to cross-compile this plugin from linux to Windows target.

Is there a way to do so or should I compile this project on Windows ?

**Comment by Rasbats** [comment]
Alec Leamas and myself are playing with the master branch code at the moment.

The easiest way would be to compile on Windows with code from the legacy branch and make a legacy installer.

**Comment by Rasbats** [comment]
CharlesParent...

See from GitHub you are an embedded software engineer. A long shot but do you read circuit diagrams with IC incorporated? This relates to another OpenCPN project.

Mike

**Comment by CharlesParent** [comment]
Hello Raspbats !
Thank you for  the information, I will setup a windows environment then !

Also I did read circuit diagrams back in the days, I can take a look if it can help !

**Comment by Rasbats** [comment]
[Down-Under Depth Sounder.pdf](https://github.com/Rasbats/shipdriver_pi/files/5353145/Down-Under.Depth.Sounder.pdf)

Just wondering if, with modern IC this whole thing could be simplified and the output translated to NMEA. 
Probably better to think about a transducer pushing out NMEA so please don't waste too much time on this.

**Comment by leamas** [comment]
> I was wondering if it was possible to cross-compile this plugin from linux to Windows target.

Yes and no.

As-is, the plugin can be built using the mingw toolchain, this is part of the current ci setup. However, this cannot be used by the regular OpenCPN packages which are build using Visual Studio (MSVC) tools.

Then again, there are OpenCPN mingw builds available but they are not that much used. Overall, the mingw stuff for the moment is a solution in search of a problem.

**Comment by leamas** [comment]
If you want to test, there is a 5.2.0 OpenCPN build available at https://cloudsmith.io/~alec-leamas/repos/opencpn/packages/detail/opencpn-mingw_520-211421144d956e178_setupexe-MJ6/

A version of the shipdriver plugin is available at  https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/detail/raw/ShipDriver-mingw-10-tarball/2.5.39+3160.31791ce/. This is built using local patches yet not merged into master.

To test: download the plugin tarball and use the "Import Plugin" function in the Settings | Plugins tab.

**Comment by CharlesParent** [comment]
Thank you for your help !
I have been able to compile it on a Windows computer following the instructions in OpenCPN developer's manual :)
