### ISSUE TITLE
Build problems with bullseye-armhf and bookworm-armhf

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#520]
sd3.2.4-beta1 failed to build for ShipDriver *bullseye-armhf* and *bookworm-armhf*:
https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/914/workflows/93f316de-85bb-4001-bdc8-566199a8394e
_bullseye_ built with a re-run but _bookworm_ failed to build after 2 re-runs.
Only change made to the files was to update the changelog.

**Comment by Rasbats** [comment]
Same is happening using sd3.2.4-beta1 for EarthExplorer_pi.
[https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/23/workflows/1dbde07d-04a1-47b7-8b3b-ad8aba3856bf](https://app.circleci.com/pipelines/github/Rasbats/EarthExplorer_pi/23/workflows/1dbde07d-04a1-47b7-8b3b-ad8aba3856bf)

**Comment by leamas** [comment]
hm... The logs indicates some problem in the dependencies for the cloudsmith python script. However, when I rebuild EarthExplorer_pi (current master) it works just fine. One possible explanation would be that the underlying python problem already is solved somehow.

Could you please re-run the EarthExplorer build once again, so we can reassert the status of this problem?

**Comment by Rasbats** [comment]
With re-run the build-bullseye-wx32-armhf has now failed with the same error. bullseye-armhf and bookworm-armhf built ok.

```
File "/home/circleci/.local/lib/python3.9/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/circleci/.local/lib/python3.9/site-packages/urllib3/contrib/__init__.py)

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by leamas** [comment]
This is an error in the `cloudsmith`  python program, or rather it's dependencies. It's probably nothing we can do mauch about ourselves.

The strange thing is that I cannot reproduce this. I do get another error when rebuilding shipdriver, but it's probably unrelated.

**Comment by leamas** [comment]
I can now reproduce it when rebuilding shipdriver. This is a bug in the cloudsmith program

**Comment by leamas** [comment]
Have filed a ticket at the cloudsmith site. They don't respond with any ticket info whatsoever, so I guess this might not lead to anything useful.
