### ISSUE TITLE
buildwin/win_deps.bat using wxWidgets 3.2.1

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#523]
Not critical but should win_deps.bat build a cache of wxWidgets 3.2.2 files?

**Comment by leamas** [comment]
You mean that it should download 3.2.2  rather than 3.2.1?

Yes, it should

**Comment by Rasbats** [comment]
@leamas Made an edit to branch 3.2 to use wxWidgets 3.2.2.1. When you have time could we move to this for the other OS, as appropriate? Needs an update to your wxWidgets repo I think.

**Comment by Rasbats** [comment]
Ok ... seen the commit of the work by Kees. Could this be cherry-picked to branch 3.2?

**Comment by leamas** [comment]
Right... the note was here. Sailing, will hopefully have some time beginning of next (this?) week.

**Comment by leamas** [comment]
See also #510

**Comment by leamas** [comment]
Fixed in 8735702e . Closing
