### ISSUE TITLE
Flatpak builds fail for sd3.2.4-beta2

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#526]
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/920/workflows/ac023672-7ad4-44d5-aded-f3f050893786](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/920/workflows/ac023672-7ad4-44d5-aded-f3f050893786)

Tried one re-run, which failed. Will try another later today.

**Comment by Rasbats** [comment]
Builds fine with the master but could you cherry pick into v3.2 branch. The beta2 template showed up the problem.

**Comment by leamas** [comment]
Done. Note that changelog refers to yet not existing beta3

**Comment by leamas** [comment]
No, but I need to push an d forgot that. Sorry, done now.

**Comment by Rasbats** [comment]
Thanks.
