### ISSUE TITLE
Distress Alerts

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#528]
Hi Mike,

As mentioned in the AIS SART alert discussion (https://www.cruisersforum.com/forums/f134/ais-sart-alerts-275727.html#post3776784), perhaps consider adding AIS SART/MOB/EPIRB and DSC Distress Alert and Distress Alert Relay sentences to the plugin. Could potentially make it useful for distress response training ?

The DSC Distress alerts are easy, just NMEA 183 text sentences. 
Eg. $CDDSC,12,5030559800,,05,00,2380814430,1143,,,S,
where 12 is the Format Specifier denoting Distress, 503055980 is the MMSI of the vessel in distress (add an extra zero to make it 10 characters long), 05 means sinking, 2380814439 is the position (2 means South East quadrant therefore, 38 08 S, 144 30 E) and 1143 is the time,

The AIS stuff a tad harder because of the 6 bit stuff, but seeing as though you've already implemented AIS, it's just a matter of generating an AIS Type 1 message, using the correct MMSI prefixes (970 is a SART, 972 is a MOB and 974 is an EPIRB), and for the Nav Status  a value of 14 (Active).

Regards, 
Steve.

**Comment by Rasbats** [comment]
Thanks Steve ... this is pretty near the top of the list of things to work on.
Mike

**Comment by Rasbats** [comment]
Implemented just the SART so far. Tarballs are here:
[https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/](https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/)
Have not used Message 14. It would only seem important of the output was used with another device.

Using the v3.2-alarms branch of the ShipDriver repo.

When the SART is disabled it leaves the icon on the display and in the AIS target list and an alarm sounds. It should disappear after the minutes set in the options, I think. How to end the distress? TBC

**Comment by Rasbats** [comment]
I think I need to send a message 1 with the nav status set other than 14 when the SART is deactivated.

**Comment by Rasbats** [comment]
nav status of 15 (undefined) puts the SART into testing mode and stops the alarm. SART Symbol remains but AIS tx stops and AIS indicator (yellow line) removed depending on target lost time set in preferences.  Now in the alpha tarball.

**Comment by TwoCanPlugIn** [comment]
Hi Mike, sounds correct.

You raise an interesting question , possibly best addressed by OpenCPN.

What happens in real life with an active AIS SART?
1. They get rescued, turn off device and it automatically is deleted from O after the timeout period (or is persisted as a lost target)
2. They don't get rescued. Device runs out of battery and stops transmitting. Should O persist the target?

I personally have no idea what happens when an active AIS SART is deactivated/switched off?

I wonder if the AIS SART manufacturers could enlighten us or whether there is guidance within the relevant IMO ECDIS standard?

Ultimately I think O needs an alarm/alert log to persist all distress & emergency events.
________________________________

**Comment by Rasbats** [comment]
[https://continuouswave.com/whaler/reference/DSC_Datagrams.html](https://continuouswave.com/whaler/reference/DSC_Datagrams.html)
Cannot find nmea for implementing a DSC distress relay message?
MOB is now dropped where the person went overboard.
DSC distress alert implemented, with the ability to cancel.
The packages are here again:
[https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/](https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/)

**Comment by TwoCanPlugIn** [comment]
Cannot find nmea for implementing a DSC distress relay message?

It's similar to the DSC Distress Alert.

Here's an example sentence.


CDDSC,16,2350763930,12,12,00,2380814428,1800,5031105200,05,S,E*65

The values in this Distress Relay sentence should be interpreted as:
Format Specifier 16 - All Ships
MMSI Address - 235076393 (This is the MMSI Address of the relay vessel)
DSC Category 12 - Distress
First Telecommand 12 - Distress Relay
Type of Communications 00 - F3E/G3E, All modes TP, 2380814428 is the latitude/longitude ie 2= SE quadrant, 38 08 S 144 28 E, 1800 is the time of distress,

Vessel In Distress 503110520 (this is the actual vessel in distress)
Nature of Distress 05 - Sinking

Hope this helps.

________________________________

**Comment by Rasbats** [comment]
Thanks. DSC distress relay and relay cancel messages are now implemented.

**Comment by Rasbats** [comment]
@TwoCanPlugIn Beta available. Can this be closed?
