### ISSUE TITLE
Invalid end of NMEA sentence

### ISSUE THREAD

**Issue by Rodemfr** [Rasbats/shipdriver_pi#530]
ShipDriver ends its NMEA sentences with `<0x0a><0x0a>` instead of `<0x0d><0x0a>`. Several of the devices/apps I use for testing do not understand this. The concerned code seems to be between lines *423* to *437* of file *ShipDrivergui_impl.cpp* :

`PushNMEABuffer(MWVA + _T("\n"));` should probably be `PushNMEABuffer(MWVA + "\r");`

**Comment by Rasbats** [comment]
Thanks for the input.

**Comment by Rasbats** [comment]
Made the changes you suggested. Looks good on Windows. When you have time could you do a test? An alpha build is here:
[https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/?q=](https://cloudsmith.io/~opencpn/repos/shipdriver-alpha/packages/?q=)
Just choose your OS. It would be interesting to know the OS used. 
Thanks.

**Comment by Rodemfr** [comment]
I use ShipDriver on both Linux & Windows.
I just tested your alpha version and it is not yet working. Now I see NMEA sentences ended by `<0x0a><0x0d>` instead of `<0x0d><0x0a>`. Not far from the solution...

**Comment by Rodemfr** [comment]
Crossing the output of your latest version and the code, I found that function `wxString Dlg::makeCheckSum(wxString mySentence)` is adding the `<0x0a>` at the end of the sentence at line 900 : 
`tmpss << hex << (int)XOR << endl;`
I'm wondering if `endl` interpretation is dependent on the OS.
So you can either explicitly add `<0x0d><0x0a>` in this function and remove the addition of '\r' in each `PushNMEABuffer` call, or you can do the opposite : remove `endl` addition in the function and add "\r\n" at each `PushNMEABuffer` call.

**Comment by Rasbats** [comment]
@Rodemfr Endings now <0x0D><0x0A>. Latest tarballs in the alpha packages. Does this work for you?

**Comment by Rodemfr** [comment]
Working perfect now, thanks !

**Comment by Rasbats** [comment]
Thanks for your help. Rather busy but I will put it in the catalog when time allows.
