### ISSUE TITLE
Initial size of Shipdriver dialog is too small

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#532]
First time running Shipdriver, the dialog is not sized correctly,and users may not be aware what features are present.
![ship-driver-01](https://github.com/Rasbats/shipdriver_pi/assets/41049749/5cf3157e-f484-4da8-8385-73a8822cecfb)

**Comment by Rasbats** [comment]
My mistake. Easily fixed. -1;-1!

**Comment by Rasbats** [comment]
Fixed in alpha.

**Comment by Rasbats** [comment]
@TwoCanPlugIn Beta available. Can this be closed?

**Comment by Rasbats** [comment]
Closing.
