### ISSUE TITLE
Speed display is displayed incorrectly if the heading is altered using the +/- 1 and 10 degree buttons

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#534]
If the user has started Shipdriver in Auto mode, and alters the heading using the plus/minus one and ten degree buttons the speed is incorrectly displayed, even though the speed slide control has not changed. 

![ship-driver-03](https://github.com/Rasbats/shipdriver_pi/assets/41049749/78842c0e-d53f-40f9-acfd-298352ecac01)

**Comment by Rasbats** [comment]
Not enough room in the text control. Now fixed in the master branch. Closing.
