### ISSUE TITLE
Start/Stop buttons do not resume previous vessel speed.

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#535]
If I have started Shipdriver using the start button, and then stop the vessel, when I press start again, the speed has been reset to zero.

I personally find it hard to discern (other then the vessel moving or the SOG values changing) whether Ship driver is started or stopped.

My preference would be for a single button where the label toggles between "Start" and "Stop". Even better, add another button with "Pause" and "Resume" labels

![ship-driver-04](https://github.com/Rasbats/shipdriver_pi/assets/41049749/3e11cb0a-8c12-4d43-8c33-2342ed5f561d)

**Comment by Rasbats** [comment]
Added a message when STOP button is used. I use STOP like an engine telegraph STOP ENGINE.

**Comment by Rasbats** [comment]
Pause/Resume implemented in the master branch. Closing.
