### ISSUE TITLE
Behaviour when Auto is engaged

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#537]
I presume the "Auto" button means to hold the vessel on the current heading.

If I move to rudder away from amidship, the vessel begins to turn as expected. When I press the "Auto" button (or called "Heading Hold" by other brands of autopilots), my expectation is that the vessel would then follow that heading, returning the rudder to the amidships position rather than continuing with the turn.

**Comment by Rasbats** [comment]
My lack of an explanation in the manual and linked with the lack of APB. Auto should allow one to activate a waypoint and maintain a course towards that waypoint.

**Comment by Rasbats** [comment]
@TwoCanPlugIn : I cannot get OpenCPN to produce the APB sentence by activating a route or waypoint. This is using OpenCPN 5.8.4 on Windows and Ubuntu Jammy (using Flatpak). With no connections to OpenCPN could you provide a screenshot of the NMEA debug window, showing APB?
Many thanks.

**Comment by TwoCanPlugIn** [comment]
Hi Mike, currently sailing and at an isolated anchorage. Will be in a marina in a few days so I'll get something back to you then when I can plugin my Windows laptop.
________________________________

**Comment by TwoCanPlugIn** [comment]
Bit hasty on my last reply.
My test of the other day had one inbound UDP connection where I feed nmea183 data and one outbound serial connection (in my case using com0com virtual serial ports). When activating a route via OpenCPN, RMB, APB & XTE sentences were sent.
When disabling the UDP port and just using shipdriver to follow a route, no sentences were sent over the virtual serial port.
Nonetheless I'll have a better look when I can charge up my laptop.
________________________________

**Comment by Rasbats** [comment]
Enjoy the sailing.
Using OpenCPN 5.6.2 without connections APB is generated. I am trying to work out what has changed.

**Comment by TwoCanPlugIn** [comment]
On 5.6.x without any outbound connection, when you activate a route/waypoint you receive RMB, APB & XTE sentences presumably from the SetNmeaMessage API?

I guess they've broken that with the new event/listener model. What would happen if you added a listener for the APB sentence?

Cheers.
________________________________

**Comment by Rasbats** [comment]
Good one. Thanks for that. I set up a UDP connection and the APB sentences are there. I have implemented a listener for this in another plugin. WIP.

**Comment by Rasbats** [comment]
Auto is working correctly. UDP 127.0.0.1 and activate the route and auto works.
