### ISSUE TITLE
Update logbook and vdr?

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#539]
Can you advise when I can update using perhaps v3.3.0?  Thanks.

**Comment by leamas** [comment]
./update-templates...

**Comment by Rasbats** [comment]
@leamas  Is busy with other stuff, I think. May be some time before sd3.3.0. Suggest using the latest template, sd3.2.4.

**Comment by rgleason** [comment]
Ok thanks.

**Comment by rgleason** [comment]
Hope you'll advise when we can update. Thanks.
