### ISSUE TITLE
Too many tags.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#54]
For someone coming from the outside like me the list of tags is staggering. It seems like each and every build is tagged.  The question then becomes why is that?

**Comment by Rasbats** [comment]
Probably my incompetence as I create the CircleCI builds with the new tag. A better name for the commit would work just as well for retracing my steps.

**Comment by leamas** [comment]
well, just wanted to check and give some feedback. It's your repo, to tag as you  find suitable.

Closing
