### ISSUE TITLE
List of Routes Not Updated

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#543]
Hi Mike,

Another observation, tell me when to stop!

When the "Follow" button is pressed it displays a list of routes that can be selected.

However this list is only constructed from the routes available when the plugin is initialized, not for any routes that have been created during the current OpenCPN session.

The list of available routes should created when the "follow" button is pressed.

In addition, rather than parsing the navobj.xml file directly, why not use the plugin API, GetRouteGUIDArray ? I think that might simplify your code.

**Comment by Rasbats** [comment]
Don't stop!!!

Yes I had not found `GetRouteGUIDArray()`. Much nicer. WIP.

**Comment by Rasbats** [comment]
The API does not have access to a list of routes, unlike the waypoints in a route. Have tried to make my own route list but failed several times.

Cannot make a list using std::list either. Got involved with unique pointers in the definition of `GetRouteEx_Plugin` .

   ```
  m_bUsingFollow = false;
	PlugIn_Route_Ex thisRoute;
	list<PlugIn_Route_Ex*> mylist;
	
	wxArrayString myRoutes = GetRouteGUIDArray();

	for (int r = 0; r < myRoutes.size(); r++) {
	
		thisRoute = *GetRouteEx_Plugin(myRoutes[r]);
		wxMessageBox(thisRoute.m_NameString);
		mylist.push_back(&thisRoute);
	}
```
After two days on this I need to move to other stuff. Ideas?

**Comment by leamas** [comment]
> The API does not have access to a list of routes, unlike the waypoints in a route.

hm.. this looks like a  major oversight. Since the list fo route GUIDs is available, I think it would be valuable if you filed this as an issue against main OpenCPN (I have future plans which also probably needs this, but is not there yet).

**Comment by leamas** [comment]
Discussed in https://github.com/OpenCPN/OpenCPN/discussions/3399, the "list of routes is not available" basically resolved.

**Comment by Rasbats** [comment]
Now fixed in the master branch.
