### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by TwoCanPlugIn** [Rasbats/shipdriver_pi#550]
Hi Mike,

Well you told me not to stop !

How about simulating an AIS collision ?

Given your vessel's course and speed, project a position, say 30' away, From that position, generate a course & speed that will set an AIS target on a collision course, Hopefully, that should generate a CPA/TCPA alert.

**Comment by Rasbats** [comment]
A fake ship on a steady bearing should work. Time!!!

**Comment by TwoCanPlugIn** [comment]
Time, something we have very little of.

Cheers.

**Comment by Rasbats** [comment]
Fixed in the master branch. Closing.
