### ISSUE TITLE
Checksum not created in the tarball metadata.xml with sd3.2.5-beta1

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#556]
As per title. 

Both Windows and Linux.

This means that the checksum fails when trying to load a tarball from the catalog.

**Comment by leamas** [comment]
I'll take a look, probably tomorrow

**Comment by leamas** [comment]
Oops... the metadata in the tarball just cannot contain the checksum. 

That is, let's say we have a tarball and compute the checksum. And we then patch metadata.xml with the new checksum. No problem, besides that the tarball now will have a new checksum. 

OTOH, the checksum in the catalog is derived from the separate .xml file, and this has a checksum.  This xml file goes into the pull request and eventually to the catalog.

So, what is the problem here, really?  "confused"

**Comment by Rasbats** [comment]
First noted after adding a beta to _frcurrents_pi_:
[https://github.com/Rasbats/frcurrents_pi/](https://github.com/Rasbats/frcurrents_pi/)

When trying to install the plugin from the catalog I get a checksum error. Where does this originate? What is being compared?

```
08:50:26.255 MESSAGE update_mgr.cpp:222 Selected update: frcurrents
08:50:26.272 MESSAGE pluginmanager.cpp:572 Installing frcurrents
08:50:26.636 MESSAGE downloader.cpp:119 filesize https://dl.cloudsmith.io/public/mike-rossiter/frcurrents-beta/raw/names/frcurrents-v1.0.2-beta1-msvc-wx32-10-tarball/versions/v1.0.2-beta1/frcurrents-v1.0.2-beta1_msvc-wx32-10-win32.tar.gz: 3539615 bytes

08:50:27.795 MESSAGE download_mgr.cpp:98 Checksum fail on frcurrents, tarball: sha256:63289508d3d16e04430e62bd48dc1f41ae16bc7b6aaceef7d64592cf2ebaeeec, metadata: sha256:85ef43663b6b2e3f13adf1dd403dd2e975f53d717846fbf12dc9789ee473613e
```

**Comment by leamas** [comment]
> When trying to install the plugin from the catalog I get a checksum error. Where does this originate?

As I said, the checksum in the catalog originates from the separate xml file created together with the tarball. The path from the build to the catalog is (for shipdriver) via the git_push which pushes it to the auto branch which you eventually make a PR from.

> What is being compared?

On Linux, where most tools usually are available, the catalog checksum is compared to the sha256 digest computed on the tarball. After a build, you could check things by inspecting _whatever.xml_  and compare to the output of `sha256sum whatever.gz`

On Windows, you can use cmake to check the actual checksum: `cmake -E sha256sum whatever.gz` ; that should actually work on all platforms.

**Comment by leamas** [comment]
> Where does PKG_BUILD_INFO come from?

In config.h.in there is `#define PKG_BUILD_INFO "@pkg_vers_build_info@"`. That is, PKG_BUILD_INFO is set to the value of the cmake variable _pkg_vers_build_info_. 

_pkg_vers_build_info_  is set in cmake/Metadata.cmake.

**Comment by Rasbats** [comment]
>In config.h.in there is #define PKG_BUILD_INFO "@pkg_vers_build_info@"
I am comparing apples with pears.
sd3.2.5-beta1 does not have: PKG_BUILD_INFO. This appears in the master branch.

**Comment by leamas** [comment]
No. I am on master at 75d83bce. Here, config.h.in is:
```
cat  config.h.in
#define API_VERSION       "@API_VERSION@"

#define PLUGIN_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define PLUGIN_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define PLUGIN_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define PLUGIN_VERSION_TWEAK @PROJECT_VERSION_TWEAK@

#define PKG_PRERELEASE "@PKG_PRERELEASE@"
#define PKG_BUILD_INFO "@pkg_vers_build_info@"

#define PLUGIN
```

**Comment by leamas** [comment]
Ah... sd3.2.5-beta1 does indeed not have an updated config.h.in.  But why  work with that? Are we not heading for 3.3.0,  which is based on master?

**Comment by Rasbats** [comment]
I was using sd3.2.5-beta1/update-templates when setting up frcurrents. Roll on sd3.3.0-beta1.
Compared the checksums of the tarball and metadata file on Cloudsmith. They are the same. 

When I compare auto and beta branches of OpenCPN/plugins they are not the same. All I did was the normal squash from auto to Beta.

**Comment by Rasbats** [comment]
This only appears to be a problem with Windows. Appveyor builds both the tag and the commit. Is this causing the problem?

**Comment by Rasbats** [comment]
Did I not wait long enough for the tag build to finish/overwrite the xml file?

**Comment by Rasbats** [comment]
Need to make another beta. Please wait for this.

**Comment by leamas** [comment]
Yes. And please use a name  sd3.3.0-beta1 for the tag, we are heading to 3.3.0 and nothing else.

**Comment by leamas** [comment]
> When I compare auto and beta branches of OpenCPN/plugins they are not the same. All I did was the normal squash from auto to Beta.

The thing to do here is to checkout the auto branch and then check then checksum there.  There are two options:

1. If the checksum in the auto branch is ok: ` git checkout beta; git checkout auto memetadata/frcurrents_pi.xmtadata/frcurrents_pi.xml` , if I got the name of the xml file correctly.
2. If the checksum in the auto branch is wrong you need to fix this. The easy path would be to download the correct xml file from cloudsmith, copy it to _metadata/frcurrents_pi.xml_  and commit.

**Comment by leamas** [comment]
Time to close?

**Comment by Rasbats** [comment]
Ok. Closing.
