### ISSUE TITLE
Android version causes a fatal crash

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#559]
If the Android version is installed with OpenCPN 5.8.4 (Android) the plugin does not run and OpenCPN crashes.The program cannot be re-started and needs to be re-installed.

Calculator_pi (with sd3.2.5) installs and seems to run without a problem. Standby for a log file.

**Comment by leamas** [comment]
hm... after a night's sleep: this is more or less as expected.

What has happened is that @bdbcat  has updated the library we link the plugins against. Contrary to other platforms, this library basically is the complete OpenCPN application. That means that to load the plugin one needs an Android executable of the same version as the library, an executable which I presume is yet not available (?)

We probably have to live with this. The crash should be resolved at latest when we enter the beta cycle and new android images becomes available.

**Comment by leamas** [comment]
OTOH, it should not crash. Main OpenCPN should refuse to load the plugin, deeming it as incompatible since the api version does not match: https://github.com/OpenCPN/OpenCPN/issues/3433

**Comment by Rasbats** [comment]
But why does Calculator_pi install and run without a problem?

One thing I notice is that Calculator code uses `#ifdef __OCPN__ANDROID__`. ShipDriver uses `#ifdef __ANDROID__`.
In the sd3.2.0 release changelog: _Drop the OCPN__ANDROID symbol, use ANDROID instead._

**Comment by Rasbats** [comment]
This was December 2022 when a lot of work was done with Android builds.

**Comment by Rasbats** [comment]
My mistake: Calculator_pi was on sd3.2.1 not sd3.2.5. [https://github.com/Rasbats/calculator_pi/commit/80a2699f2f9e29d0ebc44724673e1809968bc62a](https://github.com/Rasbats/calculator_pi/commit/80a2699f2f9e29d0ebc44724673e1809968bc62a)

**Comment by leamas** [comment]
Until there are logs proving me wrong I'm pretty convinced that this is about the new libgorp.so. This actually has two aspects. The first is just linking "old" code to it; that might work. However, as soon as we make the changes related to the new API things will almost certainly break since the plugin then uses functions not yet available in the opencpn app.

More thinking: When we make an API update we need updated OpenCPN executables/apps to test with.  On other platforms this is not really a problem, but it is on Android. @bdbcat ?

That said, the incompatible plugin should not have been loaded at all, the OpenCPN bug  still valid.

**Comment by bdbcat** [comment]
@Rasbats 
Got some space, ready to dig into this.
How did you load the plugin?  By import?
Where is the plugin tarball available now?

**Comment by Rasbats** [comment]
@bdbcat : Loaded from the master catalog. I did not find an import option with OpenCPN runing on OS v13. 

Available here:
[https://cloudsmith.io/~opencpn/repos/shipdriver-prod/packages/detail/raw/ShipDriver-v3.3.2-debian-arm64-A64-11-tarball/v3.3.2/](https://cloudsmith.io/~opencpn/repos/shipdriver-prod/packages/detail/raw/ShipDriver-v3.3.2-debian-arm64-A64-11-tarball/v3.3.2/)

**Comment by Rasbats** [comment]
Available here:
[https://cloudsmith.io/~opencpn/repos/shipdriver-prod/packages/detail/raw/ShipDriver-v3.3.2-android-arm64-A64-16-tarball/v3.3.2/](https://cloudsmith.io/~opencpn/repos/shipdriver-prod/packages/detail/raw/ShipDriver-v3.3.2-android-arm64-A64-16-tarball/v3.3.2/)

**Comment by bdbcat** [comment]
@Rasbats 
OK, thanks, I'm on it.
btw, on Android, the "import" option is only enabled when CatalogExpert is set in the config file.  Saving screen real estate.

[Plugins]
CatalogExpert=1

**Comment by bdbcat** [comment]
Simple test on Android 12, OpenCPN v103.  Install from Beta catalog.
No crash.
More info?

**Comment by Rasbats** [comment]
@bdbcat : Those were v3.3.0. After that we changed the api to 118. The version that crashed was v3.3.2. (See above)

How do you edit _opencpn.conf_? Nothing on Android 13 seems to be able to open it.

**Comment by bdbcat** [comment]
@Rasbats 
1.  Ah, now I remember.  We reverted the catalog due to the crash.
2. OK, I'll import the v3.3.2 tarball.  I assume it is not available in any catalog?
3. Install the Android app "X-plore", free on the Playstore.  This should give access to the OCPN app directory, and "opencpn.conf".

**Comment by Rasbats** [comment]
> I assume it is not available in any catalog?

I took it off with a PR.

**Comment by bdbcat** [comment]
@Rasbats 
To help in debugging this:
Do you actually need the functions/methods in API 118?  Which ones?

**Comment by bdbcat** [comment]
@rasbats @leamas 
The crash:
In branch v5.8.x (which is current Android source)
plugin_loader.cpp:1382
    case 118:
      pic->m_pplugin = dynamic_cast<opencpn_plugin_118*>(plug_in);
      do /* force a local scope */ {
        auto p = dynamic_cast<opencpn_plugin_118*>(plug_in);
        pi_ver =
            SemanticVersion(pi_major, pi_minor, p->GetPlugInVersionPatch(),
                            p->GetPlugInVersionPost(), p->GetPlugInVersionPre(),
                            p->GetPlugInVersionBuild());
      } while (false);
      break;

The dynamic cast fails, leaving "p" as NULL.  This the crash.

OCPN for Android is built using a prior version of ocpn_plugin.h, before the "using" patch which was added to silence some warnings.  As a test, I updated core ocpn_plugin.h with the version found in opencpn-libs/api-18.  No help.

So, why will shipdriver_pi class not cast to a "opencpn_plugin_118" ??
Need more eyes...

**Comment by bdbcat** [comment]
Just some thoughts:
1,  In ocpn_plugin.h, the definition of opencpn_plugin_118, I notice that the new methods added are not marked "virtual".  Every other plugin class method is marked virtual.  Could this be the trouble?

**Comment by bdbcat** [comment]
Random debug observation:
If in the code snippet above I substitute "static_cast" for "dynamic_cast", the plugin loads and runs without crash.  So I deduce that the plugin class is basically intact, looks mostly like a "opencpn_plugin_118", has a funtional vtable, etc.

So, how to debug in detail the failure of a dynamic_cast ??

**Comment by bdbcat** [comment]
More thoughts:
ocpncpn_plugin_117 and _118 do not define virtual destructors, as all other versions do.
I am definitely suspicious of that.
Needs an update to opencpn-libs.

**Comment by leamas** [comment]
> In ocpn_plugin.h, the definition of opencpn_plugin_118, I notice that the new methods added are not marked "virtual". Every other plugin class method is marked virtual. Could this be the trouble?

Whether this is the trouble or not, it's partly wrong (my bad). 

The general contract is that for a overridden method, all overrides becomes virtual if the base implementation is. To be explicit, methods should thus be marked either `virtual` or `override`.

We have 
```
bool RenderGLOverlayMultiCanvas(wxGLContext *pcontext, PlugIn_ViewPort *vp,
                                  int canvas_ix) override 
```

This one overrides  the same signature in plugin_116. That one is marked virtual so this is ok. However:
```
 bool RenderGLOverlayMultiCanvas(wxGLContext *pcontext, PlugIn_ViewPort *vp,
                                 int canvasIndex, int priority);
```
This one does **not** override and should thus be marked `virtual`. OTOH, this should not make a difference until plugin_119 which then possibly could override. And changing this now would probably break the linkage,  substituting a compile time link with a runtime one.

**Comment by leamas** [comment]
> So, how to debug in detail the failure of a dynamic_cast ??

I guess it's hard. However, the `typeid` operator returns crucial parts here. Perhaps something like this could add some piece of information, dunno
```
 do /* force a local scope */ {
std::cout << "plugin_type: " << typeid(plug_in).name() << "\n";
    auto p = dynamic_cast<opencpn_plugin_118*>(plug_in);
```

**Comment by leamas** [comment]
> ocpncpn_plugin_117 and _118 do not define virtual destructors, as all other versions do.

This should be ok. They derive from plugin_116 which has a virtual dtor. Hence, all derived classes have an implicit virtual dtor as well.

**Comment by bdbcat** [comment]
@leamas 
More experiments, on Android, using one of the in-built plugins as test subject.
SOLVED.
This is the one:

However:

 bool RenderGLOverlayMultiCanvas(wxGLContext *pcontext, PlugIn_ViewPort *vp,
                                 int canvasIndex, int priority);

This one does not override and should thus be marked virtual.

Must be a clang or Android thing, I guess.

So, we need an immediate update to opencpn-libs/master.
I can publish an update to Android in a day or so.
Thoughts?

**Comment by leamas** [comment]
This will possibly break those who already have started experimenting. Still, it's the right thing to do. 

Here we need the general info channel which zulip provides, even though not that many listens.

**Comment by Rasbats** [comment]
>Please let me know how this goes.

Will do. I will get an updated build into the catalog this week. X-plore did not help with editing _opencpn.conf_ so the catalog route seems to be favourite.
