### ISSUE TITLE
opencpn-libs question

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#560]
Mike, Is my local repository for github.com/rgleason/shipdriver_pi   supposed to have a directory for "opencpn-libs"?
I seem to still have a "libs" directory.  Does that need to be reconfigured somehow?  How do these submodules work?
Thanks.

PS: The same applies to my vdr_pi and logbookkonni_pi local repositories.  Also is it time to update them?

**Comment by Rasbats** [comment]
I suggest deleting or backing up your fork and make a new fork. When you do this you will get an _opencpn-libs_ folder. In this is the README.md with a guide to using the module.

**Comment by rgleason** [comment]
Ok Thanks. Will do that.
