### ISSUE TITLE
Latest opencpn-libs has some problems

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#561]
Working with a new plugin - e_timer_pi there were two problems.

1.  For Android builds I needed to edit _AndroidLibs.cmake_ to make the check hash match that for Dave's master.zip as found in a recent ShipDriver build.

```
if (NOT EXISTS ${OCPN_ANDROID_CACHEDIR}/master.zip)
  file(
    DOWNLOAD
      https://github.com/bdbcat/OCPNAndroidCommon/archive/master.zip
      ${OCPN_ANDROID_CACHEDIR}/master.zip
    EXPECTED_HASH
      SHA256=b6359260ecfb44b96c0dd4052e41aac505c9e3c4eb7a798b29c17ddbc3c939b3
    SHOW_PROGRESS
  )
endif ()

```

2. For Flatpak:

```
/run/build/e_timer/opencpn-libs/plugingl/src/TexFont.cpp:41:10: fatal error: GL/glu.h: No such file or directory
   41 | #include <GL/glu.h>
      |          ^~~~~~~~~~
compilation terminated.

```

Build log is here: 
[https://app.circleci.com/pipelines/github/Rasbats/e_timer_pi/15/workflows/de81df08-54f6-40f0-92ed-a571d87ef332/jobs/257](https://app.circleci.com/pipelines/github/Rasbats/e_timer_pi/15/workflows/de81df08-54f6-40f0-92ed-a571d87ef332/jobs/257)

Line 684

Perhaps a new template is needed for No.1.  Need help with No.2. Do I need to add the opencpn-glu library?

**Comment by leamas** [comment]
For 1. we need to update the template, full stop.

2: There is an upcoming mega update  to opencpn-libs which will land any time which  **might**  fix this. Can you wait a day or two?

**Comment by leamas** [comment]
it's perhaps simple. You need to add the flatpak glu module.  There is sample code in the shipdriver manifest which does exactly that below. 
```
[...]
modules:
    - @include opencpn-libs/flatpak/glu.yaml
[...]
```

**Comment by Rasbats** [comment]
AndroidLibs.cmake updated. Now available from sd3.3.0-beta1. Closing.
