### ISSUE TITLE
wxWidgets 3.2.3 is upon us.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#564]
We need to update the build dependencies to 3.2.3. This is a stable ABI release which should not generate any problems.

This includes references in 
  - appveyor.yaml
  - cmake/MacosWxwidgets.cmake
  - ci/circleci-build-debian.sh 
  - ci/circleci-build-debian-docker.sh
  - ci/circleci-build-debian-armhf.sh

The linux 3.2 packages are for use on bulllseye  which otherwise is on 3.2. They use pre-built packages in https://dl.cloudsmith.io/public/alec-leamas/wxwidgets-32 which thus needs an update..

EDIT: Macos uses  https://dl.cloudsmith.io/public/nohal/opencpn-plugins/raw/files/macos_deps_universal.tar.xz . discussed in https://github.com/OpenCPN/OpenCPN/issues/3456

**Comment by rgleason** [comment]
1. We no longer use appveyor for building msvc on pi.
2. My credits for circleci are totally used up. I wish this change had happened earlier as we are just finishing rebuilding all TP PI and I am taking a 3 month break once it is done.

**Comment by leamas** [comment]
We? The template uses appveyor, the basic reason is to avoid exactly the problems you describe.

**Comment by rgleason** [comment]
Appveyor no longer works for msvc

**Comment by leamas** [comment]
In what context? Using shipdriver template, or TP?

**Comment by rgleason** [comment]
TP.  Appveyor appears to be missing a vital header. Bdbcat tried to fix it, but what we did was move to circleci and drop WinXT support for O5.6  
We will be dropping build of O5.6 plugins pretty soon.

**Comment by leamas** [comment]
OK. As long as this is only affects TP is is a TP issue. The real issue here is how/when to update to wx 3.2.3, please stick to that.

**Comment by Rasbats** [comment]
CircleCI seems to be having a problem with these builds:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi)

**Comment by leamas** [comment]
Indeed. But why on earth  did it build for me? Now [fixed](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1943/workflows/40d8764c-43d8-4a04-aece-166f6a559379). 

Thanks for heads-up!
