### ISSUE TITLE
windows: target-arch: change x86_64 to win32.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#573]
As of discussions in https://github.com/OpenCPN/OpenCPN/issues/2027, we should update generated windows XML so it sets `<target-arch>` to _win32_ instead of current _x86_64_ for Windows builds. This is basically just to make things  more consistent, `<target-arch>` is actually not used these days.

**Comment by leamas** [comment]
NOte: https://github.com/Rasbats/shipdriver_pi/blob/master/cmake/GetArch.cmake#L51-L53

**Comment by leamas** [comment]
Actually, use _x86_ instead. Blocked on https://github.com/OpenCPN/plugins/pull/1069

**Comment by Rasbats** [comment]
After another problem with this today a fix would be good. 
[https://github.com/OpenCPN/plugins/pull/1068](https://github.com/OpenCPN/plugins/pull/1068)

**Comment by Rasbats** [comment]
On inspection there was no target-arch in the metadata:
  ```
<target>msvc-wx32</target>
  <target-version>10</target-version>
  <target-arch></target-arch>
  <tarball-url> https://dl.cloudsmith.io/public/mike-rossiter/frcurrents-prod/raw/names/frcurrents-v1.4.1-msvc-wx32-10-tarball/versions/v1.4.1/frcurrents-v1.4.1_msvc-wx32-10-win32.tar.gz </tarball-url>
  <tarball-checksum> 8ed731cf07f5e218de695d4bc944eb74de804d6e4a344a5df0fdc53af9ffeca9 </tarball-checksum>

```
[https://github.com/Rasbats/frcurrents_pi](https://github.com/Rasbats/frcurrents_pi)
