### ISSUE TITLE
CI: circleci: all debian builds are broken

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#580]
All debian builds fails in the upload step  where the `cloudsmith` command crashes.

As I understand it something has changed in   the CCI image.

**Comment by Rasbats** [comment]
Commit 11e1f84, about 5 days ago built and artifacts ended up in the alpha Cloudsmith repo as expected.

**Comment by leamas** [comment]
Yep, this is most likely not about out code. I have filed a  cloudsmith support issue.

**Comment by leamas** [comment]
The cloudsmith support has fixed the problem. Extremely responsive in the chat. Closing
