### ISSUE TITLE
RFE: Improve UPDATE_TEMPLATE.md

### ISSUE THREAD

**Issue by sebastien-rosset** [Rasbats/shipdriver_pi#591]
I'm trying to follow the instructions listed at https://github.com/Rasbats/shipdriver_pi/blob/bf214e02ee8e10ac8a88fcfa04f00c9bdb9a09c6/UPDATE_TEMPLATES.md

I'm fairly new to the OpenCPN plugin development process, and so far, I've been able to do the following steps:
https://github.com/seandepagnier/weather_routing_pi/pull/299

I had to do a few manual steps, such as copying the content of `build-deps` and `flatpack`.

The instructions indicate keys should be copied. What are these keys?
https://github.com/Rasbats/shipdriver_pi/blob/bf214e02ee8e10ac8a88fcfa04f00c9bdb9a09c6/UPDATE_TEMPLATES.md?plain=1#L7

**Comment by Rasbats** [comment]
weather_routing uses the Testplugin template not the shipdriver one. 
Manuals for both are here:
[https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/intro-AboutThisManual.html](https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/intro-AboutThisManual.html)

**Comment by leamas** [comment]
Not a bug... closing
