### ISSUE TITLE
win_deps.bat ERROR

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#592]
To fix a problem with Pathman work done by @nohal for dashboardsk_pi for Windows has been added. He used wxWidgets 3.2.2.1 but I have edited to use 3.2.5 and added to the repo.

This will only work with OpenCPN 5.9.x/5.10.

With the publication of 5.10 should the SD template move to using only wxWidgets 3.2.5 for Windows. IMO this would simplify a lot of the code.

**Comment by nohal** [comment]
Not really. We can only fully move to wx 3.2 after we drop support for Debian Bullseye derivatives, which only have wx 3.0. Until then, the code needs to be wx 3.0 compatible.
Whether you build a plugin against wx 3.2.2 or wx 3.2.5 does not matter, they are ABI compatible and when loaded use whatever the OpenCPN process is using.

**Comment by leamas** [comment]
That is the Linux view, agreed. The corresponding windows question is if we should build both msvc and msvc-wx32 or just  msvc-wx32. The latter is for older OpenCPN wx3.0 versions.

**Comment by nohal** [comment]
Just wx32, nobody caring about plugins uses the old wx30 based versions.

**Comment by Rasbats** [comment]
And for Windows I would like people to move to OpenCPN 5.9.x/5.10 for new plugins hence the use of wxW 3.2.5.
