### ISSUE TITLE
Builds for bullseye and bullseye-wx32 fail with the sd3.3.0 template

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#602]
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/1094/workflows/856f64ce-6ab0-4035-9d39-4a36fff04e48](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/1094/workflows/856f64ce-6ab0-4035-9d39-4a36fff04e48)

This problem is not just ShipDriver. Other plugins have the same issue when the sd3.3.0 template is used. (survery_pi, SailawayNMEA_pi)

**Comment by Rasbats** [comment]
Is this the problem?
[https://github.com/ethereum/solidity/issues/13057](https://github.com/ethereum/solidity/issues/13057)

**Comment by leamas** [comment]
I don't see that. 

However, perhaps the problem is visible in the log. Excerpt:
```
cd /run/build/shipdriver_pi/opencpn-libs/plugin_dc/dc_utils && /usr/bin/cmake -E cmake_link_script CMakeFiles/_DC_UTILS.dir/link.txt --verbose=1
/usr/bin/ranlib: lib_DC_UTILS.a: error reading pi_shaders.cpp.o: file truncated
/usr/bin/ar qc lib_DC_UTILS.a CMakeFiles/_DC_UTILS.dir/src/pi_shaders.cpp.o CMakeFiles/_DC_UTILS.dir/src/pidc.cpp.o CMakeFiles/_DC_UTILS.dir/src/qtstylesheet.cpp.o CMakeFiles/_DC_UTILS.dir/src/TexFont.cpp.o
/usr/bin/ranlib lib_DC_UTILS.a
make[6]: *** [opencpn-libs/plugin_dc/dc_utils/CMakeFiles/_DC_UTILS.dir/build.make:152: opencpn-libs/plugin_dc/dc_utils/lib_DC_UTILS.a] Error 1
make[6]: *** Deleting file 'opencpn-libs/plugin_dc/dc_utils/lib_DC_UTILS.a'
```

From here, it looks like pi_shaders.cpp.o  is referenced before it is created. If this indeed is the problem, it would mean we have a missing dependency declaration.

Still no opencpn time  -- hopefully, there will be coming week.  The backlog is piling up :(

**Comment by leamas** [comment]
Another finding in the log:
```
Dependencies file "opencpn-libs/plugin_dc/dc_utils/CMakeFiles/_DC_UTILS.dir/src/pi_shaders.cpp.o.d" is newer than depends file "/run/build/shipdriver_pi/opencpn-libs/plugin_dc/dc_utils/CMakeFiles/_DC_UTILS.dir/compiler_depend.internal".
```

No idea what this actually  means for now. Looks suspicious, though.
