### ISSUE TITLE
Creating GLLSentence with speed instead of distance

### ISSUE THREAD

**Issue by CharlesParent** [Rasbats/shipdriver_pi#71]
Hello,

I am trying to understand how NMEA sentences are generated in this code:

CreateGLLSentence is called 3 times in this code.
The first 2 times the 4th parameter is initSpd / 7200, which I understand as the distance traveled by the ship during 500ms (timer interval)

But the third time CreateGLLSentence is called with only initSpd. Why ?

https://github.com/Rasbats/shipdriver_pi/blob/40db90f9566c0135027add3686c60cf11a5f6959/src/ShipDrivergui_impl.cpp#L413

**Comment by Rasbats** [comment]
A typo in StartDriving(). initSpd is set as 0.0 and then the createGLLSentence uses initSpd/7200 which is also 0. It should read just initSpd in that createGLLSentence as well.

The first createGLLSentence is therefore using speed 0.0, which is ok.

**Comment by Rasbats** [comment]
Now corrected in Master.
