### ISSUE TITLE
Bad warning for unowned widgets.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#75]
The compiler detects some unowned widgets:

```
 93%] Building CXX object CMakeFiles/ShipDriver_pi.dir/src/ShipDrivergui_impl.cpp.o
/home/circleci/project/src/ShipDrivergui_impl.cpp: In constructor ‘GetRouteDialog::GetRouteDialog(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
/home/circleci/project/src/ShipDrivergui_impl.cpp:1600:13: warning: unused variable ‘b’ [-Wunused-variable]
  wxButton * b = new wxButton(this, wxID_OK, _("OK"), p, wxDefaultSize);
             ^
/home/circleci/project/src/ShipDrivergui_impl.cpp:1602:13: warning: unused variable ‘c’ [-Wunused-variable]
  wxButton * c = new wxButton(this, wxID_CANCEL, _("Cancel"), p, wxDefaultSize);
             ^
```

Having GUI widgets as local variables basically creates an undefined state after leaving the function. The buttons should either be removed or assigned to a proper wxWidgets container.

The offending commit seems to be 31567222

**Comment by Rasbats** [comment]
The buttons are assigned to 'GetRouteDialog'. They are used when that dialog is opened. Not sure how to remove the warnings at the moment. They do not appear in VS2017!

**Comment by leamas** [comment]
That they doesn't appear  in VS2017 is IMHO a plain compiler bug (unless the warnings are disabled in that build).

An automatic (local) variable which goes out of scope is undefined. Later calls might reuse the memory, possibly creating a runtime crash. In any case, an orderly shutdown is by definition impossible.

The typical usecase is something like this (ok, my own code, but that is what I find most quickly...)

```
        /** OK/Cancel buttons for the download progress window. */
        struct Buttons: public wxPanel
        {
            Buttons(wxWindow* parent) : wxPanel(parent)
            {
                using CmdEvt = wxCommandEvent;

                auto sizer = new wxBoxSizer(wxHORIZONTAL);
                auto flags = wxSizerFlags().Right().Bottom().Border();
                sizer->Add(1, 1, 100, wxEXPAND);   // Expanding spacer
                auto cancel = new wxButton(this, wxID_CANCEL, _("Cancel"));
                sizer->Add(cancel, flags);
                m_ok = new wxButton(this, wxID_OK, _("OK"));
                m_ok->Enable(false);
                sizer->Add(m_ok, flags);
                SetSizer(sizer);
                Fit();
                SetFocus();
                Show();
            }
```

This is from main opencpn, in src/catalog_mgr.cpp around line 680 if you want more context. Here, the wxSizer instance owns the button, keeping the pointer in allocated memory and also tears it down when destroyed.

**Comment by leamas** [comment]
> The buttons are assigned to 'GetRouteDialog

No.  While the buttons keep  a pointer to _this_, nothing keeps a pointer to the buttons. This is the core issue here, disguised in the "unused variable" warning.

**Comment by Rasbats** [comment]
Ok, tbc. At the moment I am trying to kickstart Travis builds. Cancelled a few and now my latest commit, correcting another issue, will not build. The last commit where Travis worked was 2.5.54. After that Travis build I cancelled some builds triggered by pull requests. The commits 55 and 56 that I made failed to start. Is Travis the problem today?

**Comment by leamas** [comment]
Yes, I think that is a travis problem. Has occasionally occurred to me as well.

**Comment by leamas** [comment]
OTOH, I seem to be able to build current master at 61d840c  on travis: https://travis-ci.com/github/leamas/shipdriver_pi/builds/204966684. It does contain a single commit on top of that, but it shouldn't change anything.

**Comment by Rasbats** [comment]
Travis has made the build. Will get this lot into the master catalog of plugins tomorrow. This will allow a final test of the gtk2/3 Bionic builds.

**Comment by leamas** [comment]
Right. Before you do, please check that there are two separate builds for bionic (ubuntu and ubuntu-gtk3) since this was missing last time...

**Comment by Rasbats** [comment]
The two builds are made. Thanks very much for working on this.

**Comment by Rasbats** [comment]
Building for a fix for this at the moment.

**Comment by Rasbats** [comment]
Thanks for the correction Alec. Closing this one.
