### ISSUE TITLE
cmake: PluginCompiler: Nasty fix needs clean up.

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#79]
cmake/PluginCompiler.cmake contains this snippet:

```
# QT_ANDROID is a cross-build, so the native FIND_PACKAGE(wxWidgets...) and
# wxWidgets_USE_FILE is not useful.
if (NOT QT_ANDROID)
  if (NOT DEFINED wxWidgets_USE_FILE)
    set(wxWidgets_USE_LIBS base core net xml html adv)
    set(BUILD_SHARED_LIBS TRUE)
    find_package(wxWidgets REQUIRED)
  endif (NOT DEFINED wxWidgets_USE_FILE)

  include(${wxWidgets_USE_FILE})
endif (NOT QT_ANDROI
```

Clearly, this should be handled in Pluginlibs.cmake instead. Still, it's here for some reason I cannot remember.

@Rasbats: Can you shed some light on this? Why is this necessary, what fails if we drop it?

**Comment by Rasbats** [comment]
I think this was because Windows did not find wxWidgets. I will test to see if it is still needed.

**Comment by Rasbats** [comment]
Removed the section from 'PluginCompiler' and did not see any problems. 

I think this was first needed when PluginCompiler took over from PluginConfigure.cmake and I just copied the section from this to PluginCompiler to make it work.

I will make another ci build and see what happens there.

**Comment by leamas** [comment]
Nor did I. Closing this bug since this doesn't seem to be an issue after excluding this strange duplicate.
