### ISSUE TITLE
OpenCPN crashes with shipdriver

### ISSUE THREAD

**Issue by douwefokkema** [Rasbats/shipdriver_pi#8]
I start OpenCPN. There is a non active route displayed. Shipdriver plugin is enabled, but window not shown. Activate the route. OpenCPN crashes after a few seconds. Exception thrown at 0x66BF4793 (ShipDriver_pi.dll) in opencpn.exe: 0xC0000005: Access violation reading location 0x0000030C.
I did not do a debug compile, so no further details.
When I first open the shipdriver window by clicking the steering wheel in the menu bar, all is fine.
This is on Windows 10.

**Comment by Rasbats** [comment]
I see it. TODO!

**Comment by Rasbats** [comment]
Fixed, I hope.

Route cannot be activated until ShipDriver is started.

PlugInHandleAutopilotRoute(true) when SD opened.
PlugInHandleAutopilotRoute(false) when SD Started. Then activate the route.

**Comment by douwefokkema** [comment]
But now routes can no longer be activated, when shipdriver is shown or not. I have to disable shipdriver pi, restart O, then I can activate routes again.

**Comment by Rasbats** [comment]
Thanks. To be continued.

**Comment by douwefokkema** [comment]
I suggest that you remove both PlugInHandleAutopilotRoute. Then as follows:
@@ -499,7 +499,7 @@ bool ShipDriver_pi::GribWind(GribRecordSet *grib, double lat, double lon,
 void ShipDriver_pi::SetNMEASentence(wxString &sentence) {
 
 	// $GPAPB,A,A,0.10,R,N,V,V,011,M,DEST,011,M,011,M*3C 
-
+  if (NULL == m_pDialog) return;
 	wxString token[40];
 	wxString s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;
 	token[0] = _T("");

And all is fine!
Good tool by the way.

**Comment by douwefokkema** [comment]
it seems + is displayed as bullet point. so insert if (NULL == m_pDialog) return; at the beginning of 
SetNMEASentence(wxString &sentence) {

**Comment by Rasbats** [comment]
Thanks again. Out for the day but I will have a look tonight.

**Comment by Rasbats** [comment]
Master code and Windows installer updated. Looks good. Thanks Douwe.
