### ISSUE TITLE
git-push: Non-functional on windows

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#88]
git-push depends on the python3 cryptography module. This fails to install in appveyor, causing the git-push script to fail.

While a serious bug, it could be considered non-blocking.  The uploads to cloudsmith still works, as do all other platforms. Downloading the one and only windows metadata file to the plugins clone should make the directory complete and ready for a PR until bug is fixed.

Installing cryptography on windows is supposed to be simple, this is about the somewhat strange environment provided by appveyor.

**Comment by Rasbats** [comment]
So I would need to manually add this to the plugins Auto branch and then merge-squash with my plugins fork Master before making a pull request to OpenCPN/plugins. Is that correct?

**Comment by leamas** [comment]
> So I would need to manually add the metadata file to the plugins Auto branch  [...]

Yes
