### ISSUE TITLE
Unused (?) github artifact upload

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#92]
The last part of appveyor.yml is about uploading artifacts to github. Is  this used any more, or could it just be removed?

**Comment by Rasbats** [comment]
This has never worked for me anyway so... yes I think it can be removed. But... Appveyor is building twice, master and tag. The tag build always fails, as a result of being unable to upload to GitHub. Does this change the picture at all? The master build ends up in Cloudsmith ok.

**Comment by leamas** [comment]
First: since you don't use this code: just remove it. It's not like it's gone, git will keep it forever, so just drop it, don't comment it out. But you might want to write a reasonable commit message so you can find it if needed ;)

About the failed tag builds: If it still fails after removing the github upload stuff, please link to the build logs here so I can see for myself.

**Comment by Rasbats** [comment]
Removed from Appveyor. Build looks good. Travis finally decided to play. Now to move all this to UKTides!

**Comment by leamas** [comment]
> Now to move all this to UKTides!

Right. BTW: Is there any need to modify the files under cmake/ in UKTides?

**Comment by Rasbats** [comment]
No, all the cmake/ files from ShipDriver have been used as is for UKTides. Intend documenting the ones in other folders that need editing idc. 

I will probably put the chmod 755 back in config.yml and one or two other places. frontend2 has this. Without doing this using the ShipDriver scripts there are permission issues. There is the git command line fix but I prefer not to have to use this.

**Comment by leamas** [comment]
Yes, frontend 2 has it, but it's IMHO plain wrong. What's the problem with setting the permissions in git? Is it windows which makes it hard? Setting the correct permissions in the git repo is the way to use -- in other words, storing scripts which should be executed  without execute permissions is plain wrong.

But in the end,  your are the maintainer and the one who decides.

**Comment by leamas** [comment]
Aaa... windows, indeed. But there are solutions: https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows

**Comment by Rasbats** [comment]
Interesting but Windows...
Using: `git update-index --chmod=+x script.sh` (replacing script etc)
Only one script file could be changed: _circleci-build-raspbian-armhf.sh_
Checked with: `git ls-tree HEAD`
And then github desktop did not let me update the repo. `Commit failed - exit code 1 received`

**Comment by Rasbats** [comment]
Ignore my last. I did not `git commit -m "Changing file permissions"`
