### ISSUE TITLE
MIA: Local builds builddeps support

### ISSUE THREAD

**Issue by leamas** [Rasbats/shipdriver_pi#98]
There is a need to make local builds without CI. While the basic cmake setup for this is fine, the required build dependencies are undocumented. The closest we have is the ci scripts.

We need better docs and possibly also scripts for all platforms besides flatpak, which has it's own documentation which is OK

**Comment by leamas** [comment]
@rasbats: thougts?

**Comment by Rasbats** [comment]
Doing some research on this.

**Comment by Rasbats** [comment]
Find I have wget on my pc. Now downloading wxWidgets from opencpn and extracting with 7z like Appveyor. Thinking about the linking bit.

**Comment by Rasbats** [comment]
This needs to go into the wiki. That Windows batch file of yours has been very useful. Shell script for Linux?

**Comment by leamas** [comment]
When you have moved BUILD_DEPENDENCIES.md to the wiki this issue could be closed from my perspective.  

OTOH, that's just me.

**Comment by Rasbats** [comment]
Closing is fine. Trying the workflow on a plugin that needs outside libs. Photolayer. I may have to ask for help!

**Comment by leamas** [comment]
OK, closing

**Comment by leamas** [comment]
Hm... I have some time now, since I'm procrastinating... I looked into your current version and I'd say this is not really the way to do it (even if it might work). I'll have a look at it.

**Comment by Rasbats** [comment]
Many, many issues. Trying to get Appveyor working before moving to the other stuff.

**Comment by leamas** [comment]
> Many, many issues

Indeed. Note the PR on photolayer_pi
